# Batch 2: Companies 52 to 102 (Delhi-NCR AI Hub: Gurgaon, Noida, New Delhi AI Innovators & High-Growth Scaleups)

BATCH_2 = [
    {
        "id": 52,
        "company_name": "Spyne.ai",
        "website": "https://spyne.ai",
        "domain_sector": "AI Photography & Automotive Visual Cataloging",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $7M (Accel, Storm Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://spyne.ai/careers",
        "career_email": "sanjay@spyne.ai",
        "hiring_decision_maker": "Sanjay Kumar (CEO) & Deepti Prasad (Co-Founder)",
        "nalin_tech_fit_hook": "Computer vision pipelines for 360-degree vehicle studio rendering, background replacement, and mobile SDK optimization.",
        "outreach_status": "To Contact"
    },
    {
        "id": 53,
        "company_name": "Wobot.ai",
        "website": "https://wobot.ai",
        "domain_sector": "Computer Vision for Workplace SOP & Safety Analytics",
        "employee_count": "35-60",
        "funding_stage_investors": "Series A $2.5M (Sequoia Surge)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://wobot.ai/careers",
        "career_email": "adhiraj@wobot.ai",
        "hiring_decision_maker": "Adhiraj Lamba (Co-Founder) & Tapan Dixit (Co-Founder)",
        "nalin_tech_fit_hook": "CCTV video analytics, edge inference pipelines, and real-time compliance alerting dashboards in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 54,
        "company_name": "Inspektlabs",
        "website": "https://inspektlabs.com",
        "domain_sector": "Computer Vision Inspection for Auto & Insurance Claims",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Accel Atoms)",
        "work_model_location": "Delhi-NCR (New Delhi) / Remote",
        "career_page_url": "https://inspektlabs.com/careers",
        "career_email": "devesh@inspektlabs.com",
        "hiring_decision_maker": "Devesh Trivedi (Founder & CEO)",
        "nalin_tech_fit_hook": "360-degree damage detection on smartphones, 3D mesh reconstruction, and automated claim settlement APIs in FastAPI.",
        "outreach_status": "To Contact"
    },
    {
        "id": 55,
        "company_name": "Devnagri",
        "website": "https://devnagri.com",
        "domain_sector": "AI Indic Translation Engine & Localization APIs",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $1M (Inflection Point Ventures)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://devnagri.com/careers",
        "career_email": "nakul@devnagri.com",
        "hiring_decision_maker": "Nakul Kundra (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Neural machine translation for 22 Indian languages, document parsing microservices, and translation quality estimation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 56,
        "company_name": "Dubverse.ai",
        "website": "https://dubverse.ai",
        "domain_sector": "Generative AI Video Dubbing in 30+ Languages",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $800K (Kalaari Capital)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://dubverse.ai/careers",
        "career_email": "varshul@dubverse.ai",
        "hiring_decision_maker": "Varshul Goyal (Founder & CEO)",
        "nalin_tech_fit_hook": "Automated lip-sync generation, speaker voice cloning, and real-time multilingual video subtitles editor in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 57,
        "company_name": "NimbleBox.ai",
        "website": "https://nimblebox.ai",
        "domain_sector": "MLOps Platform for Generative AI Deployment",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Techstars, prominent angels)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://nimblebox.ai/careers",
        "career_email": "anshuman@nimblebox.ai",
        "hiring_decision_maker": "Anshuman Pandey (Founder & CEO)",
        "nalin_tech_fit_hook": "Kubernetes GPU orchestration, model serving gateways, and real-time inference latency optimization.",
        "outreach_status": "To Contact"
    },
    {
        "id": 58,
        "company_name": "Kello",
        "website": "https://kello.ai",
        "domain_sector": "AI-Native People Intelligence & Organizational Insights",
        "employee_count": "10-25",
        "funding_stage_investors": "Seed $2.6M (Peak XV Surge)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://kello.ai/careers",
        "career_email": "mona@kello.ai",
        "hiring_decision_maker": "Mona Gandhi (Co-Founder) & Subramanya Jingade (Co-Founder)",
        "nalin_tech_fit_hook": "Organizational network graph analysis, automated candidate sourcing agents, and talent engagement workflows.",
        "outreach_status": "To Contact"
    },
    {
        "id": 59,
        "company_name": "Round1",
        "website": "https://round1.ai",
        "domain_sector": "AI-Powered Candidate Screening & Voice Interviews",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://round1.ai/careers",
        "career_email": "team@round1.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time speech-to-text interview transcription, automated technical response evaluation, and proctoring pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 60,
        "company_name": "Zoop",
        "website": "https://zoop.one",
        "domain_sector": "Automated Document Verification & OCR AI Pipelines",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://zoop.one/careers",
        "career_email": "puneet@zoop.one",
        "hiring_decision_maker": "Puneet Sharma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated Aadhaar/PAN OCR document parsers, facial match verification algorithms, and low-latency KYC APIs in FastAPI.",
        "outreach_status": "To Contact"
    },
    {
        "id": 61,
        "company_name": "Attentive.ai",
        "website": "https://attentive.ai",
        "domain_sector": "Spatial AI & Computer Vision for Outdoor Infrastructure",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $7M (Peak XV Surge, Info Edge)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://attentive.ai/careers",
        "career_email": "shiva@attentive.ai",
        "hiring_decision_maker": "Shiva Dhawan (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-resolution satellite & aerial imagery segmentation, automated geospatial property takeoff, and interactive web maps.",
        "outreach_status": "To Contact"
    },
    {
        "id": 62,
        "company_name": "Toddle",
        "website": "https://toddleapp.com",
        "domain_sector": "AI-Powered Teaching OS & Classroom Copilot",
        "employee_count": "75-100",
        "funding_stage_investors": "Series A $17M (Tenacity Ventures, Matrix)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://toddleapp.com/careers",
        "career_email": "deepanshu@toddleapp.com",
        "hiring_decision_maker": "Deepanshu Arora (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Curriculum planning AI copilots, rubrics generation, and rich multi-media classroom interfaces built with Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 63,
        "company_name": "Infeedo",
        "website": "https://infeedo.com",
        "domain_sector": "Conversational AI Employee Experience (Amber AI)",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $12M (Tiger Global, Bling Capital)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://infeedo.com/careers",
        "career_email": "tanmaya@infeedo.com",
        "hiring_decision_maker": "Tanmaya Jain (Founder & CEO)",
        "nalin_tech_fit_hook": "Sentiment analysis on unstructured employee chats, automated burnout prediction models, and executive summary dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 64,
        "company_name": "AdmitKard",
        "website": "https://admitkard.com",
        "domain_sector": "AI-Driven International EdTech & Study Abroad Guidance",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $6M (GSV Ventures)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://admitkard.com/careers",
        "career_email": "piyush@admitkard.com",
        "hiring_decision_maker": "Piyush Bhartiya (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Course eligibility matching algorithms, statement of purpose AI review engines, and student portal interfaces in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 65,
        "company_name": "Fleetx.io",
        "website": "https://fleetx.io",
        "domain_sector": "AI IoT Platform for Intelligent Fleet Management",
        "employee_count": "60-90",
        "funding_stage_investors": "Series B $19M (India Quotient, Beenext)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://fleetx.io/careers",
        "career_email": "vineet@fleetx.io",
        "hiring_decision_maker": "Vineet Sharma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time telematics stream ingestion, driver fatigue video detection, and fuel theft prediction models.",
        "outreach_status": "To Contact"
    },
    {
        "id": 66,
        "company_name": "Bijak",
        "website": "https://bijak.in",
        "domain_sector": "Agri B2B Trade & Credit Assessment AI",
        "employee_count": "60-90",
        "funding_stage_investors": "Series B $20M (Bertelsmann, Sequoia Surge)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://bijak.in/careers",
        "career_email": "nukul@bijak.in",
        "hiring_decision_maker": "Nukul Upadhye (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Commodity price trend prediction models, creditworthiness scoring for rural traders, and high-volume billing ledger APIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 67,
        "company_name": "BeatO",
        "website": "https://beatoapp.com",
        "domain_sector": "AI-Powered Diabetes Management & Preventive Health",
        "employee_count": "60-90",
        "funding_stage_investors": "Series B $33M (Lightrock India, HealthQuad)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://beatoapp.com/careers",
        "career_email": "gautam@beatoapp.com",
        "hiring_decision_maker": "Gautam Chopra (Founder & CEO)",
        "nalin_tech_fit_hook": "IoT glucometer data sync, automated glycemic event alerts, and personalized nutrition recommendation agents.",
        "outreach_status": "To Contact"
    },
    {
        "id": 68,
        "company_name": "Redcliffe Labs",
        "website": "https://redclifferehab.com",
        "domain_sector": "AI Clinical Diagnostics & Precision Path Labs",
        "employee_count": "70-100",
        "funding_stage_investors": "Series B $61M (LeapFrog Investments)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://redclifferehab.com/careers",
        "career_email": "dheeraj@redclifferehab.com",
        "hiring_decision_maker": "Dheeraj Jain (Founder)",
        "nalin_tech_fit_hook": "Automated pathology report anomaly detection, diagnostic sample logistics routing, and patient health record portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 69,
        "company_name": "Recur Club",
        "website": "https://recurclub.com",
        "domain_sector": "Subscription & Recurring Revenue Financing Platform",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $30M debt/equity (Info Edge Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://recurclub.com/careers",
        "career_email": "eklavya@recurclub.com",
        "hiring_decision_maker": "Eklavya Gupta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated underwriting integrating Stripe/Chargebee APIs, churn risk analytics, and institutional capital bidding dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 70,
        "company_name": "Uolo",
        "website": "https://uolo.com",
        "domain_sector": "EdTech Platform & Parent-School Communication AI",
        "employee_count": "60-95",
        "funding_stage_investors": "Series A $22.5M (Winter Capital)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://uolo.com/careers",
        "career_email": "pallav@uolo.com",
        "hiring_decision_maker": "Pallav Pandey (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "K-12 interactive learning modules, high-frequency parent-teacher messaging engines, and automated student attendance tracking.",
        "outreach_status": "To Contact"
    },
    {
        "id": 71,
        "company_name": "ConveGenius",
        "website": "https://convegenius.ai",
        "domain_sector": "AI Conversational Learning Platform (SwiftChat)",
        "employee_count": "45-75",
        "funding_stage_investors": "Series A $5M (Michael & Susan Dell Foundation)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://convegenius.ai/careers",
        "career_email": "jairaj@convegenius.ai",
        "hiring_decision_maker": "Jairaj Bhattacharya (Founder & CEO)",
        "nalin_tech_fit_hook": "Conversational learning bots on WhatsApp, multimodal student assessments, and real-time state education analytics.",
        "outreach_status": "To Contact"
    },
    {
        "id": 72,
        "company_name": "Filo",
        "website": "https://findfilo.com",
        "domain_sector": "Instant 1-on-1 Live Tutoring & Student AI Copilot",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $23M (Anthos Capital)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://findfilo.com/careers",
        "career_email": "imbesat@findfilo.com",
        "hiring_decision_maker": "Imbesat Ahmad (Founder & CEO)",
        "nalin_tech_fit_hook": "Sub-60s tutor matching algorithms, WebRTC interactive video streaming classrooms, and OCR question parsing.",
        "outreach_status": "To Contact"
    },
    {
        "id": 73,
        "company_name": "Unstop",
        "website": "https://unstop.com",
        "domain_sector": "Early Talent Engagement, Hackathons & Job Matching AI",
        "employee_count": "50-80",
        "funding_stage_investors": "Seed $5M (Coursera, Mynavi)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://unstop.com/careers",
        "career_email": "ankit@unstop.com",
        "hiring_decision_maker": "Ankit Aggarwal (Founder & CEO)",
        "nalin_tech_fit_hook": "Hackathon submission grading pipelines, candidate skill matching algorithms, and enterprise employer hiring dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 74,
        "company_name": "Instahyre",
        "website": "https://instahyre.com",
        "domain_sector": "AI-Powered Intelligent Talent Matching & Sourcing",
        "employee_count": "30-50",
        "funding_stage_investors": "Bootstrapped & Highly Profitable",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://instahyre.com/careers",
        "career_email": "sarbojit@instahyre.com",
        "hiring_decision_maker": "Sarbojit Mallick (Co-Founder)",
        "nalin_tech_fit_hook": "Candidate resume embedding search, algorithmic recruiter matching, and automated candidate engagement funnels in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 75,
        "company_name": "OneBanc",
        "website": "https://onebanc.ai",
        "domain_sector": "AI Neo-Banking, Payroll & Smart Employee Benefits",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $2.5M (Info Edge Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://onebanc.ai/careers",
        "career_email": "vibhore@onebanc.ai",
        "hiring_decision_maker": "Vibhore Goyal (Founder & CEO)",
        "nalin_tech_fit_hook": "Corporate payroll API rails, conversational expense categorization, and automated banking ledger reconciliation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 76,
        "company_name": "Leena AI",
        "website": "https://leena.ai",
        "domain_sector": "Autonomous Work AI Assistant for Enterprise Employees",
        "employee_count": "65-95",
        "funding_stage_investors": "Series B $30M (Bessemer, Greycroft)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://leena.ai/careers",
        "career_email": "adit@leena.ai",
        "hiring_decision_maker": "Adit Jain (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Autonomous HR policy Q&A agents, ticket resolution workflows across Slack/Teams, and custom LLM evals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 77,
        "company_name": "HROne",
        "website": "https://hrone.cloud",
        "domain_sector": "Cloud HCM & Automated HR Operations Suite",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $4M (Insitor Partners)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://hrone.cloud/careers",
        "career_email": "karan@hrone.cloud",
        "hiring_decision_maker": "Karan Jain (Founder & CEO)",
        "nalin_tech_fit_hook": "Inbox-first HR task automation, salary calculation engines in FastAPI, and interactive performance tracking UIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 78,
        "company_name": "SecureNow",
        "website": "https://securenow.in",
        "domain_sector": "Commercial Insurance & Claims Automation Platform",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $6M (Apis Partners)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://securenow.in/careers",
        "career_email": "kapil@securenow.in",
        "hiring_decision_maker": "Kapil Mehta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated group health policy quote engines, OCR claims document parsing, and employee insurance self-serve portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 79,
        "company_name": "Sproutlogix",
        "website": "https://sproutlogix.com",
        "domain_sector": "AI Capability Development & Employee Upskilling",
        "employee_count": "20-40",
        "funding_stage_investors": "Pre-Series A $1M (Indian angel networks)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://sproutlogix.com/careers",
        "career_email": "devang@sproutlogix.com",
        "hiring_decision_maker": "Devang Shah (Founder & CEO)",
        "nalin_tech_fit_hook": "Personalized AI coaching chat bots, skill gap assessments, and organizational learning analytics in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 80,
        "company_name": "KOGO OS",
        "website": "https://kogo.ai",
        "domain_sector": "Modular Multi-Agent AI OS for Enterprise & Mobility",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $1.5M (MapmyIndia)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://kogo.ai/careers",
        "career_email": "raj@kogo.ai",
        "hiring_decision_maker": "Raj K Gopalakrishnan (CEO)",
        "nalin_tech_fit_hook": "Modular agent plug-and-play framework, low-latency API integration orchestration, and vehicle in-cabin AI assistants.",
        "outreach_status": "To Contact"
    },
    {
        "id": 81,
        "company_name": "Sunfox Technologies",
        "website": "https://sunfox.in",
        "domain_sector": "Portable 12-Lead AI ECG Diagnostics (Spandan)",
        "employee_count": "25-50",
        "funding_stage_investors": "Seed $1.5M (Shark Tank India, angel syndicates)",
        "work_model_location": "Delhi-NCR / Dehradun",
        "career_page_url": "https://sunfox.in/careers",
        "career_email": "rajat@sunfox.in",
        "hiring_decision_maker": "Rajat Jain (Founder & CEO)",
        "nalin_tech_fit_hook": "Signal processing for noisy mobile ECG leads, deep learning arrhythmia detection, and doctor teleconsultation portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 82,
        "company_name": "Revrag.ai",
        "website": "https://revrag.ai",
        "domain_sector": "Autonomous AI Revenue Agents & Multimodal Outreach",
        "employee_count": "12-25",
        "funding_stage_investors": "Pre-Seed $600K (Powerhouse Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://revrag.ai/careers",
        "career_email": "ashutosh@revrag.ai",
        "hiring_decision_maker": "Ashutosh Singhal (Founder & CEO)",
        "nalin_tech_fit_hook": "Voice/text AI BDR agents capable of researching prospects, making initial discovery phone calls, and booking calendar meetings.",
        "outreach_status": "To Contact"
    },
    {
        "id": 83,
        "company_name": "Ritivel",
        "website": "https://ritivel.com",
        "domain_sector": "Automated Testing & Evals for Multi-Agent Systems",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2M (Y Combinator S24)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://ritivel.com/careers",
        "career_email": "founders@ritivel.com",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "End-to-end regression test harnesses for LLM applications, deterministic prompt evals, and automated hallucination alerts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 84,
        "company_name": "Smarter.Codes",
        "website": "https://smarter.codes",
        "domain_sector": "Semantic Extraction & NLP Knowledge Mining Engine",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Indian Angel Network)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://smarter.codes/careers",
        "career_email": "parag@smarter.codes",
        "hiring_decision_maker": "Parag Arora (Co-Founder)",
        "nalin_tech_fit_hook": "Taxonomy generation from enterprise text, structured schema extraction, and semantic search APIs in Python.",
        "outreach_status": "To Contact"
    },
    {
        "id": 85,
        "company_name": "Rezo.ai",
        "website": "https://rezo.ai",
        "domain_sector": "Cognitive Contact Center AI & Omnichannel Automation",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $1M (Modulor Capital)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://rezo.ai/careers",
        "career_email": "manish@rezo.ai",
        "hiring_decision_maker": "Manish Gupta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automating voice, email, and chat queries with conversational AI, real-time agent assist, and analytics dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 86,
        "company_name": "Kisan Network",
        "website": "https://kisannetwork.com",
        "domain_sector": "Tech-Enabled Supply Chain for Smallholder Farmers",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $3M (Y Combinator, Thiel Foundation)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://kisannetwork.com/careers",
        "career_email": "aditya@kisannetwork.com",
        "hiring_decision_maker": "Aditya Agarwalla (Co-Founder)",
        "nalin_tech_fit_hook": "Produce pricing algorithms, direct-from-farm freight routing, and vernacular mobile apps for agricultural trade.",
        "outreach_status": "To Contact"
    },
    {
        "id": 87,
        "company_name": "VdoCipher",
        "website": "https://vdocipher.com",
        "domain_sector": "Secure Video Hosting & Encrypted Streaming Tech",
        "employee_count": "20-40",
        "funding_stage_investors": "Bootstrapped & Highly Profitable",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://vdocipher.com/careers",
        "career_email": "siddhant@vdocipher.com",
        "hiring_decision_maker": "Siddhant Jain (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "DRM video encryption algorithms, dynamic watermarking rendering on HTML5 players, and streaming analytics pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 88,
        "company_name": "Restroworks (Posist)",
        "website": "https://restroworks.com",
        "domain_sector": "Cloud Restaurant POS & Inventory Management AI",
        "employee_count": "75-100",
        "funding_stage_investors": "Series A $5M (Indian angel networks)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://restroworks.com/careers",
        "career_email": "ashish@restroworks.com",
        "hiring_decision_maker": "Ashish Tulsian (Founder & CEO)",
        "nalin_tech_fit_hook": "High-throughput restaurant billing microservices, raw material consumption forecast AI, and kitchen display interfaces.",
        "outreach_status": "To Contact"
    },
    {
        "id": 89,
        "company_name": "Wingify (VWO)",
        "website": "https://vwo.com",
        "domain_sector": "A/B Testing, Conversion Optimization & Analytics",
        "employee_count": "75-100",
        "funding_stage_investors": "Bootstrapped & Highly Profitable",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://vwo.com/careers",
        "career_email": "paras@wingify.com",
        "hiring_decision_maker": "Paras Chopra (Founder & Chairman)",
        "nalin_tech_fit_hook": "Ultra-fast client DOM manipulation scripts, Bayesian statistical test evaluation engines, and heatmap analytics.",
        "outreach_status": "To Contact"
    },
    {
        "id": 90,
        "company_name": "SquadStack",
        "website": "https://squadstack.com",
        "domain_sector": "AI-Driven Telecalling & Sales Funnel Orchestration",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $12M (Chiratae Ventures)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://squadstack.com/careers",
        "career_email": "apurv@squadstack.com",
        "hiring_decision_maker": "Apurv Agrawal (Founder & CEO)",
        "nalin_tech_fit_hook": "Predictive lead scoring algorithms, speech emotion analysis on calls, and distributed telecaller workflow routing.",
        "outreach_status": "To Contact"
    },
    {
        "id": 91,
        "company_name": "DocPrime",
        "website": "https://docprime.com",
        "domain_sector": "Teleconsultation & Preventive Healthcare Booking",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $10M (PB Fintech)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://docprime.com/careers",
        "career_email": "ashish@docprime.com",
        "hiring_decision_maker": "Ashish Gupta (CEO)",
        "nalin_tech_fit_hook": "Real-time doctor video consultation queues, digital health record lockers, and automated lab test appointment engines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 92,
        "company_name": "Baaz Bikes",
        "website": "https://baazbikes.com",
        "domain_sector": "EV Gig Delivery Platform & Fast Battery Swapping",
        "employee_count": "30-60",
        "funding_stage_investors": "Series A $8M (BIG Capital)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://baazbikes.com/careers",
        "career_email": "anubhav@baazbikes.com",
        "hiring_decision_maker": "Anubhav Sharma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated battery swap cabinet IoT controllers, rider app real-time telematics, and battery lifecycle predictive analytics.",
        "outreach_status": "To Contact"
    },
    {
        "id": 93,
        "company_name": "Revfin",
        "website": "https://revfin.in",
        "domain_sector": "Financial Inclusion & EV Commercial Loan AI",
        "employee_count": "50-80",
        "funding_stage_investors": "Series B $14M (Omidyar Network)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://revfin.in/careers",
        "career_email": "sameer@revfin.in",
        "hiring_decision_maker": "Sameer Aggarwal (Founder & CEO)",
        "nalin_tech_fit_hook": "Psychometric and biometric credit scoring algorithms for non-traditional borrowers, and vehicle IoT immobilizer integrations.",
        "outreach_status": "To Contact"
    },
    {
        "id": 94,
        "company_name": "AltMobility",
        "website": "https://alt-mobility.com",
        "domain_sector": "Commercial EV Fleet Leasing & Asset Intelligence",
        "employee_count": "25-50",
        "funding_stage_investors": "Seed $6M (Eurazeo, Shell Ventures)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://alt-mobility.com/careers",
        "career_email": "dev@alt-mobility.com",
        "hiring_decision_maker": "Dev Arora (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Fleet telematics data ingestion, battery state-of-health monitoring models, and lease payment management portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 95,
        "company_name": "Hopcharge",
        "website": "https://hopcharge.com",
        "domain_sector": "On-Demand Doorstep EV Mobile Fast Charging",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $1.5M (Prominent angels)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://hopcharge.com/careers",
        "career_email": "arjun@hopcharge.com",
        "hiring_decision_maker": "Arjun Singh (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Mobile energy pod routing optimization, customer doorstep charging scheduler, and charger IoT telemetry.",
        "outreach_status": "To Contact"
    },
    {
        "id": 96,
        "company_name": "Vecmocon Technologies",
        "website": "https://vecmocon.com",
        "domain_sector": "EV Battery Intelligence & Smart Vehicle Controllers",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $5.2M (Tiger Global, Blume Ventures)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://vecmocon.com/careers",
        "career_email": "peeyush@vecmocon.com",
        "hiring_decision_maker": "Peeyush Asati (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Smart Battery Management System (BMS) telemetry, CAN bus data extraction, and real-time thermal runaway alert models.",
        "outreach_status": "To Contact"
    },
    {
        "id": 97,
        "company_name": "Sheru",
        "website": "https://sheru.se",
        "domain_sector": "Energy Cloud & Virtual Power Plants for EV Batteries",
        "employee_count": "25-45",
        "funding_stage_investors": "Series A $5M (Micelio Fund)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://sheru.se/careers",
        "career_email": "ankit@sheru.se",
        "hiring_decision_maker": "Ankit Mittal (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Virtual power plant energy arbitrage algorithms, grid frequency balancing models, and EV battery swap telemetry.",
        "outreach_status": "To Contact"
    },
    {
        "id": 98,
        "company_name": "VedaLabs",
        "website": "https://vedalabs.in",
        "domain_sector": "Computer Vision Analytics for Retail Footfall & Demographics",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $500K (MapmyIndia)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://vedalabs.in/careers",
        "career_email": "veer@vedalabs.in",
        "hiring_decision_maker": "Veer Mishra (Founder & CEO)",
        "nalin_tech_fit_hook": "Edge computer vision tracking on commodity cameras, in-store dwell time heatmaps, and retail conversion analytics.",
        "outreach_status": "To Contact"
    },
    {
        "id": 99,
        "company_name": "PerSapien",
        "website": "https://persapien.com",
        "domain_sector": "AI-Enabled Medical Diagnostics & Disease Sensors",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Indian angel syndicates)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://persapien.com/careers",
        "career_email": "shashi@persapien.com",
        "hiring_decision_maker": "Dr. Shashi Ranjan (Founder & CEO)",
        "nalin_tech_fit_hook": "Deep learning bio-signal processing, diagnostic sensor firmware communication, and automated clinical test report generators.",
        "outreach_status": "To Contact"
    },
    {
        "id": 100,
        "company_name": "LegalKart",
        "website": "https://legalkart.com",
        "domain_sector": "On-Demand Legal Consultation & LegalTech AI",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $1M (Indian angel syndicates)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://legalkart.com/careers",
        "career_email": "arvind@legalkart.com",
        "hiring_decision_maker": "Arvind Singhatiya (Founder & CEO)",
        "nalin_tech_fit_hook": "Lawyer consultation audio-video pipelines, automated legal document drafting in Next.js, and case tracking APIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 101,
        "company_name": "SpotDraft",
        "website": "https://spotdraft.com",
        "domain_sector": "AI Contract Lifecycle Management & Legal Copilot",
        "employee_count": "60-95",
        "funding_stage_investors": "Series A $26M (Premji Invest)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://spotdraft.com/careers",
        "career_email": "shashank@spotdraft.com",
        "hiring_decision_maker": "Shashank Bijapur (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated contract clause redlining with LLMs, legal document OCR, and custom contract review workflows in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 102,
        "company_name": "Grip Invest",
        "website": "https://gripinvest.in",
        "domain_sector": "Alternative Investment & Asset-Backed Wealth Platform",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $10M (Stride Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://gripinvest.in/careers",
        "career_email": "nikhil@gripinvest.in",
        "hiring_decision_maker": "Nikhil Aggarwal (Founder & CEO)",
        "nalin_tech_fit_hook": "Securitized debt instrument checkout flows, KYC investor onboarding APIs, and portfolio payout reconciliation backends.",
        "outreach_status": "To Contact"
    }
]
