# Batch 7: Companies 306 to 355 (HealthTech, EdTech, MediaTech, Creator AI, WorkTech & Multi-Agent Frameworks)

BATCH_7 = [
    {'career_email': 'vikas@hexahealth.com',
 'career_page_url': 'https://www.hexahealth.com/careers',
 'company_name': 'HexaHealth',
 'domain_sector': 'AI Surgery Care Concierge & Hospital Navigation Platform',
 'employee_count': '55-85',
 'funding_stage_investors': 'Seed $4.5M (Oommen Vadaketh, prominent healthcare angels)',
 'hiring_decision_maker': 'Vikas Chauhan (Co-Founder & CEO)',
 'id': 306,
 'nalin_tech_fit_hook': 'Building surgical recommendation matching algorithms, patient EHR clinical summarization '
                        'pipelines, and real-time hospital bed discovery backends.',
 'outreach_status': 'To Contact',
 'website': 'https://www.hexahealth.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'vikalp@eka.care',
 'career_page_url': 'https://www.eka.care/careers',
 'company_name': 'Eka Care',
 'domain_sector': 'AI Electronic Medical Records & ABHA Health Locker',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $15M (Hummingbird Ventures, 3one4 Capital)',
 'hiring_decision_maker': 'Vikalp Sahni (Founder & CEO)',
 'id': 307,
 'nalin_tech_fit_hook': 'Developing ABDM/ABHA unified healthcare record sync APIs, prescription NLP entity extraction '
                        'pipelines, and doctor EMR web interfaces in Next.js.',
 'outreach_status': 'To Contact',
 'website': 'https://www.eka.care',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'ravjot@medulance.com',
 'career_page_url': 'https://medulance.com',
 'company_name': 'Medulance',
 'domain_sector': 'AI Emergency Dispatch & Smart 5G Ambulance Network',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $3M (Alkemi Growth Capital)',
 'hiring_decision_maker': 'Ravjot Singh Arora (Co-Founder & CEO)',
 'id': 308,
 'nalin_tech_fit_hook': 'Implementing real-time GPS ambulance dispatch routing algorithms, 5G telemetry vital '
                        'transmission streams, and emergency hospital ER intake dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://medulance.com',
 'work_model_location': 'Delhi-NCR (Delhi/Noida) / Hybrid'},
    {'career_email': 'arun@janitri.in',
 'career_page_url': 'https://janitri.in',
 'company_name': 'Janitri',
 'domain_sector': 'AI Fetal & Maternal Healthcare Monitoring Hardware & Cloud',
 'employee_count': '30-55',
 'funding_stage_investors': 'Pre-Series A $1.5M (SIDBI, angel investors)',
 'hiring_decision_maker': 'Arun Agarwal (Founder & CEO)',
 'id': 309,
 'nalin_tech_fit_hook': 'Developing real-time fetal heart rate acoustic signal processing, labor contraction pattern '
                        'classification models, and nurse mobile alert webhooks.',
 'outreach_status': 'To Contact',
 'website': 'https://janitri.in',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'priyadarshee@curebay.com',
 'career_page_url': 'https://curebay.com/careers',
 'company_name': 'Curebay',
 'domain_sector': 'Hybrid Rural Healthcare & AI Telemedicine E-Clinics',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $7.5M (Elevar Equity)',
 'hiring_decision_maker': 'Priyadarshee Mohapatra (Founder & CEO)',
 'id': 310,
 'nalin_tech_fit_hook': 'Architecting low-bandwidth telemedicine video streaming gateways, automated rural pharmacy '
                        'dispensing ledgers, and lab test booking APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://curebay.com',
 'work_model_location': 'Delhi-NCR / Bhubaneswar / Remote'},
    {'career_email': 'mohit@ultrahuman.com',
 'career_page_url': 'https://www.ultrahuman.com/careers',
 'company_name': 'Ultrahuman',
 'domain_sector': 'Metabolic Health Ring & Biomarker Intelligence Cloud',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $35M (Blume Ventures, Steadview Capital)',
 'hiring_decision_maker': 'Mohit Kumar (Founder & CEO)',
 'id': 311,
 'nalin_tech_fit_hook': 'Streaming PPG optical biometric timeseries data, sleep circadian rhythm classification '
                        'algorithms, and metabolic score sync microservices in FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://www.ultrahuman.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'madan@sugarfit.com',
 'career_page_url': 'https://www.sugarfit.com',
 'company_name': 'Sugar.fit',
 'domain_sector': 'Continuous Glucose AI & Diabetes Reversal HealthTech',
 'employee_count': '55-85',
 'funding_stage_investors': 'Series A $11M (MassMutual Ventures, Cure.fit / Cult.fit)',
 'hiring_decision_maker': 'Madan Somasundaram (Co-Founder & CEO)',
 'id': 312,
 'nalin_tech_fit_hook': 'Developing real-time CGM glucose spike prediction algorithms, computer vision meal photo '
                        'carbohydrate estimation, and habit coaching agents.',
 'outreach_status': 'To Contact',
 'website': 'https://www.sugarfit.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'dhruv@orangehealth.in',
 'career_page_url': 'https://www.orangehealth.in/careers',
 'company_name': 'Orange Health',
 'domain_sector': 'On-Demand 60-Minute Diagnostic Lab Cloud & Phlebotomy',
 'employee_count': '70-100',
 'funding_stage_investors': 'Series B $25M (General Catalyst, Bertelsmann India)',
 'hiring_decision_maker': 'Dhruv Gupta (Co-Founder & CEO)',
 'id': 313,
 'nalin_tech_fit_hook': 'Building automated phlebotomist geographic dispatch engines, smart temperature-controlled '
                        'sample batching, and automated lab analyzer LIMS connectors.',
 'outreach_status': 'To Contact',
 'website': 'https://www.orangehealth.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Bangalore'},
    {'career_email': 'harshit@doceree.com',
 'career_page_url': 'https://doceree.com/careers/',
 'company_name': 'Doceree',
 'domain_sector': 'Programmatic Healthcare Marketing & AI Identity Platform',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $35M (Creaegis, Eight Roads Ventures)',
 'hiring_decision_maker': 'Dr. Harshit Jain (Founder & CEO)',
 'id': 314,
 'nalin_tech_fit_hook': 'Constructing physician identity resolution graphs (NPI/MCI verification), real-time '
                        'programmatic ad bid evaluators, and HIPAA compliance filters.',
 'outreach_status': 'To Contact',
 'website': 'https://doceree.com',
 'work_model_location': 'Delhi-NCR (Noida) / Hybrid Remote'},
    {'career_email': 'khet@claimbuddy.in',
 'career_page_url': 'https://claimbuddy.in',
 'company_name': 'ClaimBuddy',
 'domain_sector': 'Hospital Health Insurance Claim Processing AI',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $5M (Bharat Innovation Fund, Chiratae Ventures)',
 'hiring_decision_maker': 'Khet Singh (Co-Founder & CEO)',
 'id': 315,
 'nalin_tech_fit_hook': 'Developing medical bill optical parsing engines, insurance policy deduction adjudication '
                        'rules, and hospital desk cashless claim portals.',
 'outreach_status': 'To Contact',
 'website': 'https://claimbuddy.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'rahul@getvital.in',
 'career_page_url': 'https://www.getvital.in',
 'company_name': 'Vital',
 'domain_sector': 'Personalized Health Coverage & Wellness Rewards Platform',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $3M (BLinC Invest, Venture Catalysts)',
 'hiring_decision_maker': 'Rahul Harkisanka (Co-Founder & CEO)',
 'id': 316,
 'nalin_tech_fit_hook': 'Building dynamic health policy underwriting models, biometric step/exercise reward '
                        'calculation pipelines, and OPD reimbursement webhooks.',
 'outreach_status': 'To Contact',
 'website': 'https://www.getvital.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'suraj@clinikk.com',
 'career_page_url': 'https://clinikk.com',
 'company_name': 'Clinikk',
 'domain_sector': 'Primary Care Health Subscriptions & Outpatient Care Clinics',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $4M (MassMutual Ventures, Times Internet)',
 'hiring_decision_maker': 'Dr. Suraj Baliga (Co-Founder & CEO)',
 'id': 317,
 'nalin_tech_fit_hook': 'Designing integrated electronic health consultation portals, medicine delivery fulfillment '
                        'queues, and preventive health screening workflows.',
 'outreach_status': 'To Contact',
 'website': 'https://clinikk.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'sahil@fitelo.co',
 'career_page_url': 'https://fitelo.co/careers/',
 'company_name': 'Fitelo',
 'domain_sector': 'AI-Driven Personalized Weight Management & Wellness Care',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $5M (CareCapital, angel syndicates)',
 'hiring_decision_maker': 'Sahil Bansal (Co-Founder & CEO)',
 'id': 318,
 'nalin_tech_fit_hook': 'Building natural language diet log analyzers, personalized nutrient macro meal plan '
                        'generators, and automated lifestyle habit adherence models.',
 'outreach_status': 'To Contact',
 'website': 'https://fitelo.co',
 'work_model_location': 'Delhi-NCR (Chandigarh/Delhi) / Hybrid'},
    {'career_email': 'arbinder@fitterfly.com',
 'career_page_url': 'https://www.fitterfly.com/careers',
 'company_name': 'Fitterfly',
 'domain_sector': 'Digital Therapeutics for Diabetes & Metabolic Condition Care',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $12M (Amazon Smbhav Venture Fund, Fireside)',
 'hiring_decision_maker': 'Dr. Arbinder Singal (Co-Founder & CEO)',
 'id': 319,
 'nalin_tech_fit_hook': 'Implementing glycemic index food prediction models, clinical milestone tracking engines, and '
                        'doctor-patient telehealth collaboration portals.',
 'outreach_status': 'To Contact',
 'website': 'https://www.fitterfly.com',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR friendly'},
    {'career_email': 'abhishek@wellthy.care',
 'career_page_url': 'https://www.wellthytherapeutics.com',
 'company_name': 'Wellthy Therapeutics',
 'domain_sector': 'Enterprise Digital Health & Prescription Therapy Applications',
 'employee_count': '40-65',
 'funding_stage_investors': 'Pre-Series A $4M (Saama Capital, prominent funds)',
 'hiring_decision_maker': 'Abhishek Shah (Co-Founder & CEO)',
 'id': 320,
 'nalin_tech_fit_hook': 'Architecting multi-language clinical AI chatbots, medical device Bluetooth data sync '
                        'microservices, and pharma enterprise outcome reporting.',
 'outreach_status': 'To Contact',
 'website': 'https://www.wellthytherapeutics.com',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR friendly'},
    {'career_email': 'vinay@stage.in',
 'career_page_url': 'https://stage.in',
 'company_name': 'Stage',
 'domain_sector': 'Dialect OTT & Regional AI Content Platform for Bharat',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $4.8M (Blume Ventures, Inflection Point Ventures)',
 'hiring_decision_maker': 'Vinay Singhal (Co-Founder & CEO)',
 'id': 321,
 'nalin_tech_fit_hook': 'Building adaptive video bit-rate streaming transcoders for Tier 2/3 networks, vernacular '
                        'speech subtitle generation, and personalized recommendations.',
 'outreach_status': 'To Contact',
 'website': 'https://stage.in',
 'work_model_location': 'Delhi-NCR (Noida) / Hybrid Remote'},
    {'career_email': 'varun@bolo.live',
 'career_page_url': 'https://bolo.live',
 'company_name': 'Bolo Live',
 'domain_sector': 'Live Streaming & Vernacular Creator Engagement AI',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $2.4M (TBN, prominent angels)',
 'hiring_decision_maker': 'Varun Saxena (Founder & CEO)',
 'id': 322,
 'nalin_tech_fit_hook': 'Building ultra-low latency WebRTC video broadcast channels, real-time micro-gifting '
                        'transactional ledgers, and automated toxic comment moderation.',
 'outreach_status': 'To Contact',
 'website': 'https://bolo.live',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'sandeep@khabri.app',
 'career_page_url': 'https://khabri.app',
 'company_name': 'Khabri',
 'domain_sector': 'Vernacular Audio Learning & Speech Content AI Platform',
 'employee_count': '25-50',
 'funding_stage_investors': 'Seed $2.1M (Y Combinator, Liquid 2 Ventures)',
 'hiring_decision_maker': 'Sandeep Singh (Co-Founder & CEO)',
 'id': 323,
 'nalin_tech_fit_hook': 'Developing audio voice-cloning pipelines, Hindi/vernacular automated text-to-speech '
                        'synthesis, and background audio streaming microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://khabri.app',
 'work_model_location': 'Delhi-NCR (Gurgaon/Delhi) / Remote'},
    {'career_email': 'parth@getstan.app',
 'career_page_url': 'https://getstan.app',
 'company_name': 'STAN',
 'domain_sector': 'Gaming Creator Community & AI Engagement Platform',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $2.5M (General Catalyst, GFR Fund)',
 'hiring_decision_maker': 'Parth Chadha (Co-Founder & CEO)',
 'id': 324,
 'nalin_tech_fit_hook': 'Building real-time gaming chat websockets, digital collectible reward drops, and automated '
                        'esports creator engagement leaderboards.',
 'outreach_status': 'To Contact',
 'website': 'https://getstan.app',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'piyush@rooter.gg',
 'career_page_url': 'https://www.rooter.gg',
 'company_name': 'Rooter',
 'domain_sector': 'Game Streaming & Esports Broadcasting Media Platform',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $25M (Lightbox, March Capital)',
 'hiring_decision_maker': 'Piyush Kumar (Founder & CEO)',
 'id': 325,
 'nalin_tech_fit_hook': 'Constructing interactive live esports stream overlays, real-time viewer engagement '
                        'predictions, and high-concurrency tournament brackets.',
 'outreach_status': 'To Contact',
 'website': 'https://www.rooter.gg',
 'work_model_location': 'Delhi-NCR (New Delhi) / Hybrid'},
    {'career_email': 'prateek@kutumb.app',
 'career_page_url': 'https://kutumb.app',
 'company_name': 'Kutumb',
 'domain_sector': 'Community & Cultural Social Network Platform for Bharat',
 'employee_count': '55-80',
 'funding_stage_investors': 'Series A $26M (Tiger Global, Peak XV Surge)',
 'hiring_decision_maker': 'Prateek Mohapatra (Co-Founder & CEO)',
 'id': 326,
 'nalin_tech_fit_hook': 'Building high-throughput social feed ranking pipelines, vernacular media transcoding '
                        'microservices, and community moderation workflows.',
 'outreach_status': 'To Contact',
 'website': 'https://kutumb.app',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'manish@kratosstudios.com',
 'career_page_url': 'https://kratosstudios.com',
 'company_name': 'Kratos Studios',
 'domain_sector': 'Web3 Gaming Ecosystem & Player Identity AI Platform',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $20M (Accel, Prosus Ventures)',
 'hiring_decision_maker': 'Manish Agarwal (Co-Founder & CEO)',
 'id': 327,
 'nalin_tech_fit_hook': 'Developing cross-game decentralized player identity graphs, automated tournament payout smart '
                        'contracts, and anti-fraud bot detection.',
 'outreach_status': 'To Contact',
 'website': 'https://kratosstudios.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'soham@gamerji.com',
 'career_page_url': 'https://gamerji.com',
 'company_name': 'Gamerji',
 'domain_sector': 'Esports Tournament Engine & Skill Matchmaking AI',
 'employee_count': '20-35',
 'funding_stage_investors': 'Pre-Series A $1M (Unicorn India Ventures)',
 'hiring_decision_maker': 'Soham Thacker (Founder & CEO)',
 'id': 328,
 'nalin_tech_fit_hook': 'Implementing real-time ELO skill-rating matchmaking algorithms, automated screenshot victory '
                        'OCR verification, and tournament lobby rooms.',
 'outreach_status': 'To Contact',
 'website': 'https://gamerji.com',
 'work_model_location': 'Remote / Ahmedabad / Delhi-NCR friendly'},
    {'career_email': 'prashant@hypergro.ai',
 'career_page_url': 'https://hypergro.ai',
 'company_name': 'HyperGro.ai',
 'domain_sector': 'AI Video Advertising & UGC Creation Engine for Brands',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.4M (Silverneedle Ventures, prominent angels)',
 'hiring_decision_maker': 'Prashant Mathur (Co-Founder & CEO)',
 'id': 329,
 'nalin_tech_fit_hook': 'Automating viral video ad script generation via LLMs, dynamic video frame splicing, and ROAS '
                        'performance analytics in FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://hypergro.ai',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'mandar@neuralgarage.com',
 'career_page_url': 'https://www.neuralgarage.com',
 'company_name': 'NeuralGarage',
 'domain_sector': 'Generative AI Visual Dubbing & Lip Sync (VisualDub)',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.45M (Exfinity Venture Partners)',
 'hiring_decision_maker': 'Mandar Natekar (Co-Founder & CEO)',
 'id': 330,
 'nalin_tech_fit_hook': 'Building neural photorealistic lip motion re-generation models, speech phoneme-to-viseme '
                        'alignment pipelines, and distributed render queues.',
 'outreach_status': 'To Contact',
 'website': 'https://www.neuralgarage.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'aravind@ayna.ai',
 'career_page_url': 'https://ayna.ai',
 'company_name': 'Ayna.ai',
 'domain_sector': 'AI Fashion Studio & Synthetic Model Generation for E-Commerce',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.5M (Inflexor Ventures, prominent retail angels)',
 'hiring_decision_maker': 'Aravind Murthy (Co-Founder & CEO)',
 'id': 331,
 'nalin_tech_fit_hook': 'Developing controllable diffusion image inpainting models for apparel try-on, automated '
                        'shadow rendering, and fast studio batch inference.',
 'outreach_status': 'To Contact',
 'website': 'https://ayna.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'karan@zeko.ai',
 'career_page_url': 'https://zeko.ai',
 'company_name': 'Zeko.ai',
 'domain_sector': 'Virtual Dressing Room & 3D Fashion AI Experience',
 'employee_count': '12-25',
 'funding_stage_investors': 'Seed $1M (Indian angel networks & fashion founders)',
 'hiring_decision_maker': 'Karan Mishra (Founder & CEO)',
 'id': 332,
 'nalin_tech_fit_hook': 'Building 3D cloth drape mesh simulations, mobile camera human body measurement estimation, '
                        'and interactive web virtual dressing rooms.',
 'outreach_status': 'To Contact',
 'website': 'https://zeko.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'krik@kubric.io',
 'career_page_url': 'https://kubric.io',
 'company_name': 'Kubric',
 'domain_sector': 'AI Creative Automation & Video Asset Engine for Enterprises',
 'employee_count': '20-35',
 'funding_stage_investors': 'Seed $1.5M (Peak XV Surge, prominent SaaS angels)',
 'hiring_decision_maker': 'Krik Gonsalves (Co-Founder & CEO)',
 'id': 333,
 'nalin_tech_fit_hook': 'Automating enterprise brand template rendering, multi-aspect-ratio programmatic video '
                        'generation, and distributed cloud media encoders.',
 'outreach_status': 'To Contact',
 'website': 'https://kubric.io',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'tarun@flowace.ai',
 'career_page_url': 'https://flowace.ai',
 'company_name': 'Flowace',
 'domain_sector': 'AI Workforce Analytics & Time Intelligence Platform',
 'employee_count': '20-35',
 'funding_stage_investors': 'Seed $1M (Indian angel networks & seed funds)',
 'hiring_decision_maker': 'Tarun Kumar (Co-Founder & CEO)',
 'id': 334,
 'nalin_tech_fit_hook': 'Developing automated desktop background activity trackers, productivity pattern anomaly '
                        'detection, and billable hour classification models.',
 'outreach_status': 'To Contact',
 'website': 'https://flowace.ai',
 'work_model_location': 'Delhi-NCR (Noida) / Hybrid'},
    {'career_email': 'kinner@knorish.com',
 'career_page_url': 'https://knorish.com/careers',
 'company_name': 'Knorish',
 'domain_sector': 'AI Funnels & Course Creation Platform for Creators',
 'employee_count': '35-60',
 'funding_stage_investors': 'Pre-Series A $1.5M (Pentathlon Ventures, 100X.VC)',
 'hiring_decision_maker': 'Kinner Sacchdev (Co-Founder & CEO)',
 'id': 335,
 'nalin_tech_fit_hook': 'Constructing generative AI course curriculum builders, automated sales landing page '
                        'copywriters, and video DRM distribution microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://knorish.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'amar@bito.ai',
 'career_page_url': 'https://bito.ai/careers/',
 'company_name': 'Bito.ai',
 'domain_sector': 'AI Coding Assistant & PR Review Automation Platform',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $3.2M (Eniac Ventures, prominent engineering angels)',
 'hiring_decision_maker': 'Amar Goel (Co-Founder & CEO)',
 'id': 336,
 'nalin_tech_fit_hook': 'Developing automated AST code diff analyzers, Git hook CI/CD pull request reviewers, and code '
                        'security vulnerability scanning models.',
 'outreach_status': 'To Contact',
 'website': 'https://bito.ai',
 'work_model_location': 'Fully Remote (India) / Pune'},
    {'career_email': 'annil@wurkr.uk',
 'career_page_url': 'https://wurkr.uk',
 'company_name': 'Wurkr',
 'domain_sector': 'Virtual AI Workspace & Spatial Collaboration Platform',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $2M (Hindustan Media Ventures, prominent angels)',
 'hiring_decision_maker': 'Annil Chandel (Co-Founder & CEO)',
 'id': 337,
 'nalin_tech_fit_hook': 'Building spatial audio communication rooms, interactive 2D virtual office canvas state sync '
                        'via websockets, and screen share pipelines.',
 'outreach_status': 'To Contact',
 'website': 'https://wurkr.uk',
 'work_model_location': 'Fully Remote (India) / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'sourabh@skit.ai',
 'career_page_url': 'https://skit.ai/careers/',
 'company_name': 'Skit.ai',
 'domain_sector': 'Voice AI Automation for Debt Collection & Customer Support',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $23M (WestBridge Capital, Kalaari Capital)',
 'hiring_decision_maker': 'Sourabh Gupta (Co-Founder & CEO)',
 'id': 338,
 'nalin_tech_fit_hook': 'Architecting low-latency duplex spoken dialog systems, telephony SIP trunk audio streamers, '
                        'and multilingual debt resolution negotiation bots.',
 'outreach_status': 'To Contact',
 'website': 'https://skit.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'subhabrata@questlabs.ai',
 'career_page_url': 'https://www.questlabs.ai',
 'company_name': 'Quest Labs',
 'domain_sector': 'AI Growth & User Onboarding SDKs for Mobile and Web Apps',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.5M (Y Combinator W24)',
 'hiring_decision_maker': 'Subhabrata Choudhury (Founder & CEO)',
 'id': 339,
 'nalin_tech_fit_hook': 'Building embeddable React/Next.js onboarding quest widgets, user churn prediction models, and '
                        'dynamic product feature guidance components.',
 'outreach_status': 'To Contact',
 'website': 'https://www.questlabs.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'albert@vectorshift.ai',
 'career_page_url': 'https://www.vectorshift.ai/careers',
 'company_name': 'VectorShift',
 'domain_sector': 'AI Workflow Automation & Multi-Agent Builder Platform',
 'employee_count': '12-25',
 'funding_stage_investors': 'Seed $3M (Y Combinator W24, prominent Silicon Valley angels)',
 'hiring_decision_maker': 'Albert Qiu (Co-Founder & CEO)',
 'id': 340,
 'nalin_tech_fit_hook': 'Developing node-based visual drag-and-drop LLM pipeline editors, autonomous agent task '
                        'execution loops, and document ingestion connectors.',
 'outreach_status': 'To Contact',
 'website': 'https://www.vectorshift.ai',
 'work_model_location': 'Fully Remote (India team / Global)'},
    {'career_email': 'sundar@cselect.ai',
 'career_page_url': 'https://cselect.ai',
 'company_name': 'Maya AI',
 'domain_sector': 'Personalization AI for Financial Services & Banks',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $8M (Covalent Fund, prominent institutional funds)',
 'hiring_decision_maker': 'Sundar Madakshira (CEO)',
 'id': 341,
 'nalin_tech_fit_hook': 'Constructing customer banking transactional taste graphs, dynamic credit card merchant offer '
                        'matching, and low-latency API ranking engines.',
 'outreach_status': 'To Contact',
 'website': 'https://cselect.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'konstantina@kaedim3d.com',
 'career_page_url': 'https://www.kaedim3d.com/careers',
 'company_name': 'Kaedim',
 'domain_sector': 'AI 2D to 3D Generation for Games & Virtual Production',
 'employee_count': '20-40',
 'funding_stage_investors': 'Series A $15M (A16Z Games, Pioneer Fund)',
 'hiring_decision_maker': 'Konstantina Psoma (Founder & CEO)',
 'id': 342,
 'nalin_tech_fit_hook': 'Building neural 3D mesh reconstruction pipelines from 2D concept sketches, automated UV '
                        'unwrapping tools, and game engine export plugins.',
 'outreach_status': 'To Contact',
 'website': 'https://www.kaedim3d.com',
 'work_model_location': 'Fully Remote (India team / Global)'},
    {'career_email': 'kyle@openpipe.ai',
 'career_page_url': 'https://openpipe.ai/careers',
 'company_name': 'OpenPipe',
 'domain_sector': 'Fine-Tuning & Model Distillation Platform for Production LLMs',
 'employee_count': '10-20',
 'funding_stage_investors': 'Seed $6.7M (Costanoa Ventures, Y Combinator)',
 'hiring_decision_maker': 'Kyle Corbitt (Co-Founder & CEO)',
 'id': 343,
 'nalin_tech_fit_hook': 'Developing automated LLM prompt-response capture SDKs, synthetic dataset filtering pipelines, '
                        'and Llama 3 model distillation benchmarking.',
 'outreach_status': 'To Contact',
 'website': 'https://openpipe.ai',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'steven@dub.co',
 'career_page_url': 'https://dub.co/careers',
 'company_name': 'Dub.co',
 'domain_sector': 'Open Source Link Infrastructure & Analytics for Modern Web',
 'employee_count': '10-20',
 'funding_stage_investors': 'Seed $2M (Open core investors, prominent developer angels)',
 'hiring_decision_maker': 'Steven Tey (Founder & CEO)',
 'id': 344,
 'nalin_tech_fit_hook': 'Building edge link redirection handlers on Next.js / Cloudflare Workers, real-time click '
                        'analytics ingestion, and geo-targeted smart links.',
 'outreach_status': 'To Contact',
 'website': 'https://dub.co',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'prashant@leegality.com',
 'career_page_url': 'https://www.leegality.com/careers',
 'company_name': 'Leegality',
 'domain_sector': 'Document Infrastructure & AI Compliance for Indian Enterprises',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $5M (IIFL, prominent domestic funds)',
 'hiring_decision_maker': 'Prashant Muddu (Co-Founder & CEO)',
 'id': 345,
 'nalin_tech_fit_hook': 'Automating Bharat stamp duty calculations across Indian states, Aadhaar e-sign HSM signing '
                        'queues, and legal document workflow APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://www.leegality.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'satya@bluecopa.com',
 'career_page_url': 'https://bluecopa.com',
 'company_name': 'Bluecopa',
 'domain_sector': 'AI Finance Operations & Intelligent Data Platform for CFOs',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $2.3M (Blume Ventures, Chiratae Ventures)',
 'hiring_decision_maker': 'Satya Prakash (Co-Founder & CEO)',
 'id': 346,
 'nalin_tech_fit_hook': 'Building unified data connectors for ERPs and payment gateways, automated revenue recognition '
                        'models, and conversational finance queries.',
 'outreach_status': 'To Contact',
 'website': 'https://bluecopa.com',
 'work_model_location': 'Remote / Hyderabad / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'brijraj@spryhealth.com',
 'career_page_url': 'https://www.spryhealth.com/careers',
 'company_name': 'Spry',
 'domain_sector': 'AI Physical Therapy Clinic Management OS & RCM Platform',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $7M (Two Culture Capital, Together Fund)',
 'hiring_decision_maker': 'Brijraj Bhuptani (Co-Founder & CEO)',
 'id': 347,
 'nalin_tech_fit_hook': 'Developing physical therapy SOAP note clinical transcription AI, insurance claim revenue '
                        'cycle scrubbers, and patient motion exercise apps.',
 'outreach_status': 'To Contact',
 'website': 'https://www.spryhealth.com',
 'work_model_location': 'Remote / Delhi-NCR / Bangalore'},
    {'career_email': 'gleb@datafold.com',
 'career_page_url': 'https://www.datafold.com/careers',
 'company_name': 'Datafold',
 'domain_sector': 'Automated Data Testing & LLM Data Diffing Infrastructure',
 'employee_count': '20-40',
 'funding_stage_investors': 'Series A $22M (Amplify Partners, Y Combinator)',
 'hiring_decision_maker': 'Gleb Mezhanskiy (Founder & CEO)',
 'id': 348,
 'nalin_tech_fit_hook': 'Building cross-database data diffing algorithms, dbt CI pull request test automation bots, '
                        'and data warehouse lineage graph visualizers.',
 'outreach_status': 'To Contact',
 'website': 'https://www.datafold.com',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'dan@fingerprint.com',
 'career_page_url': 'https://fingerprint.com/careers/',
 'company_name': 'Fingerprint',
 'domain_sector': 'Device Intelligence & Bot Detection AI for Application Security',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series B $32M (Craft Ventures, Nexus Venture Partners)',
 'hiring_decision_maker': 'Dan Pinto (Co-Founder & CEO)',
 'id': 349,
 'nalin_tech_fit_hook': 'Implementing 99.5% accuracy browser visitor fingerprinting signals, client-side entropy '
                        'collectors, and account takeover prevention APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://fingerprint.com',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'nicolas@questdb.com',
 'career_page_url': 'https://questdb.com/careers/',
 'company_name': 'QuestDB',
 'domain_sector': 'High-Performance Time-Series Database for AI & Market Data',
 'employee_count': '20-40',
 'funding_stage_investors': 'Series A $12M (468 Capital, Nexus VP, Y Combinator)',
 'hiring_decision_maker': 'Nicolas Hourcard (Co-Founder & CEO)',
 'id': 350,
 'nalin_tech_fit_hook': 'Building zero-GC high-frequency time-series SQL query engines, real-time market data '
                        'ingestion pipelines, and Grafana dashboard telemetry plugins.',
 'outreach_status': 'To Contact',
 'website': 'https://questdb.com',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'brian@unstructured.io',
 'career_page_url': 'https://unstructured.io/careers',
 'company_name': 'Unstructured.io',
 'domain_sector': 'ETL & Preprocessing for Enterprise LLM Data and Documents',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series B $40M (Menlo Ventures, Databricks Ventures)',
 'hiring_decision_maker': 'Brian Raymond (Founder & CEO)',
 'id': 351,
 'nalin_tech_fit_hook': 'Building multi-modal document chunking pipelines, layout-aware PDF table OCR parsing engines, '
                        'and vector database ingestion connectors.',
 'outreach_status': 'To Contact',
 'website': 'https://unstructured.io',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'jerry@llamaindex.ai',
 'career_page_url': 'https://www.llamaindex.ai/careers',
 'company_name': 'LlamaIndex',
 'domain_sector': 'Data Framework for LLM Context Augmentation & RAG Systems',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $8.5M (Greylock Partners, prominent AI angels)',
 'hiring_decision_maker': 'Jerry Liu (Co-Founder & CEO)',
 'id': 352,
 'nalin_tech_fit_hook': 'Constructing hierarchical document index structures, multi-modal query engines, and agentic '
                        'tool-calling workflows in Python/TypeScript.',
 'outreach_status': 'To Contact',
 'website': 'https://www.llamaindex.ai',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'tuhin@baseten.co',
 'career_page_url': 'https://www.baseten.co/careers',
 'company_name': 'Baseten',
 'domain_sector': 'Serverless ML Model Inference & High-Performance Serving',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series B $40M (IVP, Spark Capital)',
 'hiring_decision_maker': 'Tuhin Srivastava (Co-Founder & CEO)',
 'id': 353,
 'nalin_tech_fit_hook': 'Optimizing open-source LLM container cold-start latencies with Truss, streaming inference '
                        'chunking, and multi-GPU tensor parallelism.',
 'outreach_status': 'To Contact',
 'website': 'https://www.baseten.co',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'erik@modal.com',
 'career_page_url': 'https://modal.com/careers',
 'company_name': 'Modal Labs',
 'domain_sector': 'Serverless Cloud Compute for AI & Python Data Teams',
 'employee_count': '20-40',
 'funding_stage_investors': 'Series A $16M (Redpoint Ventures, Amplify Partners)',
 'hiring_decision_maker': 'Erik Bernhardsson (Founder & CEO)',
 'id': 354,
 'nalin_tech_fit_hook': 'Building sub-second Python container initialization runtimes, distributed batch jobs '
                        'orchestration, and serverless GPU queue managers.',
 'outreach_status': 'To Contact',
 'website': 'https://modal.com',
 'work_model_location': 'Fully Remote (India / Global)'},
    {'career_email': 'joao@crewai.com',
 'career_page_url': 'https://www.crewai.com/careers',
 'company_name': 'CrewAI',
 'domain_sector': 'Multi-Agent Automation Framework & Collaborative AI Teams',
 'employee_count': '10-25',
 'funding_stage_investors': 'Seed $2.5M (Prominent open-source & AI angels)',
 'hiring_decision_maker': 'Joao Moura (Founder & CEO)',
 'id': 355,
 'nalin_tech_fit_hook': 'Developing role-based multi-agent collaboration protocols, task delegation state machines, '
                        'and Next.js live telemetry monitoring consoles.',
 'outreach_status': 'To Contact',
 'website': 'https://www.crewai.com',
 'work_model_location': 'Fully Remote (India / Global)'},
]
