# Batch 5: Companies 205 to 255 (EV Mobility, CleanTech, IoT & Robotics AI)

BATCH_5 = [
    {'career_email': 'arun@exponent.energy',
 'career_page_url': 'https://exponent.energy/careers',
 'company_name': 'Exponent Energy',
 'domain_sector': '15-Minute Rapid Charging Battery Pack & Station Network',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $26M (Lightspeed, Eight Roads)',
 'hiring_decision_maker': 'Arun Vinayak (Co-Founder & CEO)',
 'id': 205,
 'nalin_tech_fit_hook': 'Battery telemetry data ingestion, fast charging current-voltage profiling algorithms, and '
                        'station management dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://exponent.energy',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR'},
    {'career_email': 'suhas@simpleenergy.in',
 'career_page_url': 'https://simpleenergy.in/careers',
 'company_name': 'Simple Energy',
 'domain_sector': 'Smart Electric Two-Wheelers & Battery R&D Platform',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $20M (Prominent high-net-worth syndicates)',
 'hiring_decision_maker': 'Suhas Rajkumar (Founder & CEO)',
 'id': 206,
 'nalin_tech_fit_hook': 'Connected scooter touchscreen OS in Android/React, OTA vehicle telemetry sync, and thermal '
                        'performance predictive models.',
 'outreach_status': 'To Contact',
 'website': 'https://simpleenergy.in',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'hemanth@turno.club',
 'career_page_url': 'https://turno.club/careers',
 'company_name': 'Turno',
 'domain_sector': 'Commercial Electric Vehicle Distribution & Battery Life AI',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $13.8M (B Capital, Quona Capital)',
 'hiring_decision_maker': 'Hemanth Dholakia (Co-Founder & CEO)',
 'id': 207,
 'nalin_tech_fit_hook': 'Commercial vehicle battery health estimation models, financing repayment risk scoring, and '
                        'customer vehicle portals in Next.js.',
 'outreach_status': 'To Contact',
 'website': 'https://turno.club',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR'},
    {'career_email': 'akash@cleanelectric.in',
 'career_page_url': 'https://cleanelectric.in/careers',
 'company_name': 'Clean Electric',
 'domain_sector': 'Fast-Charging Liquid-Cooled EV Battery Packs & BMS',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $2.2M (Info Edge Ventures, Kalaari)',
 'hiring_decision_maker': 'Akash Gupta (Co-Founder & CEO)',
 'id': 208,
 'nalin_tech_fit_hook': 'Direct contact liquid cooling battery telemetry, cellular IoT tracking, and cell degradation '
                        'prediction pipelines in Python.',
 'outreach_status': 'To Contact',
 'website': 'https://cleanelectric.in',
 'work_model_location': 'Remote / Pune / Delhi-NCR'},
    {'career_email': 'mohal@matter.in',
 'career_page_url': 'https://matter.in/careers',
 'company_name': 'Matter Energy',
 'domain_sector': 'Electric Motorbikes with Integrated Liquid Cooling',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $35M (Capital A, prominent investors)',
 'hiring_decision_maker': 'Mohal Lalbhai (Founder & CEO)',
 'id': 209,
 'nalin_tech_fit_hook': 'Manual gearbox electric vehicle telematics, connected instrument cluster Android apps, and '
                        'riding efficiency analytics.',
 'outreach_status': 'To Contact',
 'website': 'https://matter.in',
 'work_model_location': 'Remote / Ahmedabad / Delhi-NCR'},
    {'career_email': 'awais@pixxel.space',
 'career_page_url': 'https://pixxel.space/careers',
 'company_name': 'Pixxel',
 'domain_sector': 'Hyperspectral Imaging Satellites & Earth Observation AI',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $36M (Google, Lightspeed, Radical)',
 'hiring_decision_maker': 'Awais Ahmed (Co-Founder & CEO) & Kshitij Khandelwal (Co-Founder)',
 'id': 210,
 'nalin_tech_fit_hook': 'Satellite hyperspectral image processing pipelines, deep learning for mineral/crop health '
                        'detection, and geospatial APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://pixxel.space',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'srinath@agnikul.in',
 'career_page_url': 'https://agnikul.in/careers',
 'company_name': 'Agnikul Cosmos',
 'domain_sector': '3D-Printed Semi-Cryogenic Rocket Launch Vehicles',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series B $26M (Celesta Capital, Rocketship.vc)',
 'hiring_decision_maker': 'Srinath Ravichandran (Co-Founder & CEO)',
 'id': 211,
 'nalin_tech_fit_hook': 'Rocket telemetry parsing, automated launch test telemetry dashboards in Next.js, and '
                        'trajectory simulation software.',
 'outreach_status': 'To Contact',
 'website': 'https://agnikul.in',
 'work_model_location': 'Remote / Chennai'},
    {'career_email': 'suyash@galaxeye.space',
 'career_page_url': 'https://galaxeye.space/careers',
 'company_name': 'GalaxEye Space',
 'domain_sector': 'Multi-Sensor SAR & Optical Earth Observation Satellites',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $3.5M (Speciale Invest, Drone Federation)',
 'hiring_decision_maker': 'Suyash Singh (Co-Founder & CEO)',
 'id': 212,
 'nalin_tech_fit_hook': 'Synthetic Aperture Radar (SAR) data fusion with optical satellite imagery, cloud-penetrating '
                        'change detection models.',
 'outreach_status': 'To Contact',
 'website': 'https://galaxeye.space',
 'work_model_location': 'Remote / Chennai / Bangalore'},
    {'career_email': 'pramod@unboxrobotics.com',
 'career_page_url': 'https://unboxrobotics.com/careers',
 'company_name': 'Unbox Robotics',
 'domain_sector': 'Swarm Robotics & Autonomous Sorting for Logistics',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $7M (3one4 Capital, SOSV)',
 'hiring_decision_maker': 'Pramod Ghadge (Co-Founder & CEO)',
 'id': 213,
 'nalin_tech_fit_hook': 'Multi-robot swarm coordination path planning, warehouse conveyor fleet simulation, and '
                        'low-latency ROS controller bridges.',
 'outreach_status': 'To Contact',
 'website': 'https://unboxrobotics.com',
 'work_model_location': 'Remote / Pune / Bangalore'},
    {'career_email': 'daniel@detecttechnologies.com',
 'career_page_url': 'https://detecttechnologies.com/careers',
 'company_name': 'Detect Technologies',
 'domain_sector': 'Industrial AI Computer Vision for Workplace Safety & Assets',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $28M (Prosus Ventures, Accel)',
 'hiring_decision_maker': 'Daniel Raj David (Co-Founder & CEO)',
 'id': 214,
 'nalin_tech_fit_hook': 'Computer vision pipeline for PPE non-compliance detection in refineries, ultrasonic sensor '
                        'IoT telemetry, and industrial safety alerts.',
 'outreach_status': 'To Contact',
 'website': 'https://detecttechnologies.com',
 'work_model_location': 'Remote / Chennai / Delhi-NCR'},
    {'career_email': 'harshit@intugine.com',
 'career_page_url': 'https://intugine.com/careers',
 'company_name': 'Intugine Technologies',
 'domain_sector': 'Multimodal Real-Time Supply Chain Visibility & IoT',
 'employee_count': '45-75',
 'funding_stage_investors': 'Pre-Series A $2.5M (M12 - Microsoft Ventures)',
 'hiring_decision_maker': 'Harshit Shrivastava (Founder & CEO)',
 'id': 215,
 'nalin_tech_fit_hook': 'GPS and SIM-based location tracking APIs, shipment arrival delay prediction models, and '
                        'supply chain control tower UIs in Next.js.',
 'outreach_status': 'To Contact',
 'website': 'https://intugine.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ranjith@stellapps.com',
 'career_page_url': 'https://stellapps.com/careers',
 'company_name': 'Stellapps Technologies',
 'domain_sector': 'Dairy Supply Chain Digitization, Smart IoT & Cattle Wearables',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $18M (Celesta Capital, Omnivore)',
 'hiring_decision_maker': 'Ranjith Mukundan (Founder & CEO)',
 'id': 216,
 'nalin_tech_fit_hook': 'Milk quality testing sensor data processing, cattle health wearable telemetry, and village '
                        'procurement center sync.',
 'outreach_status': 'To Contact',
 'website': 'https://stellapps.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'sameer@charzer.com',
 'career_page_url': 'https://charzer.com/careers',
 'company_name': 'Charzer',
 'domain_sector': 'EV Charging Station Network & Smart IoT Charger OS',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $3M (Indian angel networks)',
 'hiring_decision_maker': 'Sameer Ranjan Jaiswal (Co-Founder)',
 'id': 217,
 'nalin_tech_fit_hook': 'OCPP protocol charging station management software, driver mobile app charging reservation, '
                        'and energy metering backends.',
 'outreach_status': 'To Contact',
 'website': 'https://charzer.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'akshay@kazam.energy',
 'career_page_url': 'https://kazam.energy/careers',
 'company_name': 'Kazam',
 'domain_sector': 'EV Charging Software Platform & Grid Management',
 'employee_count': '35-60',
 'funding_stage_investors': 'Series A $5M (Vertex Ventures, Avaana Capital)',
 'hiring_decision_maker': 'Akshay Shekhar (Co-Founder & CEO)',
 'id': 218,
 'nalin_tech_fit_hook': 'Smart EV charger hardware connectivity, dynamic tariff billing microservices, and fleet '
                        'charging schedule optimization algorithms.',
 'outreach_status': 'To Contact',
 'website': 'https://kazam.energy',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'visakh@fynmobility.com',
 'career_page_url': 'https://fynmobility.com/careers',
 'company_name': 'Fyn Mobility',
 'domain_sector': 'EV Fleet as a Service for E-Commerce Logistics',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $2M (Prominent mobility investors)',
 'hiring_decision_maker': 'Visakh Sasikumar (Founder & CEO)',
 'id': 219,
 'nalin_tech_fit_hook': 'Electric delivery vehicle telematics, battery swap station reservation matching, and '
                        'logistics SLA monitoring portals.',
 'outreach_status': 'To Contact',
 'website': 'https://fynmobility.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'pulkit@sprih.net',
 'career_page_url': 'https://sprih.net/careers',
 'company_name': 'Sprih',
 'domain_sector': 'Climate Tech & AI Carbon Emission Accounting Platform',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $2.9M (Leo Capital)',
 'hiring_decision_maker': 'Pulkit Agarwal (Founder & CEO)',
 'id': 220,
 'nalin_tech_fit_hook': 'Automated Scope 1, 2, and 3 carbon emissions data extraction from corporate ERPs, carbon '
                        'offset tracking, and ESG dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://sprih.net',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'jagadish@uptimeai.com',
 'career_page_url': 'https://uptimeai.com/careers',
 'company_name': 'UptimeAI',
 'domain_sector': 'AI Virtual Engineer for Heavy Industrial Predictive Maintenance',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $3.5M (Emergent Ventures)',
 'hiring_decision_maker': 'Jagadish Gattu (Founder & CEO)',
 'id': 221,
 'nalin_tech_fit_hook': 'Industrial plant sensor time-series anomaly detection, equipment degradation root cause '
                        'reasoning, and interactive plant schematics.',
 'outreach_status': 'To Contact',
 'website': 'https://uptimeai.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'anirudh@digantara.com',
 'career_page_url': 'https://digantara.com/careers',
 'company_name': 'Digantara',
 'domain_sector': 'Space Situational Awareness & Orbital Space Debris Tracking',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $12M (Peak XV Partners, Aditya Birla)',
 'hiring_decision_maker': 'Anirudh Sharma (Co-Founder & CEO)',
 'id': 222,
 'nalin_tech_fit_hook': 'Orbital mechanics collision avoidance algorithms, satellite sensor telemetry ingest, and '
                        'interactive 3D celestial tracking consoles.',
 'outreach_status': 'To Contact',
 'website': 'https://digantara.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'pratham@headfone.co.in',
 'career_page_url': 'https://headfone.co.in/careers',
 'company_name': 'Headfone',
 'domain_sector': 'Vernacular Audio Content Platform & Personalized Audio AI',
 'employee_count': '40-70',
 'funding_stage_investors': 'Series B $10M (Elevation Capital, Hashed)',
 'hiring_decision_maker': 'Pratham Khandelwal (Co-Founder & CEO)',
 'id': 223,
 'nalin_tech_fit_hook': 'Audio recommendation algorithms based on listening habits, automated speech loudness '
                        'leveling, and creator studio apps in React.',
 'outreach_status': 'To Contact',
 'website': 'https://headfone.co.in',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'shyam@zevi.ai',
 'career_page_url': 'https://zevi.ai/careers',
 'company_name': 'Zevi.ai',
 'domain_sector': 'AI-Powered Site Search & Neural Discovery for E-Commerce',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.6M (Together Fund, Better Capital)',
 'hiring_decision_maker': 'Shyam Sunder (Co-Founder & CEO)',
 'id': 224,
 'nalin_tech_fit_hook': 'NLP search query intent classification, real-time product embedding ranking, and '
                        'Shopify/Magento search integration SDKs.',
 'outreach_status': 'To Contact',
 'website': 'https://zevi.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'shailendra@fasal.co',
 'career_page_url': 'https://fasal.co/careers',
 'company_name': 'Fasal',
 'domain_sector': 'Precision Horticulture AI & IoT Micro-Climate Sensors',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $12M (TDK Ventures, British International)',
 'hiring_decision_maker': 'Shailendra Tiwari (Co-Founder & CEO)',
 'id': 225,
 'nalin_tech_fit_hook': 'Soil and canopy micro-climate sensor data telemetry, disease outbreak predictive models, and '
                        'precision irrigation alert engines.',
 'outreach_status': 'To Contact',
 'website': 'https://fasal.co',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'siddharth@bharatagri.com',
 'career_page_url': 'https://bharatagri.com/careers',
 'company_name': 'BharatAgri',
 'domain_sector': 'Algorithmic Crop Advisory & Smart Farming System',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $4.3M (Omnivore, India Quotient)',
 'hiring_decision_maker': 'Siddharth Dialani (Co-Founder & CEO)',
 'id': 226,
 'nalin_tech_fit_hook': 'Personalized crop calendar generation algorithms based on satellite soil and weather data, '
                        'and vernacular voice advisory apps.',
 'outreach_status': 'To Contact',
 'website': 'https://bharatagri.com',
 'work_model_location': 'Remote / Pune / Bangalore'},
    {'career_email': 'taranjeet@agnext.com',
 'career_page_url': 'https://agnext.com/careers',
 'company_name': 'AgNext Technologies',
 'domain_sector': 'DeepTech AI Food Quality Assessment & Spectroscopy',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series A $21M (Alpha Wave Global, Omnivore)',
 'hiring_decision_maker': 'Taranjeet Singh Bhamra (Founder & CEO)',
 'id': 227,
 'nalin_tech_fit_hook': 'Near-infrared spectroscopy data modeling, instant crop chemical constituent estimation, and '
                        'food supply chain quality cloud.',
 'outreach_status': 'To Contact',
 'website': 'https://agnext.com',
 'work_model_location': 'Remote / Chandigarh / Delhi-NCR'},
    {'career_email': 'vivek@aibono.com',
 'career_page_url': 'https://aibono.com/careers',
 'company_name': 'Aibono',
 'domain_sector': 'AI-Powered Fresh Produce AgTech & Demand Aggregation',
 'employee_count': '40-70',
 'funding_stage_investors': 'Seed $3.5M (Mitsui & Co., Rebright Partners)',
 'hiring_decision_maker': 'Vivek Rajkumar (Founder & CEO)',
 'id': 228,
 'nalin_tech_fit_hook': 'Farm yield harvesting schedules, retail store perishable demand aggregation models, and '
                        'cold-chain route optimization.',
 'outreach_status': 'To Contact',
 'website': 'https://aibono.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'kishor@ergos.in',
 'career_page_url': 'https://ergos.in/careers',
 'company_name': 'Ergos',
 'domain_sector': 'Grain-Bank Agri FinTech & Digital Farm Gate Warehousing',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $10M (Aavishkaar Capital)',
 'hiring_decision_maker': 'Kishor Jha (Founder & CEO)',
 'id': 229,
 'nalin_tech_fit_hook': 'Digitized warehouse receipt ledger, post-harvest grain quality certification, and digital '
                        'bank loan disbursement pipelines.',
 'outreach_status': 'To Contact',
 'website': 'https://ergos.in',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'tauseef@gramophone.in',
 'career_page_url': 'https://gramophone.in/careers',
 'company_name': 'Gramophone',
 'domain_sector': 'Full-Stack Agritech Advisory, Input Marketplace & AI Diagnostics',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series B $10M (Z3Partners, Info Edge)',
 'hiring_decision_maker': 'Tauseef Khan (Co-Founder & CEO)',
 'id': 230,
 'nalin_tech_fit_hook': 'Crop disease photo diagnosis using computer vision on mobile devices, localized agronomic '
                        'recommendations, and commerce checkout.',
 'outreach_status': 'To Contact',
 'website': 'https://gramophone.in',
 'work_model_location': 'Remote / Indore / Delhi-NCR'},
    {'career_email': 'milan@intellolabs.com',
 'career_page_url': 'https://www.intellolabs.com/careers',
 'company_name': 'Intello Labs',
 'domain_sector': 'Computer Vision & Deep Learning Quality Testing for Agri-Food',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $5.9M (Saama Capital, Omnivore)',
 'hiring_decision_maker': 'Milan Sharma (Co-Founder & CEO)',
 'id': 231,
 'nalin_tech_fit_hook': 'Edge computer vision pipelines, multi-spectral image preprocessing, and FastAPI microservices '
                        'for agricultural grading.',
 'outreach_status': 'To Contact',
 'website': 'https://www.intellolabs.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'neeraj@superk.in',
 'career_page_url': 'https://superk.in/careers',
 'company_name': 'SuperK',
 'domain_sector': 'Tech-Enabled Franchised Grocery Chain for Tier-3/4 Towns',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $5.5M (Blume Ventures, Silverneedle)',
 'hiring_decision_maker': 'Neeraj Menta (Co-Founder & CEO)',
 'id': 232,
 'nalin_tech_fit_hook': 'Store level inventory replenishment algorithms, franchise billing POS software, and regional '
                        'warehouse dispatch routing.',
 'outreach_status': 'To Contact',
 'website': 'https://superk.in',
 'work_model_location': 'Remote / Hyderabad'},
    {'career_email': 'shrikant@getknit.dev',
 'career_page_url': 'https://getknit.dev/careers',
 'company_name': 'Knit',
 'domain_sector': 'Unified API Integration Platform for SaaS Applications',
 'employee_count': '12-25',
 'funding_stage_investors': 'Seed $1M (Endiya Partners)',
 'hiring_decision_maker': 'Shrikant Shenoy (Co-Founder & CEO)',
 'id': 233,
 'nalin_tech_fit_hook': 'Building universal schema abstractions for HRIS and CRM platforms, webhook event dispatching, '
                        'and rate-limited API proxies.',
 'outreach_status': 'To Contact',
 'website': 'https://getknit.dev',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ashish@convin.ai',
 'career_page_url': 'https://convin.ai/careers',
 'company_name': 'Convin.ai',
 'domain_sector': 'AI Conversation Intelligence & Real-Time Agent Assistance',
 'employee_count': '40-70',
 'funding_stage_investors': 'Series A $6.5M (Kalaari Capital, Titan Capital)',
 'hiring_decision_maker': 'Ashish Santhalia (Co-Founder & CEO)',
 'id': 234,
 'nalin_tech_fit_hook': 'Real-time speech-to-text audio streaming, whisper latency tuning, and agent co-pilot RAG '
                        'systems in Next.js/FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://convin.ai',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'nayrhit@gushwork.ai',
 'career_page_url': 'https://www.gushwork.ai/careers',
 'company_name': 'Gushwork.ai',
 'domain_sector': 'AI Operational Workforce & Autonomous Process Automation',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $2.1M (Lightspeed India, B Capital)',
 'hiring_decision_maker': 'Nayrhit Bhattacharya (Co-Founder & CEO)',
 'id': 235,
 'nalin_tech_fit_hook': 'Building multi-agent task execution graphs, browser orchestration agents, and '
                        'human-in-the-loop validation dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://www.gushwork.ai',
 'work_model_location': 'Delhi-NCR (Noida/Delhi) / Remote'},
    {'career_email': 'suhash@gan.ai',
 'career_page_url': 'https://gan.ai/careers',
 'company_name': 'Gan.ai',
 'domain_sector': 'Generative AI Video Personalization at Scale',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $5.2M (Peak XV Surge, Emergent Ventures)',
 'hiring_decision_maker': 'Suhash Patel (Founder & CEO)',
 'id': 236,
 'nalin_tech_fit_hook': 'Generative video diffusion pipelines, neural audio lip-sync synchronization, and distributed '
                        'rendering microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://gan.ai',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Remote'},
    {'career_email': 'gaurav@verloop.io',
 'career_page_url': 'https://verloop.io/careers',
 'company_name': 'Verloop.io',
 'domain_sector': 'Customer Support Automation & Multilingual Conversational AI',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $5M (Alpha Wave, IDFC Parampara)',
 'hiring_decision_maker': 'Gaurav Singh (Founder & CEO)',
 'id': 237,
 'nalin_tech_fit_hook': 'Machine learning intent recognition models, live agent transfer queues, and real-time chat '
                        'socket infrastructure.',
 'outreach_status': 'To Contact',
 'website': 'https://verloop.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'jack@cognizer.ai',
 'career_page_url': 'https://cognizer.ai/careers',
 'company_name': 'Cognizer',
 'domain_sector': 'Genius Brain AI & Corporate Unstructured Content Intelligence',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $5M (Indian angel syndicates)',
 'hiring_decision_maker': 'Jack Donenfeld (Co-Founder)',
 'id': 238,
 'nalin_tech_fit_hook': 'Natural language query parsers over corporate legal and financial archives, graph neural '
                        'networks, and semantic retrieval.',
 'outreach_status': 'To Contact',
 'website': 'https://cognizer.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR'},
    {'career_email': 'shridhar@senseforth.ai',
 'career_page_url': 'https://senseforth.ai/careers',
 'company_name': 'Senseforth.ai',
 'domain_sector': 'Conversational AI Bots & Enterprise Cognitive Virtual Assistants',
 'employee_count': '40-70',
 'funding_stage_investors': 'Pre-Series A $2M (Indian angel syndicates)',
 'hiring_decision_maker': 'Shridhar Marri (Co-Founder & CEO)',
 'id': 239,
 'nalin_tech_fit_hook': 'Pre-built banking conversational flows, automated query disambiguation, and enterprise '
                        'customer service analytics dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://senseforth.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'alok@drivetrain.ai',
 'career_page_url': 'https://drivetrain.ai/careers',
 'company_name': 'Drivetrain.ai',
 'domain_sector': 'Strategic Financial Planning & Enterprise Modeling SaaS',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $3.2M (Elevation Capital, angel syndicates)',
 'hiring_decision_maker': 'Alok Goel (Co-Founder & CEO)',
 'id': 240,
 'nalin_tech_fit_hook': 'Multi-dimensional financial model formula calculation engines, live ERP/CRM data sync, and '
                        'interactive scenario forecasting.',
 'outreach_status': 'To Contact',
 'website': 'https://drivetrain.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'rohit@segmind.com',
 'career_page_url': 'https://www.segmind.com/careers',
 'company_name': 'Segmind',
 'domain_sector': 'Serverless Generative AI APIs & Diffusion Model Workflows',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1M (Indian angel networks & institutional seed)',
 'hiring_decision_maker': 'Rohit M A (Co-Founder & CEO)',
 'id': 241,
 'nalin_tech_fit_hook': 'Serverless GPU inference routing, diffusion pipeline cold-start reduction, and modular '
                        'workflow builder interfaces.',
 'outreach_status': 'To Contact',
 'website': 'https://www.segmind.com',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'fardad@kudo.ai',
 'career_page_url': 'https://kudo.ai/careers',
 'company_name': 'Kudo.ai',
 'domain_sector': 'Real-Time Multilingual Speech Translation & Meeting Subtitles',
 'employee_count': '40-70',
 'funding_stage_investors': 'Series A $6M (Felicitas Ventures)',
 'hiring_decision_maker': 'Fardad Zabetian (CEO)',
 'id': 242,
 'nalin_tech_fit_hook': 'Low-latency WebRTC live meeting audio streams, real-time machine translation pipelines, and '
                        'speech synthesis voice output.',
 'outreach_status': 'To Contact',
 'website': 'https://kudo.ai',
 'work_model_location': 'Remote / Bangalore / Global'},
    {'career_email': 'dipanjan@kombai.com',
 'career_page_url': 'https://kombai.com/careers',
 'company_name': 'Kombai',
 'domain_sector': 'Generative AI Model That Interprets UI Designs into Code',
 'employee_count': '10-25',
 'funding_stage_investors': 'Seed $4.5M (Stellaris Venture Partners)',
 'hiring_decision_maker': 'Dipanjan Dey (Co-Founder & CEO)',
 'id': 243,
 'nalin_tech_fit_hook': 'Computer vision models that recognize UI components from raw vector nodes, clean HTML/CSS '
                        'generation, and React component code trees.',
 'outreach_status': 'To Contact',
 'website': 'https://kombai.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'aneesh@qritive.com',
 'career_page_url': 'https://qritive.com/careers',
 'company_name': 'Aura ML (Qritive)',
 'domain_sector': 'AI Digital Pathology & Cancer Diagnosis Assistance',
 'employee_count': '20-40',
 'funding_stage_investors': 'Series A $7.5M (MassMutual Ventures)',
 'hiring_decision_maker': 'Aneesh Satnalika (Co-Founder & CEO)',
 'id': 244,
 'nalin_tech_fit_hook': 'Gigapixel whole slide image deep learning segmentation, tumor boundary identification, and '
                        'clinical pathology report automation.',
 'outreach_status': 'To Contact',
 'website': 'https://qritive.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'adarsh@aindra.in',
 'career_page_url': 'https://aindra.in/careers',
 'company_name': 'AIndra Systems',
 'domain_sector': 'Point-of-Care Cervical Cancer Screening & Computer Vision',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.2M (Villgro, Millennium Alliance)',
 'hiring_decision_maker': 'Adarsh Natarajan (Founder & CEO)',
 'id': 245,
 'nalin_tech_fit_hook': 'Automated Pap smear slide cell morphology classifiers, compact microscope camera integration, '
                        'and telepathology consults.',
 'outreach_status': 'To Contact',
 'website': 'https://aindra.in',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ashwin@aikenist.com',
 'career_page_url': 'https://aikenist.com/careers',
 'company_name': 'Aikenist',
 'domain_sector': 'AI-Assisted MRI Acceleration & Radiology Reporting',
 'employee_count': '10-25',
 'funding_stage_investors': 'Seed $500K (Indian angel networks)',
 'hiring_decision_maker': 'Ashwin Kumar (Founder & CEO)',
 'id': 246,
 'nalin_tech_fit_hook': 'K-space MRI reconstruction deep learning algorithms, scan time reduction pipelines, and '
                        'automated lesion volumetric metrics.',
 'outreach_status': 'To Contact',
 'website': 'https://aikenist.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'mudit@dozee.io',
 'career_page_url': 'https://dozee.io/careers',
 'company_name': 'Dozee',
 'domain_sector': 'Contactless AI Early Warning & Remote Patient Monitoring',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $6M (State Bank of India, Gokul Rajaram)',
 'hiring_decision_maker': 'Mudit Dandwate (Co-Founder & CEO)',
 'id': 247,
 'nalin_tech_fit_hook': 'Ballistocardiography sensor signal processing, continuous heart/respiration rate extraction, '
                        'and ICU early warning score engines.',
 'outreach_status': 'To Contact',
 'website': 'https://dozee.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'kalyan@5cnetwork.com',
 'career_page_url': 'https://5cnetwork.com/careers',
 'company_name': '5C Network',
 'domain_sector': 'Cloud Radiology Network & Diagnostic Triage AI',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $4.6M (Celesta Capital, Unitus)',
 'hiring_decision_maker': 'Kalyan Sivasailam (Co-Founder & CEO)',
 'id': 248,
 'nalin_tech_fit_hook': 'DICOM medical image cloud transmission protocols, automated radiologist routing algorithms, '
                        'and diagnostic turnaround telemetry.',
 'outreach_status': 'To Contact',
 'website': 'https://5cnetwork.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'amit@deeptek.ai',
 'career_page_url': 'https://deeptek.ai/careers',
 'company_name': 'DeepTek.ai',
 'domain_sector': 'Medical Imaging AI & Automated Radiology Reporting',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $3M (TATA Capital Healthcare Fund)',
 'hiring_decision_maker': 'Dr. Amit Kharat (Co-Founder & CEO)',
 'id': 249,
 'nalin_tech_fit_hook': 'Chest X-ray pulmonary pathology classification, CT scan brain hemorrhage detection, and '
                        'automated radiology findings drafts.',
 'outreach_status': 'To Contact',
 'website': 'https://deeptek.ai',
 'work_model_location': 'Remote / Pune / Bangalore'},
    {'career_email': 'meenakshi@synapsica.com',
 'career_page_url': 'https://synapsica.com/careers',
 'company_name': 'Synapsica Healthcare',
 'domain_sector': 'AI Spine & Musculoskeletal Radiology Triage',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $4.2M (Y Combinator, IvyCap Ventures)',
 'hiring_decision_maker': 'Dr. Meenakshi Singh (Co-Founder & CEO)',
 'id': 250,
 'nalin_tech_fit_hook': 'Spine vertebrae and disc degeneration automated measurement algorithms, vertebral listhesis '
                        'detection, and PACS web viewer.',
 'outreach_status': 'To Contact',
 'website': 'https://synapsica.com',
 'work_model_location': 'Remote / New Delhi / Bangalore'},
    {'career_email': 'geetha@niramai.com',
 'career_page_url': 'https://niramai.com/careers',
 'company_name': 'Niramai',
 'domain_sector': 'Thermalytix Non-Invasive AI Breast Cancer Screening',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $6M (Dream Incubator, Beenext, Ankur)',
 'hiring_decision_maker': 'Dr. Geetha Manjunath (Founder & CEO)',
 'id': 251,
 'nalin_tech_fit_hook': 'High-resolution thermal imaging pattern analysis, automated vascular asymmetry detection, and '
                        'portable diagnostic kit sync.',
 'outreach_status': 'To Contact',
 'website': 'https://niramai.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ramakant@wysa.io',
 'career_page_url': 'https://wysa.io/careers',
 'company_name': 'Wysa',
 'domain_sector': 'AI Conversational Mental Health & Cognitive Therapy Bot',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $20M (HealthQuad, British International)',
 'hiring_decision_maker': 'Ramakant Vempati (Co-Founder & CEO)',
 'id': 252,
 'nalin_tech_fit_hook': 'Evidence-based cognitive behavioral therapy dialogue flows, clinical crisis detection '
                        'heuristics, and privacy-first user state encryption.',
 'outreach_status': 'To Contact',
 'website': 'https://wysa.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'laina@brainsightai.com',
 'career_page_url': 'https://brainsightai.com/careers',
 'company_name': 'BrainSightAI',
 'domain_sector': 'AI Neuroimaging & Whole-Brain Connectome Diagnostics',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.2M (Indian Angel Network, Stanford)',
 'hiring_decision_maker': 'Laina Emmanuel (Co-Founder & CEO)',
 'id': 253,
 'nalin_tech_fit_hook': 'Functional MRI brain functional connectivity graphs, neuro-oncology pre-surgical planning 3D '
                        'rendering, and psychiatric biomarkers.',
 'outreach_status': 'To Contact',
 'website': 'https://brainsightai.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'srikrishna@prediblehealth.com',
 'career_page_url': 'https://prediblehealth.com/careers',
 'company_name': 'Predible Health',
 'domain_sector': 'AI Deep Learning for Pulmonary & Thoracic Radiology',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1M (Indian angel syndicates)',
 'hiring_decision_maker': 'Srikrishna Ramamoorthy (Co-Founder)',
 'id': 254,
 'nalin_tech_fit_hook': 'Lung nodule detection and volumetric growth tracking over sequential CT scans, COPD airway '
                        'quantification, and cloud viewer.',
 'outreach_status': 'To Contact',
 'website': 'https://prediblehealth.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'prabhdeep@red.health',
 'career_page_url': 'https://red.health/careers',
 'company_name': 'Stanplus (Red.Health)',
 'domain_sector': 'Emergency Medical Dispatch AI & Ambulance Fleet Network',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series A $20M (HealthQuad)',
 'hiring_decision_maker': 'Prabhdeep Singh (Founder & CEO)',
 'id': 255,
 'nalin_tech_fit_hook': 'Sub-15 minute emergency response dispatch algorithms, live hospital bed occupancy sync, and '
                        'paramedic telemetry integration.',
 'outreach_status': 'To Contact',
 'website': 'https://red.health',
 'work_model_location': 'Remote / Hyderabad / Delhi-NCR'},
]
