# Batch 4: Companies 154 to 204 (FinTech AI, WealthTech, InsurTech, Corporate Finance & High-Growth SaaS)

BATCH_4 = [
    {
        "id": 154,
        "company_name": "Decentro",
        "website": "https://decentro.tech",
        "domain_sector": "Real-Time Banking & KYC Verification API Platform",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $4.7M (Y Combinator, Rapyd Ventures)",
        "work_model_location": "Remote / Delhi-NCR / Bangalore",
        "career_page_url": "https://decentro.tech/careers",
        "career_email": "rohit@decentro.tech",
        "hiring_decision_maker": "Rohit Taneja (Founder & CEO) & Pratik Daudkhane (Co-Founder)",
        "nalin_tech_fit_hook": "Developer API portals in Next.js + automated KYC document verification pipelines using computer vision and LLMs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 155,
        "company_name": "Peblo (FinBox)",
        "website": "https://finbox.in",
        "domain_sector": "Embedded Credit Infrastructure & Risk Intelligence AI",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $6M (Arali Ventures, Flipkart)",
        "work_model_location": "Remote / Gurgaon / Bangalore",
        "career_page_url": "https://finbox.in/careers",
        "career_email": "rajat@finbox.in",
        "hiring_decision_maker": "Rajat Deshpande (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Device telematics credit scoring models, alternate data underwriting pipelines, and embedded loan journey SDKs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 156,
        "company_name": "Jar",
        "website": "https://myjar.app",
        "domain_sector": "Automated Micro-Savings & Digital Gold Investment Platform",
        "employee_count": "65-95",
        "funding_stage_investors": "Series B $22M (Tiger Global, Rocketship.vc)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://myjar.app/careers",
        "career_email": "nishchay@myjar.app",
        "hiring_decision_maker": "Nishchay AG (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "UPI autopay round-up execution microservices, gamified savings streak algorithms, and high-concurrency transaction ledgers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 157,
        "company_name": "Kodo",
        "website": "https://kodo.com",
        "domain_sector": "Corporate Cards & Automated Spend Management for Startups",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $8.7M (Brex, Y Combinator)",
        "work_model_location": "Remote / Mumbai / Bangalore",
        "career_page_url": "https://kodo.com/careers",
        "career_email": "deekshith@kodo.com",
        "hiring_decision_maker": "Deekshith Podduturi (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Card issuance rails on bank networks, automated corporate expense categorization, and multi-user spend control dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 158,
        "company_name": "Karbon Card",
        "website": "https://karboncard.com",
        "domain_sector": "Corporate Credit Cards & Automated Payouts for Startups",
        "employee_count": "45-75",
        "funding_stage_investors": "Series A $15M (Olive Tree Capital, Harmony)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://karboncard.com/careers",
        "career_email": "kartik@karboncard.com",
        "hiring_decision_maker": "Kartik Jain (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Startup underwriting algorithms using live bank balance scraping, automated payroll disbursements, and payment reconciliation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 159,
        "company_name": "Ditto Insurance",
        "website": "https://joinditto.in",
        "domain_sector": "Plain-English Health & Term Insurance Advisory",
        "employee_count": "60-90",
        "funding_stage_investors": "Seed $4.5M (Zerodha, Finshots)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://joinditto.in/careers",
        "career_email": "shrehith@joinditto.in",
        "hiring_decision_maker": "Shrehith Karkera (Co-Founder) & Pawan Kumar Rai (Co-Founder)",
        "nalin_tech_fit_hook": "Algorithmic policy comparison engines, insurance clause summarization models, and spam-free consultation booking systems.",
        "outreach_status": "To Contact"
    },
    {
        "id": 160,
        "company_name": "Plum Benefits",
        "website": "https://plumhq.com",
        "domain_sector": "Comprehensive Group Health Insurance & Wellness Platform",
        "employee_count": "70-100",
        "funding_stage_investors": "Series A $15.6M (Tiger Global, Tanglin)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://plumhq.com/careers",
        "career_email": "abhishek@plumhq.com",
        "hiring_decision_maker": "Abhishek Poddar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time health insurance policy pricing calculators, automated claims submission via WhatsApp, and HR wellness dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 161,
        "company_name": "Loop Health",
        "website": "https://loophealth.com",
        "domain_sector": "Preventive Primary Care & Employee Health Insurance AI",
        "employee_count": "65-95",
        "funding_stage_investors": "Series A $12M (General Catalyst, Elevation)",
        "work_model_location": "Remote / Pune / Bangalore",
        "career_page_url": "https://loophealth.com/careers",
        "career_email": "mayank@loophealth.com",
        "hiring_decision_maker": "Mayank Kale (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "In-house medical doctor consultation video queues, automated electronic prescription sync, and group health claims tracking.",
        "outreach_status": "To Contact"
    },
    {
        "id": 162,
        "company_name": "Onsurity",
        "website": "https://onsurity.com",
        "domain_sector": "Monthly Healthcare & Health Insurance Subscriptions for SMEs",
        "employee_count": "70-100",
        "funding_stage_investors": "Series B $24M (International Finance Corporation, Quona)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://onsurity.com/careers",
        "career_email": "yogesh@onsurity.com",
        "hiring_decision_maker": "Yogesh Agarwal (Founder & CEO)",
        "nalin_tech_fit_hook": "Micro-subscription recurring payment billing engines, employee health card generation, and automated claim reimbursement bots.",
        "outreach_status": "To Contact"
    },
    {
        "id": 163,
        "company_name": "Pazcare",
        "website": "https://pazcare.com",
        "domain_sector": "Employee Benefits, Health Insurance & Wellness Administration",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $8.2M (Jafco Asia, 3one4 Capital)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://pazcare.com/careers",
        "career_email": "sanchit@pazcare.com",
        "hiring_decision_maker": "Sanchit Malik (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Employee benefits self-enrollment portals, automated insurer policy endorsement updates, and mental wellness appointment schedulers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 164,
        "company_name": "Nova Benefits",
        "website": "https://novabenefits.com",
        "domain_sector": "Employee Health Insurance Portal & Claims Automation",
        "employee_count": "45-75",
        "funding_stage_investors": "Series A $10M (Bessemer Venture Partners, SIG)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://novabenefits.com/careers",
        "career_email": "saransh@novabenefits.com",
        "hiring_decision_maker": "Saransh Garg (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Hospital bill and discharge summary OCR document parsing, claim status tracking APIs, and HR corporate benefits dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 165,
        "company_name": "Velocity.in",
        "website": "https://velocity.in",
        "domain_sector": "Revenue-Based Financing & Financial Insights for D2C Brands",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $20M (Peter Thiel's Valar Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://velocity.in/careers",
        "career_email": "abhiroop@velocity.in",
        "hiring_decision_maker": "Abhiroop Medhekar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "D2C revenue and marketing spend integrations (Shopify, Meta Ads), automated underwriting risk engines, and cash advance payouts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 166,
        "company_name": "Klub",
        "website": "https://klubworks.com",
        "domain_sector": "Revenue-Based Growth Capital & Investment Marketplace",
        "employee_count": "50-80",
        "funding_stage_investors": "Series A $20M (Alteria Capital, Trifecta)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://klubworks.com/careers",
        "career_email": "anurakt@klubworks.com",
        "hiring_decision_maker": "Anurakt Jain (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Algorithmic revenue share calculations, banking data scraping for financial underwriting, and investor portfolio return dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 167,
        "company_name": "Bikayi",
        "website": "https://bikayi.com",
        "domain_sector": "WhatsApp E-Commerce Storefront & Payment Automation",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $10.8M (Sequoia Capital India)",
        "work_model_location": "Remote / Hyderabad / Bangalore",
        "career_page_url": "https://bikayi.com/careers",
        "career_email": "sonakshi@bikayi.com",
        "hiring_decision_maker": "Sonakshi Nathani (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated online catalog generation from phone photos, WhatsApp commerce messaging bots, and integrated payment checkouts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 168,
        "company_name": "Zoko",
        "website": "https://zoko.io",
        "domain_sector": "WhatsApp Marketing, Support & Conversational Commerce",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $1.4M (Y Combinator, Ryan Hoover)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://zoko.io/careers",
        "career_email": "arjun@zoko.io",
        "hiring_decision_maker": "Arjun Rastogi (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "WhatsApp Business Cloud API high-throughput messaging, multi-agent inbox interfaces in React, and Shopify event triggers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 169,
        "company_name": "Vahan.ai",
        "website": "https://vahan.co",
        "domain_sector": "WhatsApp-Based Blue-Collar Recruitment & AI Virtual Recruiter",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $8M (Khosla Ventures, Y Combinator)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://vahan.co/careers",
        "career_email": "madhav@vahan.ai",
        "hiring_decision_maker": "Madhav Krishna (Founder & CEO)",
        "nalin_tech_fit_hook": "Conversational AI voice and text recruiters on WhatsApp, automated worker qualification screening, and job dispatching algorithms.",
        "outreach_status": "To Contact"
    },
    {
        "id": 170,
        "company_name": "Cube Wealth",
        "website": "https://bankoncube.com",
        "domain_sector": "Automated Multi-Asset Wealth Advisory & Investment App",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $2M (Prominent angel investors)",
        "work_model_location": "Remote / Mumbai",
        "career_page_url": "https://bankoncube.com/careers",
        "career_email": "satyen@bankoncube.com",
        "hiring_decision_maker": "Satyen Kothari (Founder & CEO)",
        "nalin_tech_fit_hook": "Algorithmic portfolio rebalancing engines, multi-asset class transaction routing (equities, P2P, gold), and advisory feeds.",
        "outreach_status": "To Contact"
    },
    {
        "id": 171,
        "company_name": "Wint Wealth",
        "website": "https://wintwealth.com",
        "domain_sector": "Retail Debt Assets & Fixed Income Investment Platform",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $5M (Eight Roads Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://wintwealth.com/careers",
        "career_email": "ajinkya@wintwealth.com",
        "hiring_decision_maker": "Ajinkya Kulkarni (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Covered bond order settlement systems, depository participant (CDSL/NSDL) APIs, and automated monthly interest distribution rails.",
        "outreach_status": "To Contact"
    },
    {
        "id": 172,
        "company_name": "Dezerv",
        "website": "https://dezerv.in",
        "domain_sector": "Tech-Driven Wealth Management for Tech Professionals & HNIs",
        "employee_count": "60-95",
        "funding_stage_investors": "Series B $32M (Premji Invest, Elevation Capital)",
        "work_model_location": "Remote / Mumbai / Bangalore",
        "career_page_url": "https://dezerv.in/careers",
        "career_email": "sandeep@dezerv.in",
        "hiring_decision_maker": "Sandeep Jethwani (Co-Founder)",
        "nalin_tech_fit_hook": "Integrated Portfolio Management Services (PMS) analytics, digital investment onboarding, and institutional asset allocation models.",
        "outreach_status": "To Contact"
    },
    {
        "id": 173,
        "company_name": "Stable Money",
        "website": "https://stablemoney.in",
        "domain_sector": "Fixed Deposit & Secure Yield Marketplace",
        "employee_count": "30-55",
        "funding_stage_investors": "Series A $15M (RTP Global, Lightspeed)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://stablemoney.in/careers",
        "career_email": "saurabh@stablemoney.in",
        "hiring_decision_maker": "Saurabh Jain (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Multi-bank core banking integration for instant paperless fixed deposit booking, interest rate comparison, and KYC validation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 174,
        "company_name": "Uni Cards",
        "website": "https://uni.cards",
        "domain_sector": "Smart Multi-Network Credit Cards & Pay-Later Platform",
        "employee_count": "75-100",
        "funding_stage_investors": "Series A $70M (Lightspeed, Accel)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://uni.cards/careers",
        "career_email": "nitin@uni.cards",
        "hiring_decision_maker": "Nitin Gupta (Founder & CEO)",
        "nalin_tech_fit_hook": "Low-latency payment authorization hooks, credit card transaction ledgering, and real-time cashback calculation engines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 175,
        "company_name": "Freo (MoneyTap)",
        "website": "https://freo.money",
        "domain_sector": "App-Based Credit Line & Digital Financial Services",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $40M (Prime Venture Partners, Sequoia)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://freo.money/careers",
        "career_email": "anuj@freo.money",
        "hiring_decision_maker": "Anuj Kacker (Co-Founder)",
        "nalin_tech_fit_hook": "Instant credit line limit assessment algorithms, NBFC loan disbursement rails, and recurring repayment auto-debit triggers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 176,
        "company_name": "CASHe",
        "website": "https://cashe.co.in",
        "domain_sector": "AI-Driven Instant Personal Loans & Social Loan Quotient",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $40M (Singularity Growth)",
        "work_model_location": "Remote / Mumbai",
        "career_page_url": "https://cashe.co.in/careers",
        "career_email": "yashoraj@cashe.co.in",
        "hiring_decision_maker": "Yashoraj Tyagi (CEO)",
        "nalin_tech_fit_hook": "Alternative credit scoring algorithms using mobile digital footprints, automated e-mandate registration, and instant loan settlement.",
        "outreach_status": "To Contact"
    },
    {
        "id": 177,
        "company_name": "NIRA",
        "website": "https://nirafinance.com",
        "domain_sector": "Real-Time Micro-Lending Platform for Middle-Income Earners",
        "employee_count": "40-70",
        "funding_stage_investors": "Seed $4M (Techstars, Indian angel syndicates)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://nirafinance.com/careers",
        "career_email": "rohit@nirafinance.com",
        "hiring_decision_maker": "Rohit Sen (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated bank statement analysis for payroll estimation, credit bureau CIBIL/Experian ingestion, and mobile micro-loan disbursals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 178,
        "company_name": "Finzy",
        "website": "https://finzy.com",
        "domain_sector": "Peer-to-Peer Digital Lending & Algorithmic Credit Risk",
        "employee_count": "30-50",
        "funding_stage_investors": "Series A $2.3M (Prominent BFSI angel syndicates)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://finzy.com/careers",
        "career_email": "amit@finzy.com",
        "hiring_decision_maker": "Amit More (Founder & CEO)",
        "nalin_tech_fit_hook": "P2P borrower-lender risk matching algorithms, escrow account payment reconciliation, and automated EMI collection engines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 179,
        "company_name": "Faircent",
        "website": "https://faircent.com",
        "domain_sector": "Peer-to-Peer Lending & Automated Credit Scoring Marketplace",
        "employee_count": "60-90",
        "funding_stage_investors": "Series B $10M (Incofin, Muthoot Fincorp)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://faircent.com/careers",
        "career_email": "rajat@faircent.com",
        "hiring_decision_maker": "Rajat Gandhi (Founder & CEO)",
        "nalin_tech_fit_hook": "P2P credit risk underwriting models, automated investment mandate execution, and high-volume loan portfolio performance dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 180,
        "company_name": "LenDenClub",
        "website": "https://lendenclub.com",
        "domain_sector": "P2P Lending Platform & Digital Alternative Credit Rails",
        "employee_count": "65-95",
        "funding_stage_investors": "Series A $10M (Tuscan Ventures, Ohm Stock)",
        "work_model_location": "Remote / Mumbai",
        "career_page_url": "https://lendenclub.com/careers",
        "career_email": "bhavin@lendenclub.com",
        "hiring_decision_maker": "Bhavin Patel (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Fractional micro-lending matching engine, auto-investment rules, and bank-grade escrow settlement transaction microservices.",
        "outreach_status": "To Contact"
    },
    {
        "id": 181,
        "company_name": "IndiaLends",
        "website": "https://indialends.com",
        "domain_sector": "Digital Lending, Credit Scoring & Credit Card Marketplace",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $25M (ACP Partners, American Express)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://indialends.com/careers",
        "career_email": "gaurav@indialends.com",
        "hiring_decision_maker": "Gaurav Chopra (Founder & CEO)",
        "nalin_tech_fit_hook": "Free credit report fetching engines, personalized loan recommendation pipelines, and institutional lender API adapters.",
        "outreach_status": "To Contact"
    },
    {
        "id": 182,
        "company_name": "BankSathi",
        "website": "https://banksathi.com",
        "domain_sector": "FinTech Product Marketplace & Financial Advisory App",
        "employee_count": "50-80",
        "funding_stage_investors": "Pre-Series A $4M (Kotak Securities)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://banksathi.com/careers",
        "career_email": "jitendra@banksathi.com",
        "hiring_decision_maker": "Jitendra Dhaka (Founder & CEO)",
        "nalin_tech_fit_hook": "Lead tracking and attribution mobile backends, automated commission payout ledgers, and advisor product recommendation engines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 183,
        "company_name": "GroMo",
        "website": "https://gromo.in",
        "domain_sector": "Distribution Platform for Financial Products (Insurance & Credit)",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $11M (SIG Venture Capital)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://gromo.in/careers",
        "career_email": "ankit@gromo.in",
        "hiring_decision_maker": "Ankit Khandelwal (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Partner financial app integrations, real-time lead pipeline tracking in Next.js, and instant commission payment rails.",
        "outreach_status": "To Contact"
    },
    {
        "id": 184,
        "company_name": "ZET (OneCode)",
        "website": "https://zetapp.in",
        "domain_sector": "Networked FinTech Product Distribution & Credit Enablement",
        "employee_count": "70-95",
        "funding_stage_investors": "Series A $13M (General Catalyst, Nexus VP)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://zetapp.in/careers",
        "career_email": "manish@zetapp.in",
        "hiring_decision_maker": "Manish Shara (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Direct bank API integrations for personal loan eligibility, automated agent onboarding, and microservices for commission distribution.",
        "outreach_status": "To Contact"
    },
    {
        "id": 185,
        "company_name": "Novio (Credilio)",
        "website": "https://novio.in",
        "domain_sector": "Digital Distribution Engine for Retail Loans & Credit Cards",
        "employee_count": "40-70",
        "funding_stage_investors": "Seed $4M (CornerStone Venture Partners)",
        "work_model_location": "Remote / Mumbai / Delhi-NCR",
        "career_page_url": "https://novio.in/careers",
        "career_email": "sandeep@novio.in",
        "hiring_decision_maker": "Sandeep Dhakar (Founder & CEO)",
        "nalin_tech_fit_hook": "Digital card application processing, rule-based banking eligibility check pipelines, and partner advisor performance dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 186,
        "company_name": "FloBiz (myBillBook)",
        "website": "https://flobiz.in",
        "domain_sector": "GST Billing, Inventory Accounting & SMB ERP Suite",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $31M (Sequoia Capital India, Elevation)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://flobiz.in/careers",
        "career_email": "rahul@flobiz.in",
        "hiring_decision_maker": "Rahul Raj (Founder & CEO)",
        "nalin_tech_fit_hook": "Offline-first desktop and mobile SQLite sync, GST e-invoicing API gateways, and automated stock low-inventory alerts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 187,
        "company_name": "Pepper Content",
        "website": "https://peppercontent.io",
        "domain_sector": "Content Marketing Platform & Enterprise Generative Copilot",
        "employee_count": "70-100",
        "funding_stage_investors": "Series A $14.3M (Bessemer Venture Partners, Tanglin)",
        "work_model_location": "Remote / Mumbai / Delhi-NCR",
        "career_page_url": "https://peppercontent.io/careers",
        "career_email": "anirudh@peppercontent.io",
        "hiring_decision_maker": "Anirudh Singla (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Enterprise LLM editorial copilot in Next.js, automated SEO keyword density validation, and workflow assignment queues.",
        "outreach_status": "To Contact"
    },
    {
        "id": 188,
        "company_name": "Superleap",
        "website": "https://superleap.com",
        "domain_sector": "AI-Native CRM & Automated Deal Velocity Platform",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $3.8M (Peak XV Surge)",
        "work_model_location": "Remote / Delhi-NCR / Bangalore",
        "career_page_url": "https://superleap.com/careers",
        "career_email": "sameer@superleap.com",
        "hiring_decision_maker": "Sameer Grover (Founder & CEO)",
        "nalin_tech_fit_hook": "Automated meeting note summarization, CRM contact enrichment with LLMs, and real-time deal stage forecasting pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 189,
        "company_name": "Awign",
        "website": "https://awign.com",
        "domain_sector": "Enterprise Work-as-a-Service & Gig Workforce Platform",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $15M (Bertelsmann, Mynavi)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://awign.com/careers",
        "career_email": "sarthak@awign.com",
        "hiring_decision_maker": "Annanya Sarthak (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Distributed gig task allocation algorithms, automated photo proof of work verification with computer vision, and payouts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 190,
        "company_name": "WorkIndia",
        "website": "https://workindia.in",
        "domain_sector": "Geo-Location Blue-Collar Employment Marketplace",
        "employee_count": "70-100",
        "funding_stage_investors": "Series A $12M (Beenext, Asuka Asset)",
        "work_model_location": "Remote / Mumbai / Bangalore",
        "career_page_url": "https://workindia.in/careers",
        "career_email": "kunal@workindia.in",
        "hiring_decision_maker": "Kunal Patil (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Geographic hyper-local job search indexing, automated tele-screening verification bots, and low-latency mobile API backends.",
        "outreach_status": "To Contact"
    },
    {
        "id": 191,
        "company_name": "Gigforce",
        "website": "https://gigforce.in",
        "domain_sector": "On-Demand Staffing & Workforce Management Platform",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $3M (Endiya Partners)",
        "work_model_location": "Remote / Delhi-NCR / Bangalore",
        "career_page_url": "https://gigforce.in/careers",
        "career_email": "chirag@gigforce.in",
        "hiring_decision_maker": "Chirag Mittal (Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time gig shift scheduling algorithms, biometric time-tracking sync, and automated payroll disbursement pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 192,
        "company_name": "Newton School",
        "website": "https://newtonschool.co",
        "domain_sector": "Outcome-Driven Tech School & AI Software Academy",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $25M (Steadview Capital, Nexus VP)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://newtonschool.co/careers",
        "career_email": "nishant@newtonschool.co",
        "hiring_decision_maker": "Nishant Chandra (Co-Founder) & Siddharth Maheshwari (Co-Founder)",
        "nalin_tech_fit_hook": "Automated code execution judging sandboxes, personalized learning path recommendations, and student job portal interfaces.",
        "outreach_status": "To Contact"
    },
    {
        "id": 193,
        "company_name": "Masai School",
        "website": "https://masaischool.com",
        "domain_sector": "Coding Bootcamp & Tech Skill Acceleration Platform",
        "employee_count": "70-100",
        "funding_stage_investors": "Series B $10M (India Quotient, Unitus)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://masaischool.com/careers",
        "career_email": "prateek@masaischool.com",
        "hiring_decision_maker": "Prateek Shukla (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Income Share Agreement (ISA) tracking ledgers, student coding challenge assessment engines, and employer recruitment portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 194,
        "company_name": "AlmaBetter",
        "website": "https://almabetter.com",
        "domain_sector": "Online AI, Machine Learning & Data Science Academy",
        "employee_count": "40-70",
        "funding_stage_investors": "Seed $2.7M (Kalaari Capital)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://almabetter.com/careers",
        "career_email": "shivam@almabetter.com",
        "hiring_decision_maker": "Shivam Dutta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Jupyter notebook automated grading backends, real-time live lecture interactive polls in Next.js, and student resume AI reviewers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 195,
        "company_name": "Teachmint",
        "website": "https://teachmint.com",
        "domain_sector": "AI-Enabled Teaching OS & School Infrastructure Software",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $78M (Rocketship.vc, Vulcan, Lightspeed)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://teachmint.com/careers",
        "career_email": "mihir@teachmint.com",
        "hiring_decision_maker": "Mihir Gupta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Two-way live interactive whiteboard WebRTC streaming, automated test generation with LLMs, and school fee management portals.",
        "outreach_status": "To Contact"
    },
    {
        "id": 196,
        "company_name": "Stashfin",
        "website": "https://stashfin.com",
        "domain_sector": "Neobanking, Digital Credit Line & Card Platform",
        "employee_count": "75-100",
        "funding_stage_investors": "Series B $70M (Uncorrelated Ventures, Fasanara)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://stashfin.com/careers",
        "career_email": "tushar@stashfin.com",
        "hiring_decision_maker": "Tushar Patel (Founder & CEO)",
        "nalin_tech_fit_hook": "Digital card issuance APIs, transaction fraud monitoring models, and loan portfolio ledger management microservices.",
        "outreach_status": "To Contact"
    },
    {
        "id": 197,
        "company_name": "Battery Smart",
        "website": "https://batterysmart.in",
        "domain_sector": "Two & Three-Wheeler EV Battery Swapping Network",
        "employee_count": "80-100",
        "funding_stage_investors": "Series B $33M (Tiger Global, Blume Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://batterysmart.in/careers",
        "career_email": "pulkit@batterysmart.in",
        "hiring_decision_maker": "Pulkit Khurana (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Battery swap station IoT telemetry, driver reservation matching algorithms, and battery health degradation prediction.",
        "outreach_status": "To Contact"
    },
    {
        "id": 198,
        "company_name": "Cashify",
        "website": "https://cashify.in",
        "domain_sector": "Re-Commerce Platform & Device Diagnostics Automation",
        "employee_count": "80-100",
        "funding_stage_investors": "Series B $15M (New Enterprise Associates)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://cashify.in/careers",
        "career_email": "mandeep@cashify.in",
        "hiring_decision_maker": "Mandeep Manocha (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Mobile hardware diagnostic algorithms on smartphone sensors, algorithmic refurbished pricing models, and doorstep pickup routing.",
        "outreach_status": "To Contact"
    },
    {
        "id": 199,
        "company_name": "Soothe Healthcare",
        "website": "https://paree.in",
        "domain_sector": "Personal Healthcare Products & Supply Chain Tech",
        "employee_count": "60-90",
        "funding_stage_investors": "Series B $20M (Aavishkaar Capital)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://paree.in/careers",
        "career_email": "sahil@paree.in",
        "hiring_decision_maker": "Sahil Dharia (Founder & CEO)",
        "nalin_tech_fit_hook": "Supply chain inventory demand forecasting models, distributor ordering portals, and D2C e-commerce checkout funnels.",
        "outreach_status": "To Contact"
    },
    {
        "id": 200,
        "company_name": "Pee Safe",
        "website": "https://peesafe.com",
        "domain_sector": "Hygiene Tech & D2C Health Care Platform",
        "employee_count": "45-75",
        "funding_stage_investors": "Series B $3M (Natco Pharma, Alkemi)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://peesafe.com/careers",
        "career_email": "vikas@peesafe.com",
        "hiring_decision_maker": "Vikas Bagaria (Founder & CEO)",
        "nalin_tech_fit_hook": "Omnichannel retail replenishment analytics, D2C subscription replenishment microservices, and customer retention tracking.",
        "outreach_status": "To Contact"
    },
    {
        "id": 201,
        "company_name": "Leaf Round",
        "website": "https://leafround.com",
        "domain_sector": "Fractional Asset-Backed Leasing & Alternative Yield",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Indian angel networks)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://leafround.com/careers",
        "career_email": "nishat@leafround.com",
        "hiring_decision_maker": "Nishat Nayak (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Asset lease payment escrow tracking, fractional investment contracts generation, and investor monthly return ledgers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 202,
        "company_name": "AltGraaf",
        "website": "https://altgraaf.com",
        "domain_sector": "High-Yield Fixed Return Alternative Debt Platform",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $2M (Prominent angel syndicates)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://altgraaf.com/careers",
        "career_email": "founders@altgraaf.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Corporate invoice discounting rails, credit assessment data pipelines, and real-time yield distribution calculators.",
        "outreach_status": "To Contact"
    },
    {
        "id": 203,
        "company_name": "Spenny",
        "website": "https://spennyapp.com",
        "domain_sector": "Micro-Investing & Spare Change Savings App",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1M (Y Combinator, 500 Global)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://spennyapp.com/careers",
        "career_email": "rathnakar@spennyapp.com",
        "hiring_decision_maker": "Rathnakar Samavedam (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "SMS payment parsing for transaction roundups, automated mutual fund micro-investing APIs, and portfolio analytics in React.",
        "outreach_status": "To Contact"
    },
    {
        "id": 204,
        "company_name": "TapChief",
        "website": "https://tapchief.com",
        "domain_sector": "On-Demand Professional Services & Talent Marketplace",
        "employee_count": "30-50",
        "funding_stage_investors": "Seed $1.5M (Blume Ventures, 500 Startups)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://tapchief.com/careers",
        "career_email": "shashank@tapchief.com",
        "hiring_decision_maker": "Shashank Murali (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Consultant skill matching algorithms, automated project milestone escrow payments, and client timesheet tracking.",
        "outreach_status": "To Contact"
    }
]
