# Batch 3: Companies 103 to 153 (Open-Source, Developer Platforms, Observability & Cloud Tools)

BATCH_3 = [
    {'career_email': 'pranay@signoz.io',
 'career_page_url': 'https://signoz.io/careers',
 'company_name': 'SigNoz',
 'domain_sector': 'Open-Source APM, Distributed Tracing & Observability',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $6.5M (Y Combinator W21, Uncorrelated)',
 'hiring_decision_maker': 'Pranay Prateek (Co-Founder) & Ankit Nayan (Co-Founder)',
 'id': 103,
 'nalin_tech_fit_hook': 'Building high-performance ClickHouse telemetry query pipelines, OpenTelemetry instrumentation '
                        'agents, and Next.js trace viewers.',
 'outreach_status': 'To Contact',
 'website': 'https://signoz.io',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'vamsi@plane.so',
 'career_page_url': 'https://plane.so/careers',
 'company_name': 'Plane (Plane.so)',
 'domain_sector': 'Open-Source Project Management & Engineering Workflow',
 'employee_count': '25-50',
 'funding_stage_investors': 'Seed $4M (OSS Capital, Y Combinator)',
 'hiring_decision_maker': 'Vamsi Kurama (Co-Founder & CEO) & Manoj Kumar (Co-Founder)',
 'id': 104,
 'nalin_tech_fit_hook': 'Real-time collaborative Kanban/Gantt state sync with WebSockets, optimistic UI updates in '
                        'Next.js, and issue triage AI agents.',
 'outreach_status': 'To Contact',
 'website': 'https://plane.so',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'harjot@coderabbit.ai',
 'career_page_url': 'https://coderabbit.ai/careers',
 'company_name': 'CodeRabbit',
 'domain_sector': 'AI-Powered Code Review & Automated PR Summaries',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $16M (CRV)',
 'hiring_decision_maker': 'Harjot Gill (Co-Founder & CEO) & Gurinder Bains (Co-Founder)',
 'id': 105,
 'nalin_tech_fit_hook': 'AST code diff parsing, automated PR security linting with LLM context, and webhook-driven '
                        'GitHub action review bots.',
 'outreach_status': 'To Contact',
 'website': 'https://coderabbit.ai',
 'work_model_location': 'Remote / Bangalore / Global'},
    {'career_email': 'navaneeth@tooljet.com',
 'career_page_url': 'https://tooljet.com/careers',
 'company_name': 'ToolJet',
 'domain_sector': 'Open-Source Low-Code Platform for Internal Engineering Tools',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $4.6M (Nexus Venture Partners, M12)',
 'hiring_decision_maker': 'Navaneeth P K (Founder & CEO)',
 'id': 106,
 'nalin_tech_fit_hook': 'Building drag-and-drop React canvas components, database connector sandboxes in Node/FastAPI, '
                        'and automated query runners.',
 'outreach_status': 'To Contact',
 'website': 'https://tooljet.com',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'ashish@stepsecurity.io',
 'career_page_url': 'https://stepsecurity.io/careers',
 'company_name': 'StepSecurity',
 'domain_sector': 'CI/CD Pipeline AI Security & Automated Remediation',
 'employee_count': '10-20',
 'funding_stage_investors': 'Seed $3M (Runtime Ventures)',
 'hiring_decision_maker': 'Ashish Kurmi (Co-Founder & CEO) & Varun Sharma (Co-Founder)',
 'id': 107,
 'nalin_tech_fit_hook': 'GitHub Actions outbound network traffic inspection, automated least-privilege token '
                        'generation, and pull request auto-fix bots.',
 'outreach_status': 'To Contact',
 'website': 'https://stepsecurity.io',
 'work_model_location': 'Fully Remote (India)'},
    {'career_email': 'kahseng@locofy.ai',
 'career_page_url': 'https://locofy.ai/careers',
 'company_name': 'Locofy.ai',
 'domain_sector': 'AI Design-to-Code Platform (Figma to React/Next.js)',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $4.5M (Accel, January Capital)',
 'hiring_decision_maker': 'Kah Seng Tay (Co-Founder & CEO) & Sohaib Muhammad (Co-Founder)',
 'id': 108,
 'nalin_tech_fit_hook': 'Translating Figma layout hierarchies into production-clean Next.js/Tailwind components with '
                        'responsive CSS generation.',
 'outreach_status': 'To Contact',
 'website': 'https://locofy.ai',
 'work_model_location': 'Fully Remote (India)'},
    {'career_email': 'vishal@dhiwise.com',
 'career_page_url': 'https://dhiwise.com/careers',
 'company_name': 'DhiWise',
 'domain_sector': 'Developer Programming Automation & App Generation Platform',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $7M (Accel, Together Fund)',
 'hiring_decision_maker': 'Vishal Virani (Founder & CEO) & Rahul Shingala (Co-Founder)',
 'id': 109,
 'nalin_tech_fit_hook': 'Full-stack code generation algorithms, OpenAPI schema to client SDK builders, and Next.js '
                        'project scaffolders.',
 'outreach_status': 'To Contact',
 'website': 'https://dhiwise.com',
 'work_model_location': 'Fully Remote (India)'},
    {'career_email': 'abhishek@appsmith.com',
 'career_page_url': 'https://appsmith.com/careers',
 'company_name': 'Appsmith',
 'domain_sector': 'Open-Source Low-Code Application Platform',
 'employee_count': '70-100',
 'funding_stage_investors': 'Series B $41M (Insight Partners, Accel)',
 'hiring_decision_maker': 'Abhishek Nayak (Co-Founder & CEO) & Arpit Mohan (CTO)',
 'id': 110,
 'nalin_tech_fit_hook': 'Client-side reactive JavaScript evaluation engine, complex data table virtualization, and '
                        'database query orchestrators.',
 'outreach_status': 'To Contact',
 'website': 'https://appsmith.com',
 'work_model_location': 'Fully Remote (India/Global)'},
    {'career_email': 'krrish@berri.ai',
 'career_page_url': 'https://litellm.ai/careers',
 'company_name': 'LiteLLM (BerriAI)',
 'domain_sector': 'Open-Source Universal LLM Gateway & Proxy',
 'employee_count': '8-15',
 'funding_stage_investors': 'Seed $2.5M (Y Combinator W23)',
 'hiring_decision_maker': 'Krrish Dholakia (Co-Founder) & Ishaan Jaff (Co-Founder)',
 'id': 111,
 'nalin_tech_fit_hook': 'High-throughput async Python/FastAPI proxy, 100+ LLM API standardization, load-balancing '
                        'fallbacks, and redis rate limiting.',
 'outreach_status': 'To Contact',
 'website': 'https://litellm.ai',
 'work_model_location': 'Fully Remote (India/Global)'},
    {'career_email': 'hamzah@lightdash.com',
 'career_page_url': 'https://lightdash.com/careers',
 'company_name': 'Lightdash',
 'domain_sector': 'Open-Source Business Intelligence & Semantic Layer',
 'employee_count': '20-35',
 'funding_stage_investors': 'Seed $8.4M (Y Combinator, Accel)',
 'hiring_decision_maker': 'Hamzah Chaudhary (Founder & CEO)',
 'id': 112,
 'nalin_tech_fit_hook': 'dbt semantic layer integration, fast SQL metric querying, and interactive visualization '
                        'dashboards in React/TypeScript.',
 'outreach_status': 'To Contact',
 'website': 'https://lightdash.com',
 'work_model_location': 'Fully Remote (India)'},
    {'career_email': 'gaurav@bytebeam.io',
 'career_page_url': 'https://bytebeam.io/careers',
 'company_name': 'Bytebeam',
 'domain_sector': 'Cloud Platform for Connected IoT Devices & Over-The-Air Updates',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $3M (Together Fund, Accel)',
 'hiring_decision_maker': 'Gaurav Minhas (Co-Founder & CEO) & Bharadwaz Gourineni (Co-Founder)',
 'id': 113,
 'nalin_tech_fit_hook': 'MQTT telematics streaming backends, edge OTA firmware upgrade verification, and real-time '
                        'device fleet health consoles.',
 'outreach_status': 'To Contact',
 'website': 'https://bytebeam.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'dilip@cogniswitch.ai',
 'career_page_url': 'https://cogniswitch.ai/careers',
 'company_name': 'CogniSwitch',
 'domain_sector': 'Knowledge Extraction & Document Ingestion for LLM Pipelines',
 'employee_count': '10-25',
 'funding_stage_investors': 'Seed $1.2M (Peak XV Surge network)',
 'hiring_decision_maker': 'Dilip Venkat (Founder & CEO)',
 'id': 114,
 'nalin_tech_fit_hook': 'Semantic document chunking algorithms, knowledge graph triple extraction, and sub-second RAG '
                        'context synthesis in Python.',
 'outreach_status': 'To Contact',
 'website': 'https://cogniswitch.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'rupesh@cognisaas.com',
 'career_page_url': 'https://cognisaas.com/careers',
 'company_name': 'CogniSaaS',
 'domain_sector': 'Customer Onboarding & Value Delivery Tracking SaaS',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1M (Speciale Invest, Whiteboard)',
 'hiring_decision_maker': 'Rupesh Rao (Founder & CEO)',
 'id': 115,
 'nalin_tech_fit_hook': 'Interactive Gantt chart rendering in Next.js, automated milestone risk prediction, and '
                        'customer onboarding status tracking.',
 'outreach_status': 'To Contact',
 'website': 'https://cognisaas.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'alister@usefini.com',
 'career_page_url': 'https://usefini.com/careers',
 'company_name': 'Fini (usefini)',
 'domain_sector': '24/7 AI Knowledge Base & Support Bot Agent',
 'employee_count': '10-20',
 'funding_stage_investors': 'Seed $2M (Angel syndicates)',
 'hiring_decision_maker': 'Alister Esam (Founder & CEO)',
 'id': 116,
 'nalin_tech_fit_hook': 'Zero-hallucination support agent pipelines, documentation scraping & semantic indexing, and '
                        'Zendesk/Intercom integrations.',
 'outreach_status': 'To Contact',
 'website': 'https://usefini.com',
 'work_model_location': 'Fully Remote (India)'},
    {'career_email': 'siddharth@spendflo.com',
 'career_page_url': 'https://spendflo.com/careers',
 'company_name': 'Spendflo',
 'domain_sector': 'SaaS Procurement, Management & Optimization Platform',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $11M (Accel, Together Fund)',
 'hiring_decision_maker': 'Siddharth Sridharan (Co-Founder & CEO)',
 'id': 117,
 'nalin_tech_fit_hook': 'Automated contract metadata extraction using LLMs, vendor benchmark pricing comparisons, and '
                        'renewal notification alerts.',
 'outreach_status': 'To Contact',
 'website': 'https://spendflo.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'vaibhav@privado.ai',
 'career_page_url': 'https://privado.ai/careers',
 'company_name': 'Privado.ai',
 'domain_sector': 'Developer-First Code Scanning for Privacy & Compliance',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $14M (Peak XV, Together Fund)',
 'hiring_decision_maker': 'Vaibhav Antil (Co-Founder & CEO)',
 'id': 118,
 'nalin_tech_fit_hook': 'Static code analysis AST parsers to trace sensitive user data flows, automated GDPR/CCPA risk '
                        'detection, and CI/CD gates.',
 'outreach_status': 'To Contact',
 'website': 'https://privado.ai',
 'work_model_location': 'Fully Remote (India) / Delhi-NCR'},
    {'career_email': 'arvind@superops.com',
 'career_page_url': 'https://superops.com/careers',
 'company_name': 'SuperOps',
 'domain_sector': 'Unified PSA & RMM Platform for Managed Service Providers',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $12.4M (Addition, March Capital)',
 'hiring_decision_maker': 'Arvind Parthiban (Co-Founder & CEO)',
 'id': 119,
 'nalin_tech_fit_hook': 'Automated IT asset discovery, script execution engines for remote endpoints, and intelligent '
                        'ticket dispatching algorithms.',
 'outreach_status': 'To Contact',
 'website': 'https://superops.com',
 'work_model_location': 'Remote / Chennai / Bangalore'},
    {'career_email': 'srikrishnan@rocketlane.com',
 'career_page_url': 'https://rocketlane.com/careers',
 'company_name': 'Rocketlane',
 'domain_sector': 'Collaborative Customer Onboarding & Professional Services SaaS',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $24M (8VC, Nexus VP, Matrix)',
 'hiring_decision_maker': 'Srikrishnan Ganesan (Co-Founder & CEO)',
 'id': 120,
 'nalin_tech_fit_hook': 'Real-time client portal collaboration, project template automation, and resource utilization '
                        'forecasting dashboards in React.',
 'outreach_status': 'To Contact',
 'website': 'https://rocketlane.com',
 'work_model_location': 'Fully Remote (India) / Chennai'},
    {'career_email': 'girish@sprinto.com',
 'career_page_url': 'https://sprinto.com/careers',
 'company_name': 'Sprinto',
 'domain_sector': 'Automated Security Compliance & Audit Readiness',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $20M (Accel, Elevation Capital)',
 'hiring_decision_maker': 'Girish Redekar (Co-Founder & CEO)',
 'id': 121,
 'nalin_tech_fit_hook': 'Automated cloud security evidence collection across AWS/GCP, continuous SOC 2/ISO 27001 '
                        'monitoring, and auditor portals.',
 'outreach_status': 'To Contact',
 'website': 'https://sprinto.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'aravind@factors.ai',
 'career_page_url': 'https://factors.ai/careers',
 'company_name': 'Factors.ai',
 'domain_sector': 'Account-Based Marketing Analytics & Attribution AI',
 'employee_count': '30-55',
 'funding_stage_investors': 'Series A $3.6M (Elevation Capital, Emergent)',
 'hiring_decision_maker': 'Aravind Murthy (Co-Founder & CEO)',
 'id': 122,
 'nalin_tech_fit_hook': 'Multi-touch marketing attribution algorithms, account de-anonymization data streams, and '
                        'automated revenue funnel visualizations.',
 'outreach_status': 'To Contact',
 'website': 'https://factors.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'anshuman@clearfeed.ai',
 'career_page_url': 'https://clearfeed.ai/careers',
 'company_name': 'ClearFeed',
 'domain_sector': 'Conversational Support Orchestration in Slack & Teams',
 'employee_count': '25-45',
 'funding_stage_investors': 'Series A $4.2M (Peak XV Surge, 8VC)',
 'hiring_decision_maker': 'Anshuman Singh (Co-Founder & CEO)',
 'id': 123,
 'nalin_tech_fit_hook': 'High-throughput Slack/Teams webhook ingestion, GPT-powered ticket summarization, and '
                        'bi-directional Zendesk/Jira syncing.',
 'outreach_status': 'To Contact',
 'website': 'https://clearfeed.ai',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'ritish@zluri.com',
 'career_page_url': 'https://zluri.com/careers',
 'company_name': 'Zluri',
 'domain_sector': 'Enterprise SaaS Management & AI Access Automation',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $20M (Lightspeed, MassMutual)',
 'hiring_decision_maker': 'Ritish Reddy (Co-Founder) & Sethu Meenakshisundaram (Co-Founder)',
 'id': 124,
 'nalin_tech_fit_hook': 'Automated user app provisioning workflows, license utilization trackers, and generative AI IT '
                        'helpdesk agents.',
 'outreach_status': 'To Contact',
 'website': 'https://zluri.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'aayush@scrut.io',
 'career_page_url': 'https://scrut.io/careers',
 'company_name': 'Scrut Automation',
 'domain_sector': 'Information Security & Risk Management Compliance AI',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $10M (Lightspeed, MassMutual)',
 'hiring_decision_maker': 'Aayush Ghosh Choudhury (Founder & CEO)',
 'id': 125,
 'nalin_tech_fit_hook': 'Automated cloud asset inventory scanning, risk posture scoring algorithms, and '
                        'multi-framework audit workflows.',
 'outreach_status': 'To Contact',
 'website': 'https://scrut.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'shesh@kapture.cx',
 'career_page_url': 'https://kapture.cx/careers',
 'company_name': 'Kapture CX',
 'domain_sector': 'Enterprise Customer Experience & GenAI Support Suite',
 'employee_count': '60-95',
 'funding_stage_investors': 'Series A $4M (Cactus Venture Partners)',
 'hiring_decision_maker': 'Sheshgiri Kamath (Founder & CEO)',
 'id': 126,
 'nalin_tech_fit_hook': 'Generative response assist for support agents, omnichannel routing engines, and automated '
                        'CSAT sentiment extraction.',
 'outreach_status': 'To Contact',
 'website': 'https://kapture.cx',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'surga@salesken.ai',
 'career_page_url': 'https://salesken.ai/careers',
 'company_name': 'Salesken.ai',
 'domain_sector': 'Real-Time Conversational Sales Intelligence & Cueing AI',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $22M (M12 - Microsoft, Sequoia)',
 'hiring_decision_maker': 'Surga Thilakan (Co-Founder & CEO)',
 'id': 127,
 'nalin_tech_fit_hook': 'Live speech-to-text during sales calls with sub-second battle card retrieval and '
                        'objection-handling prompts.',
 'outreach_status': 'To Contact',
 'website': 'https://salesken.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ankit@signzy.com',
 'career_page_url': 'https://signzy.com/careers',
 'company_name': 'Signzy',
 'domain_sector': 'AI-Powered Video KYC & Digital Onboarding APIs',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $26M (Gaja Capital, Vertex)',
 'hiring_decision_maker': 'Ankit Ratan (Co-Founder & CEO)',
 'id': 128,
 'nalin_tech_fit_hook': 'Facial liveness verification algorithms, government database check APIs, and bank-grade '
                        'secure video calling architectures.',
 'outreach_status': 'To Contact',
 'website': 'https://signzy.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'ranjan@entropik.io',
 'career_page_url': 'https://entropik.io/careers',
 'company_name': 'Entropik Tech',
 'domain_sector': 'Emotion AI & Neuromarketing Consumer Insights',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series B $25M (Bessemer, SIG)',
 'hiring_decision_maker': 'Ranjan Kumar (Founder & CEO)',
 'id': 129,
 'nalin_tech_fit_hook': 'Facial expression coding, eye-tracking heatmaps on web video, and automated consumer '
                        'sentiment scoring algorithms.',
 'outreach_status': 'To Contact',
 'website': 'https://entropik.io',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'vinay@arya.ai',
 'career_page_url': 'https://arya.ai/careers',
 'company_name': 'Arya.ai',
 'domain_sector': 'Enterprise AI Operating System & Deep Learning for BFSI',
 'employee_count': '35-60',
 'funding_stage_investors': 'Seed $2M (Aurionpro Solutions)',
 'hiring_decision_maker': 'Vinay Kumar (Founder & CEO)',
 'id': 130,
 'nalin_tech_fit_hook': 'Autonomous underwriting models, fraud detection neural nets for claims, and explainable AI '
                        'audit tools in Python.',
 'outreach_status': 'To Contact',
 'website': 'https://arya.ai',
 'work_model_location': 'Remote / Mumbai / Bangalore'},
    {'career_email': 'sriram@iamdave.ai',
 'career_page_url': 'https://iamdave.ai/careers',
 'company_name': 'DaveAI',
 'domain_sector': 'AI Avatars & Interactive 3D Digital Sales Experience',
 'employee_count': '25-45',
 'funding_stage_investors': 'Pre-Series A $1M (Indian angel syndicates)',
 'hiring_decision_maker': 'Sriram P H (Co-Founder & CEO)',
 'id': 131,
 'nalin_tech_fit_hook': 'WebGL interactive virtual avatars, real-time facial animation synthesis, and conversational '
                        'product recommendation engines.',
 'outreach_status': 'To Contact',
 'website': 'https://iamdave.ai',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'vinay@hubbler.mobi',
 'career_page_url': 'https://hubbler.mobi/careers',
 'company_name': 'Hubbler',
 'domain_sector': 'No-Code Enterprise Workflow Automation Platform',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $1.5M (Prominent angel syndicates)',
 'hiring_decision_maker': 'Vinay Agrrawal (Founder & CEO)',
 'id': 132,
 'nalin_tech_fit_hook': 'Dynamic form and business process modeling engines, mobile offline sync, and enterprise '
                        'role-based access controllers.',
 'outreach_status': 'To Contact',
 'website': 'https://hubbler.mobi',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'jinen@dronahq.com',
 'career_page_url': 'https://dronahq.com/careers',
 'company_name': 'DronaHQ',
 'domain_sector': 'Low-Code Internal Tool Builder & API Integration Suite',
 'employee_count': '40-70',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Jinen Dedhia (Co-Founder) & Divyesh Kharade (Co-Founder)',
 'id': 133,
 'nalin_tech_fit_hook': 'Interactive UI component drag-and-drop engines, REST/GraphQL connector plugins, and secure '
                        'on-prem enterprise deployments.',
 'outreach_status': 'To Contact',
 'website': 'https://dronahq.com',
 'work_model_location': 'Remote / Mumbai / Bangalore'},
    {'career_email': 'nitin@pando.ai',
 'career_page_url': 'https://pando.ai/careers',
 'company_name': 'Pando',
 'domain_sector': 'Networked Supply Chain Control Tower & Logistics AI',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $30M (Iron Pillar, Uncorrelated)',
 'hiring_decision_maker': 'Nitin Jayakrishnan (Co-Founder & CEO)',
 'id': 134,
 'nalin_tech_fit_hook': 'Enterprise freight rate bidding algorithms, multi-carrier shipment track & trace, and '
                        'automated freight audit reconciliation.',
 'outreach_status': 'To Contact',
 'website': 'https://pando.ai',
 'work_model_location': 'Remote / Chennai / Bangalore'},
    {'career_email': 'nitish@freightfox.ai',
 'career_page_url': 'https://freightfox.ai/careers',
 'company_name': 'Freight Fox',
 'domain_sector': 'Manufacturing Freight Procurement & Transport Analytics AI',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $1.5M (Prominent logistics angels)',
 'hiring_decision_maker': 'Nitish Rai (Co-Founder & CEO)',
 'id': 135,
 'nalin_tech_fit_hook': 'Machine learning lane pricing indices, carbon emission transport trackers, and logistics '
                        'procurement contract automation.',
 'outreach_status': 'To Contact',
 'website': 'https://freightfox.ai',
 'work_model_location': 'Remote / Pune / Bangalore'},
    {'career_email': 'ram@wizfreight.com',
 'career_page_url': 'https://wizfreight.com/careers',
 'company_name': 'Wiz Freight',
 'domain_sector': 'Cross-Border Digital Freight Forwarding Platform',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $15M (Tiger Global, Nippon Express)',
 'hiring_decision_maker': 'Ramkumar Govindarajan (Co-Founder & CEO)',
 'id': 136,
 'nalin_tech_fit_hook': 'Ocean container shipment tracking via satellite AIS data, customs filing document automation, '
                        'and port fee calculators.',
 'outreach_status': 'To Contact',
 'website': 'https://wizfreight.com',
 'work_model_location': 'Remote / Chennai / Gurgaon'},
    {'career_email': 'amitabh@cogoport.com',
 'career_page_url': 'https://cogoport.com/careers',
 'company_name': 'Cogoport',
 'domain_sector': 'Global Trade Technology & Container Freight Booking AI',
 'employee_count': '80-100',
 'funding_stage_investors': 'Series B $50M (Tiger Global)',
 'hiring_decision_maker': 'Amitabh Shankar (CEO)',
 'id': 137,
 'nalin_tech_fit_hook': 'International freight marketplace quotation engines, trade financing risk models, and '
                        'shipment documentation OCR.',
 'outreach_status': 'To Contact',
 'website': 'https://cogoport.com',
 'work_model_location': 'Remote / Mumbai / Gurgaon'},
    {'career_email': 'marc@langfuse.com',
 'career_page_url': 'https://langfuse.com/careers',
 'company_name': 'Langfuse',
 'domain_sector': 'Open Source LLM Engineering, Observability & Tracing',
 'employee_count': '10-25',
 'funding_stage_investors': 'Seed $4M (Lightspeed, Y Combinator W23)',
 'hiring_decision_maker': 'Marc Klingen (Co-Founder & CEO)',
 'id': 138,
 'nalin_tech_fit_hook': 'Building low-overhead open telemetry spans, LLM prompt evaluation pipelines, and '
                        'high-throughput trace ingestion in Next.js/FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://langfuse.com',
 'work_model_location': 'Fully Remote (India/Global)'},
    {'career_email': 'yash@nimbuspost.com',
 'career_page_url': 'https://nimbuspost.com/careers',
 'company_name': 'NimbusPost',
 'domain_sector': 'Tech-Enabled Logistics Aggregator & Courier AI Platform',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $5M (Prominent logistics investors)',
 'hiring_decision_maker': 'Yash Jain (Co-Founder & CEO)',
 'id': 139,
 'nalin_tech_fit_hook': 'Courier rate calculation engines, automated non-delivery report (NDR) IVR confirmation bots, '
                        'and shipping label generation.',
 'outreach_status': 'To Contact',
 'website': 'https://nimbuspost.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'zaiba@ithinklogistics.com',
 'career_page_url': 'https://ithinklogistics.com/careers',
 'company_name': 'iThink Logistics',
 'domain_sector': 'AI Shipping Aggregator & Non-Delivery Reduction (NDR) AI',
 'employee_count': '45-75',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Zaiba Sarang (Co-Founder)',
 'id': 140,
 'nalin_tech_fit_hook': 'Automated WhatsApp NDR customer contact bots, predictive delivery date estimators, and '
                        'multi-courier API reconciliation.',
 'outreach_status': 'To Contact',
 'website': 'https://ithinklogistics.com',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR'},
    {'career_email': 'nisschal@shyplite.com',
 'career_page_url': 'https://shyplite.com/careers',
 'company_name': 'Shyplite',
 'domain_sector': 'Multicarrier Shipping Gateway & Fulfillment Software',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $8M (Prominent Indian syndicates)',
 'hiring_decision_maker': 'Nisschal Jaain (Co-Founder & CEO)',
 'id': 141,
 'nalin_tech_fit_hook': 'Unified logistics API gateway, warehouse inventory synchronization, and automated customs '
                        'documentation for exports.',
 'outreach_status': 'To Contact',
 'website': 'https://shyplite.com',
 'work_model_location': 'Delhi-NCR (New Delhi) / Hybrid'},
    {'career_email': 'nayan@shipyaari.com',
 'career_page_url': 'https://shipyaari.com/careers',
 'company_name': 'Shipyaari',
 'domain_sector': 'Automated SaaS Logistics & Inter-City Freight Platform',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $6M (Tuscan Ventures)',
 'hiring_decision_maker': 'Nayan Ratandhayara (Co-Founder & CEO)',
 'id': 142,
 'nalin_tech_fit_hook': 'Algorithmic courier recommendation engines, real-time shipment milestone webhooks, and seller '
                        'billing reconciliation.',
 'outreach_status': 'To Contact',
 'website': 'https://shipyaari.com',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR'},
    {'career_email': 'hrishikesh@zolvit.com',
 'career_page_url': 'https://zolvit.com/careers',
 'company_name': 'Vakilsearch (Zolvit)',
 'domain_sector': 'Legal, Tax & Compliance Automation Cloud for Businesses',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $10M (Inflexor Ventures)',
 'hiring_decision_maker': 'Hrishikesh Datar (Founder & CEO)',
 'id': 143,
 'nalin_tech_fit_hook': 'Automated trademark classification search, legal drafting document builders, and MCA annual '
                        'compliance filing workflows.',
 'outreach_status': 'To Contact',
 'website': 'https://zolvit.com',
 'work_model_location': 'Remote / Chennai / Delhi-NCR'},
    {'career_email': 'lionel@indiafilings.com',
 'career_page_url': 'https://indiafilings.com/careers',
 'company_name': 'IndiaFilings',
 'domain_sector': 'Cloud Legal, Incorporation & Tax Filing Platform',
 'employee_count': '80-100',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Lionel Charles (Founder & CEO)',
 'id': 144,
 'nalin_tech_fit_hook': 'LEDGERS cloud accounting software, automated GST filing engines, and digital signature '
                        'certificate verification APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://indiafilings.com',
 'work_model_location': 'Remote / Chennai / New Delhi'},
    {'career_email': 'vishvajit@quicko.com',
 'career_page_url': 'https://quicko.com/careers',
 'company_name': 'Quicko',
 'domain_sector': 'Online Tax Planning, Filing & Financial Developer APIs',
 'employee_count': '30-50',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Vishvajit Sonagara (Founder & CEO)',
 'id': 145,
 'nalin_tech_fit_hook': 'Capital gains tax calculation engines for Zerodha/Groww traders, Form 16 OCR parsing, and '
                        'income tax e-filing JSON APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://quicko.com',
 'work_model_location': 'Remote / Ahmedabad / Bangalore'},
    {'career_email': 'rajith@volopay.com',
 'career_page_url': 'https://volopay.com/careers',
 'company_name': 'Volopay',
 'domain_sector': 'Corporate Cards, Automated Accounts Payable & Expense SaaS',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $29M (Y Combinator, JAM Fund)',
 'hiring_decision_maker': 'Rajith Shaji (Co-Founder & CEO)',
 'id': 146,
 'nalin_tech_fit_hook': 'Virtual corporate card issuance rails, multi-currency international wire transfers, and '
                        'automated invoice OCR approval trees.',
 'outreach_status': 'To Contact',
 'website': 'https://volopay.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'hemant@enkash.com',
 'career_page_url': 'https://enkash.com/careers',
 'company_name': 'EnKash',
 'domain_sector': 'All-In-One Commercial Payments & Corporate Spend Management',
 'employee_count': '70-100',
 'funding_stage_investors': 'Series B $20M (Ascent Capital, Baring India)',
 'hiring_decision_maker': 'Hemant Vishnoi (Co-Founder) & Yadvendra Tyagi (Co-Founder)',
 'id': 147,
 'nalin_tech_fit_hook': 'Corporate purchasing cards, supplier payment batch settlement rails, and automated ERP '
                        'general ledger synchronization.',
 'outreach_status': 'To Contact',
 'website': 'https://enkash.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Mumbai'},
    {'career_email': 'yash@fylehq.com',
 'career_page_url': 'https://fylehq.com/careers',
 'company_name': 'Fyle',
 'domain_sector': 'Real-Time Expense Management & Credit Card Reconciliation AI',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $20M (Tiger Global, Steadview)',
 'hiring_decision_maker': 'Yashwanth Madhusudan (Co-Founder & CEO)',
 'id': 148,
 'nalin_tech_fit_hook': 'Real-time card feed reconciliation on Visa/Mastercard networks, receipt text OCR, and '
                        'automated expense policy checking.',
 'outreach_status': 'To Contact',
 'website': 'https://fylehq.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'nikunj@cutshort.io',
 'career_page_url': 'https://cutshort.io/careers',
 'company_name': 'Cutshort',
 'domain_sector': 'AI-Powered Tech Recruitment Platform & Direct Talent Match',
 'employee_count': '25-45',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Nikunj Verma (Founder & CEO)',
 'id': 149,
 'nalin_tech_fit_hook': 'Candidate skill graph matching, automated candidate response follow-up bots, and real-time '
                        'tech recruiting dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://cutshort.io',
 'work_model_location': 'Remote / Pune / Bangalore'},
    {'career_email': 'ayush@pesto.tech',
 'career_page_url': 'https://pesto.tech/careers',
 'company_name': 'Pesto Tech',
 'domain_sector': 'Remote Full-Stack Developer Upskilling & Global Placement',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $2M (Matrix Partners India)',
 'hiring_decision_maker': 'Ayush Jaiswal (Co-Founder & CEO)',
 'id': 150,
 'nalin_tech_fit_hook': 'Automated code assessment sandboxes, student curriculum progress dashboards in React, and '
                        'employer matching algorithms.',
 'outreach_status': 'To Contact',
 'website': 'https://pesto.tech',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Remote'},
    {'career_email': 'karthik@flexiple.com',
 'career_page_url': 'https://flexiple.com/careers',
 'company_name': 'Flexiple',
 'domain_sector': 'Vetted Freelance & Full-Time Tech Talent Matching Platform',
 'employee_count': '25-45',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Karthik Sridharan (Co-Founder & CEO)',
 'id': 151,
 'nalin_tech_fit_hook': 'Freelance tech assessment evaluation rubrics, automated job description parsing, and '
                        'client-talent matching portals.',
 'outreach_status': 'To Contact',
 'website': 'https://flexiple.com',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'kartik@springworks.in',
 'career_page_url': 'https://springworks.in/careers',
 'company_name': 'Springworks',
 'domain_sector': 'Work Culture & HR SaaS Tools (SpringVerify, Trivia)',
 'employee_count': '60-90',
 'funding_stage_investors': 'Bootstrapped & Highly Profitable',
 'hiring_decision_maker': 'Kartik Mandaville (Founder & CEO)',
 'id': 152,
 'nalin_tech_fit_hook': 'Background verification API integrations on government registries, employee engagement bots '
                        'on Slack, and fast Next.js dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://springworks.in',
 'work_model_location': 'Remote / Bangalore'},
    {'career_email': 'vijay@keka.com',
 'career_page_url': 'https://keka.com/careers',
 'company_name': 'Keka HR',
 'domain_sector': 'Modern HRMS, Payroll Automation & Performance Management',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series A $57M (Vista Point Advisors)',
 'hiring_decision_maker': 'Vijay Yalamanchili (CEO)',
 'id': 153,
 'nalin_tech_fit_hook': 'Complex payroll calculation rule engines, biometric attendance sync, and scalable '
                        'microservices architectures.',
 'outreach_status': 'To Contact',
 'website': 'https://keka.com',
 'work_model_location': 'Remote / Hyderabad / Bangalore'},
]
