# Batch 6: Companies 256 to 305 (AgriTech, E-Commerce Infrastructure, B2B Commerce, Logistics & CleanTech)

BATCH_6 = [
    {'career_email': 'varun@crofarm.com',
 'career_page_url': 'https://www.otipy.com/careers',
 'company_name': 'Otipy (Crofarm)',
 'domain_sector': 'Fresh Produce Supply Chain & Demand Forecasting AI',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $32M (WestBridge Capital, SIG Venture Capital)',
 'hiring_decision_maker': 'Varun Khurana (Founder & CEO)',
 'id': 256,
 'nalin_tech_fit_hook': 'Building predictive demand-forecasting microservices, inventory perishable decay models, and '
                        'high-throughput dispatch APIs in FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://www.otipy.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'mukul@agrim.app',
 'career_page_url': 'https://agrim.zohorecruit.in/jobs/Careers',
 'company_name': 'Agrim',
 'domain_sector': 'B2B Agri-Inputs Marketplace & Rural Commerce Platform',
 'employee_count': '65-90',
 'funding_stage_investors': 'Series A $10M (Kalaari Capital, Omnivore)',
 'hiring_decision_maker': 'Mukul Garg (Co-Founder & CEO)',
 'id': 257,
 'nalin_tech_fit_hook': 'Architecting B2B agri-dealer ordering portals, vernacular catalog search indexes, and '
                        'resilient offline-first mobile sync backends.',
 'outreach_status': 'To Contact',
 'website': 'https://agrim.app',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'pavan@aquaexchange.com',
 'career_page_url': 'https://aquaexchange.com',
 'company_name': 'AquaExchange',
 'domain_sector': 'Aquaculture IoT Telematics & Farm Automation Fintech',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $6M (Ocean 14 Capital, Endiya Partners)',
 'hiring_decision_maker': 'Pavan Kosaraju (Founder & CEO)',
 'id': 258,
 'nalin_tech_fit_hook': 'Streaming sensor telemetry from IoT aerators into time-series pipelines, power failover '
                        'alerts, and credit risk scoring algorithms.',
 'outreach_status': 'To Contact',
 'website': 'https://aquaexchange.com',
 'work_model_location': 'Remote / Vijayawada / Delhi-NCR friendly'},
    {'career_email': 'shrey@golocad.com',
 'career_page_url': 'https://golocad.com/careers/',
 'company_name': 'Locad',
 'domain_sector': 'Distributed E-Commerce Fulfillment & Cloud Logistics Engine',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series B $9M (Global Ventures, Reefknot Investments)',
 'hiring_decision_maker': 'Shrey Jain (Co-Founder & CTO)',
 'id': 259,
 'nalin_tech_fit_hook': 'Developing distributed multi-warehouse routing engines, carrier rate optimization '
                        'microservices, and live order tracking webhooks.',
 'outreach_status': 'To Contact',
 'website': 'https://golocad.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'rajul@increff.com',
 'career_page_url': 'https://www.increff.com/careers',
 'company_name': 'Increff',
 'domain_sector': 'Enterprise Inventory Optimization & Merchandising Intelligence',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series A $12M (TVS Capital Funds, Premji Invest)',
 'hiring_decision_maker': 'Rajul Jain (Co-Founder & CEO)',
 'id': 260,
 'nalin_tech_fit_hook': 'Building markdown pricing optimization models, warehouse SKU allocation graphs, and '
                        'low-latency inventory sync in FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://www.increff.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'ofresh@gopazo.com',
 'career_page_url': 'https://www.gopazo.com',
 'company_name': 'Pazo',
 'domain_sector': 'Visual Operational Intelligence & Deskless Workforce Workflows',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $1.2M (Prominent enterprise SaaS angels)',
 'hiring_decision_maker': 'Ofresh George (Founder & CEO)',
 'id': 261,
 'nalin_tech_fit_hook': 'Designing interactive store audit checklists, computer vision SOP verification modules, and '
                        'real-time incident resolution boards in Next.js.',
 'outreach_status': 'To Contact',
 'website': 'https://www.gopazo.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'tarun@singleinterface.com',
 'career_page_url': 'https://www.singleinterface.com/careers/',
 'company_name': 'SingleInterface',
 'domain_sector': 'Hyperlocal Retail Marketing & Storefront Automation Platform',
 'employee_count': '60-90',
 'funding_stage_investors': 'Series A $30M (Asia Partners, PayPal Ventures)',
 'hiring_decision_maker': 'Tarun Sobhani (Co-Founder & CEO)',
 'id': 262,
 'nalin_tech_fit_hook': 'Automating multi-location SEO schema injection, Google My Business review response AI agents, '
                        'and localized inventory feeds.',
 'outreach_status': 'To Contact',
 'website': 'https://www.singleinterface.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'sonakshi@bik.ai',
 'career_page_url': 'https://www.instahyre.com/jobs-at-bik-ai/',
 'company_name': 'Bik.ai',
 'domain_sector': 'Conversational Commerce & WhatsApp Marketing Automation',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $1.3M (Tsingyuan Ventures, prominent consumer angels)',
 'hiring_decision_maker': 'Sonakshi Nathani (Co-Founder & CEO)',
 'id': 263,
 'nalin_tech_fit_hook': 'Building WhatsApp commerce flow orchestrators, automated abandoned-cart recovery agents, and '
                        'high-concurrency webhook parsers.',
 'outreach_status': 'To Contact',
 'website': 'https://www.bik.ai',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'deepak@quicksell.co',
 'career_page_url': 'https://quicksell.co',
 'company_name': 'QuickSell',
 'domain_sector': 'Mobile Catalog Commerce & B2B Wholesale Ordering SaaS',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $2M (Info Edge Ventures, Silicon Valley angels)',
 'hiring_decision_maker': 'Deepak Bhagchandani (Founder & CEO)',
 'id': 264,
 'nalin_tech_fit_hook': 'Developing dynamic visual digital catalogs, multi-currency price tier engines, and real-time '
                        'WhatsApp order generation microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://quicksell.co',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR friendly'},
    {'career_email': 'ranjeet@flash.co',
 'career_page_url': 'https://flash.co',
 'company_name': 'Flash.co',
 'domain_sector': 'Smart Shopping Email & Post-Purchase AI Platform',
 'employee_count': '35-60',
 'funding_stage_investors': 'Series A $12.5M (Matrix Partners India / Z47, PeerCapital)',
 'hiring_decision_maker': 'Ranjeet Singh (Founder & CEO)',
 'id': 265,
 'nalin_tech_fit_hook': 'Building custom inbox parsing engines for e-commerce receipts, order delivery tracking '
                        'microservices, and personalized product recommendations.',
 'outreach_status': 'To Contact',
 'website': 'https://flash.co',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'angad@citymall.live',
 'career_page_url': 'https://citymall.live',
 'company_name': 'CityMall',
 'domain_sector': 'Social Commerce for Tier 2/3 Cities & Vernacular Ordering',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $75M (Norwest Venture Partners, Elevation Capital)',
 'hiring_decision_maker': 'Angad Kikla (Co-Founder & CEO)',
 'id': 266,
 'nalin_tech_fit_hook': 'Developing community leader distribution networks, vernacular voice search ordering, and '
                        'localized route planning for suburban clusters.',
 'outreach_status': 'To Contact',
 'website': 'https://citymall.live',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'alok@kikolive.com',
 'career_page_url': 'https://kiko.live',
 'company_name': 'Kiko Live',
 'domain_sector': 'Quick Commerce Enablement & ONDC Storefronts for Retailers',
 'employee_count': '20-45',
 'funding_stage_investors': 'Pre-Series A $1.5M (SOSV, Venture Catalysts)',
 'hiring_decision_maker': 'Alok Chawla (Co-Founder & CEO)',
 'id': 267,
 'nalin_tech_fit_hook': 'Integrating ONDC buyer and seller protocol adapters, sub-30-minute hyper-local delivery '
                        'dispatch, and kirana catalog digitization.',
 'outreach_status': 'To Contact',
 'website': 'https://kiko.live',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR friendly'},
    {'career_email': 'talha@biddano.com',
 'career_page_url': 'https://biddano.com',
 'company_name': 'Biddano',
 'domain_sector': 'B2B Healthcare & Pharma Logistics Fulfillment Platform',
 'employee_count': '45-75',
 'funding_stage_investors': 'Pre-Series A $2M (Gokul Rajaram, angel syndicates)',
 'hiring_decision_maker': 'Talha Shaikh (Co-Founder & CEO)',
 'id': 268,
 'nalin_tech_fit_hook': 'Optimizing temperature-controlled pharmaceutical dispatch algorithms, pharmacy order '
                        'aggregation, and dynamic multi-depot fleet allocation.',
 'outreach_status': 'To Contact',
 'website': 'https://biddano.com',
 'work_model_location': 'Remote / Pune / Delhi-NCR friendly'},
    {'career_email': 'gaurav@procol.in',
 'career_page_url': 'https://www.procol.ai/careers',
 'company_name': 'Procol',
 'domain_sector': 'Enterprise Procurement Management & Reverse Auction Platform',
 'employee_count': '40-70',
 'funding_stage_investors': 'Series A $6.5M (Blume Ventures, Peak XV Surge)',
 'hiring_decision_maker': 'Gaurav Baheti (Founder & CEO)',
 'id': 269,
 'nalin_tech_fit_hook': 'Building real-time English/Dutch reverse auction bidding engines, vendor proposal evaluation '
                        'RAG agents, and ERP contract connectors.',
 'outreach_status': 'To Contact',
 'website': 'https://www.procol.ai',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'amit@geniemode.com',
 'career_page_url': 'https://www.geniemode.com/careers',
 'company_name': 'Geniemode',
 'domain_sector': 'B2B Cross-Border Sourcing & Supply Chain for Home & Fashion',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $28M (Tiger Global, Info Edge Ventures)',
 'hiring_decision_maker': 'Amit Sharma (Co-Founder & CEO)',
 'id': 270,
 'nalin_tech_fit_hook': 'Designing supplier compliance verification pipelines, automated cross-border customs doc '
                        'generation, and international trade tracking.',
 'outreach_status': 'To Contact',
 'website': 'https://www.geniemode.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'siddharth@bijnis.com',
 'career_page_url': 'https://www.bijnis.com/careers',
 'company_name': 'Bijnis',
 'domain_sector': 'B2B Smart Manufacturing Platform for Footwear & Apparel',
 'employee_count': '65-95',
 'funding_stage_investors': 'Series B $30M (Westbridge, Info Edge, Matrix Partners)',
 'hiring_decision_maker': 'Siddharth Vij (Co-Founder & CEO)',
 'id': 271,
 'nalin_tech_fit_hook': 'Implementing factory production floor telemetry, material yield optimization algorithms, and '
                        'wholesale retailer re-ordering apps.',
 'outreach_status': 'To Contact',
 'website': 'https://www.bijnis.com',
 'work_model_location': 'Delhi-NCR (New Delhi) / Hybrid'},
    {'career_email': 'anubhav@rupifi.com',
 'career_page_url': 'https://www.rupifi.com/careers',
 'company_name': 'Rupifi',
 'domain_sector': 'B2B Embedded Lending & Commercial Credit Checkout APIs',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $25M (Bessemar Venture Partners, Tiger Global)',
 'hiring_decision_maker': 'Anubhav Jain (Co-Founder & CEO)',
 'id': 272,
 'nalin_tech_fit_hook': 'Developing real-time credit underwriting decision engines, merchant invoice factoring APIs, '
                        'and automated loan repayment webhooks.',
 'outreach_status': 'To Contact',
 'website': 'https://www.rupifi.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'prachi@payglocal.in',
 'career_page_url': 'https://payglocal.in',
 'company_name': 'PayGlocal',
 'domain_sector': 'Cross-Border Payment Gateway & Global Merchant Acquiring',
 'employee_count': '35-65',
 'funding_stage_investors': 'Series B $12M (Tiger Global, Peak XV Surge)',
 'hiring_decision_maker': 'Prachi Dharani (Co-Founder & CEO)',
 'id': 273,
 'nalin_tech_fit_hook': 'Building low-latency international transaction routing gateways, currency conversion hedging '
                        'engines, and PCI-DSS tokenization vaults.',
 'outreach_status': 'To Contact',
 'website': 'https://payglocal.in',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'vikul@bimaplan.com',
 'career_page_url': 'https://www.bimaplan.com',
 'company_name': 'Bimaplan',
 'domain_sector': 'Embedded Micro-Insurance Infrastructure & Financial APIs',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $3.5M (Y Combinator, 2am VC, Fin VC)',
 'hiring_decision_maker': 'Vikul Goyal (Founder & CEO)',
 'id': 274,
 'nalin_tech_fit_hook': 'Constructing modular insurance policy issuance APIs, automated claim processing pipelines, '
                        'and bite-sized sachet insurance checkout SDKs.',
 'outreach_status': 'To Contact',
 'website': 'https://www.bimaplan.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'shrayvats@finsire.com',
 'career_page_url': 'https://www.finsire.com',
 'company_name': 'Finsire',
 'domain_sector': 'Asset-Backed Lending Infrastructure & Collateral APIs',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.3M (DevX Venture Fund, angel investors)',
 'hiring_decision_maker': 'Shrayvats Swarup (Co-Founder & CEO)',
 'id': 275,
 'nalin_tech_fit_hook': 'Building real-time mutual fund and equity lien marking integrations with depositories '
                        '(NSDL/CDSL) and loan origination microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://www.finsire.com',
 'work_model_location': 'Remote / Chennai / Delhi-NCR friendly'},
    {'career_email': 'ajay@card91.io',
 'career_page_url': 'https://www.card91.io',
 'company_name': 'Card91',
 'domain_sector': 'Card Issuance-as-a-Service & Corporate Expense Infrastructure',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $2M (Infinity Ventures, prominent fintech angels)',
 'hiring_decision_maker': 'Ajay Pandey (Co-Founder & CEO)',
 'id': 276,
 'nalin_tech_fit_hook': 'Designing programmable virtual prepaid card controls, dynamic merchant spending limit rules, '
                        'and ISO 8583 payment switch integrations.',
 'outreach_status': 'To Contact',
 'website': 'https://www.card91.io',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'anirudh@climes.io',
 'career_page_url': 'https://climes.io',
 'company_name': 'Climes.io',
 'domain_sector': 'Climate Fintech & Carbon Calculation APIs for Checkout',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $1.2M (Peak XV Surge, Kalaari Capital)',
 'hiring_decision_maker': 'Anirudh Gupta (Co-Founder & CEO)',
 'id': 277,
 'nalin_tech_fit_hook': 'Integrating real-time flight and e-commerce cart carbon footprint estimators, API carbon '
                        'credit retirement ledgers, and consumer climate widgets.',
 'outreach_status': 'To Contact',
 'website': 'https://climes.io',
 'work_model_location': 'Delhi-NCR (Delhi/Gurgaon) / Hybrid'},
    {'career_email': 'hemant@loopify.world',
 'career_page_url': 'https://www.loopify.world',
 'company_name': 'Loopify',
 'domain_sector': 'Sustainable Packaging & Enterprise Carbon Accounting Platform',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1M (Indian angel networks & ESG funds)',
 'hiring_decision_maker': 'Hemant Chandwandkar (Co-Founder & CEO)',
 'id': 278,
 'nalin_tech_fit_hook': 'Creating plastic-free packaging lifecycle impact trackers, corporate ESG gift procurement '
                        'portals, and sustainability audit reporting backends.',
 'outreach_status': 'To Contact',
 'website': 'https://www.loopify.world',
 'work_model_location': 'Remote / Mumbai / Delhi-NCR friendly'},
    {'career_email': 'kamesh@breatheesg.com',
 'career_page_url': 'https://breatheesg.com',
 'company_name': 'Breathe ESG',
 'domain_sector': 'Enterprise ESG Reporting & Scope 1-3 Sustainability SaaS',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1M (Prominent institutional seed funds)',
 'hiring_decision_maker': 'Kamesh Ravichandran (Founder & CEO)',
 'id': 279,
 'nalin_tech_fit_hook': 'Architecting automated Scope 1, 2, and 3 emission ledger calculations, BRSR compliance report '
                        'generators, and supplier survey portals.',
 'outreach_status': 'To Contact',
 'website': 'https://breatheesg.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'chintan@ecolibrium.io',
 'career_page_url': 'https://www.ecolibrium.io/careers',
 'company_name': 'Ecolibrium',
 'domain_sector': 'Industrial Machine Intelligence & Predictive Maintenance AI',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $5M (Swordfish Investments, Infuse Ventures)',
 'hiring_decision_maker': 'Chintan Soni (Co-Founder & CEO)',
 'id': 280,
 'nalin_tech_fit_hook': 'Developing machine learning anomaly detection on high-frequency motor vibration data, thermal '
                        'sensor streams, and plant energy dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://www.ecolibrium.io',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'raunak@infinite-uptime.com',
 'career_page_url': 'https://www.infinite-uptime.com/careers/',
 'company_name': 'Infinite Uptime',
 'domain_sector': 'Digital Industrial Diagnostics & Vibration Analytics AI',
 'employee_count': '70-100',
 'funding_stage_investors': 'Series B $19M (Tiger Global, GSR Ventures)',
 'hiring_decision_maker': 'Raunak Bhinge (Founder & CEO)',
 'id': 281,
 'nalin_tech_fit_hook': 'Processing real-time triaxial vibration acoustic waveforms, early bearing fault detection '
                        'models, and edge inference gateways.',
 'outreach_status': 'To Contact',
 'website': 'https://www.infinite-uptime.com',
 'work_model_location': 'Remote / Pune / Delhi-NCR friendly'},
    {'career_email': 'siddharth@voltup.in',
 'career_page_url': 'https://voltup.in',
 'company_name': 'VoltUp',
 'domain_sector': 'EV Battery Swapping Infrastructure & Smart Mobility Network',
 'employee_count': '35-60',
 'funding_stage_investors': 'Seed $2M (AdvantEdge, prominent clean mobility angels)',
 'hiring_decision_maker': 'Siddharth Kabra (Co-Founder & CEO)',
 'id': 282,
 'nalin_tech_fit_hook': 'Developing battery swap station IoT telematics, state-of-health tracking algorithms, and '
                        'driver mobile app fast checkout.',
 'outreach_status': 'To Contact',
 'website': 'https://voltup.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'vikas@moeving.com',
 'career_page_url': 'https://moeving.com',
 'company_name': 'MoEVing',
 'domain_sector': 'Commercial Electric Fleet Telematics & Charging Management',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $5M (Beyond Capital, Stride Ventures)',
 'hiring_decision_maker': 'Vikas Mishra (Founder & CEO)',
 'id': 283,
 'nalin_tech_fit_hook': 'Building real-time EV fleet routing engines, battery state-of-charge prediction models, and '
                        'commercial charging hub reservation APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://moeving.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'akshit@statiq.in',
 'career_page_url': 'https://www.statiq.in',
 'company_name': 'Statiq',
 'domain_sector': 'EV Charging Station Network & IoT Charger Cloud Management',
 'employee_count': '45-75',
 'funding_stage_investors': 'Series A $25M (Shell Ventures, Y Combinator W20)',
 'hiring_decision_maker': 'Akshit Bansal (Co-Founder & CEO)',
 'id': 284,
 'nalin_tech_fit_hook': 'Implementing OCPP 1.6/2.0 protocol websocket handlers, automated charger billing gateways, '
                        'and highway smart route charging planners.',
 'outreach_status': 'To Contact',
 'website': 'https://www.statiq.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'aravind@riverind.com',
 'career_page_url': 'https://www.riverind.com/careers',
 'company_name': 'River Mobility',
 'domain_sector': 'Electric Utility Scooters & Connected IoT Vehicle Telematics',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $40M (Yamaha Motor, Mitsui & Co, Lowercarbon)',
 'hiring_decision_maker': 'Aravind Mani (Co-Founder & CEO)',
 'id': 285,
 'nalin_tech_fit_hook': 'Building scooter CAN-bus vehicle telematics data ingestion, over-the-air firmware update '
                        'pipelines, and mobile companion app microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://www.riverind.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'aman@kalagato.co',
 'career_page_url': 'https://kalagato.co',
 'company_name': 'KalaGato',
 'domain_sector': 'Automated Mobile App Ecosystem Intelligence & Consumer Insights AI',
 'employee_count': '20-35',
 'funding_stage_investors': 'Seed $4M (9Unicorns, Village Global)',
 'hiring_decision_maker': 'Aman Kumar (Founder & CEO)',
 'id': 286,
 'nalin_tech_fit_hook': 'Processing billions of anonymized mobile behavioral signals, automated consumer cohort '
                        'segmentation, and interactive Next.js data portals.',
 'outreach_status': 'To Contact',
 'website': 'https://kalagato.co',
 'work_model_location': 'Delhi-NCR (New Delhi) / Hybrid'},
    {'career_email': 'antony@tagalys.com',
 'career_page_url': 'https://tagalys.com',
 'company_name': 'Tagalys',
 'domain_sector': 'E-Commerce Visual Merchandising & Automated Product Sorting AI',
 'employee_count': '20-35',
 'funding_stage_investors': 'Pre-Series A $1M (Indian angel networks & seed funds)',
 'hiring_decision_maker': 'Antony Kattukaran (Founder & CEO)',
 'id': 287,
 'nalin_tech_fit_hook': 'Building real-time product conversion scoring algorithms, automated visual grid merchandiser '
                        'tools, and low-latency catalog search APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://tagalys.com',
 'work_model_location': 'Remote / Chennai / Delhi-NCR friendly'},
    {'career_email': 'madhav@zippee.delivery',
 'career_page_url': 'https://www.zippee.delivery',
 'company_name': 'Zippee',
 'domain_sector': 'Same-Day Delivery & Dark-Store Fulfillment for D2C Brands',
 'employee_count': '25-50',
 'funding_stage_investors': "Seed $2M (Haldiram's Family Office, prominent D2C angels)",
 'hiring_decision_maker': 'Madhav Kasturia (Founder & CEO)',
 'id': 288,
 'nalin_tech_fit_hook': 'Architecting micro-dark store inventory replenishment triggers, rider allocation graphs, and '
                        'sub-2-hour D2C delivery tracking APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://www.zippee.delivery',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Hybrid'},
    {'career_email': 'prateek@tartaninvestments.com',
 'career_page_url': 'https://www.tartaninvestments.com',
 'company_name': 'Tartan',
 'domain_sector': 'Income Verification & Real-Time Payroll Data Infrastructure',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $4.5M (500 Global, InfoEdge Ventures)',
 'hiring_decision_maker': 'Prateek Baseganni (Co-Founder & CEO)',
 'id': 289,
 'nalin_tech_fit_hook': 'Building secure payroll system scrapers, automated payslip OCR extraction pipelines, and '
                        'employment verification APIs for lenders.',
 'outreach_status': 'To Contact',
 'website': 'https://www.tartaninvestments.com',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Bangalore / Remote'},
    {'career_email': 'puneet@fold.money',
 'career_page_url': 'https://fold.money',
 'company_name': 'Fold',
 'domain_sector': 'AI Personal Finance & Intelligent Banking Canvas',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.5M (Prominent fintech founders & angels)',
 'hiring_decision_maker': 'Puneet Kumar (Founder & CEO)',
 'id': 290,
 'nalin_tech_fit_hook': 'Developing Account Aggregator financial telemetry parsers, LLM personal budget copilot '
                        'agents, and sleek Next.js financial canvas interfaces.',
 'outreach_status': 'To Contact',
 'website': 'https://fold.money',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'ramanathan@hyperface.co',
 'career_page_url': 'https://hyperface.co/careers',
 'company_name': 'Hyperface',
 'domain_sector': 'Card Issuance APIs & Financial Infrastructure Platform',
 'employee_count': '30-55',
 'funding_stage_investors': 'Seed $9M (3one4 Capital, Flipkart Ventures)',
 'hiring_decision_maker': 'Ramanathan RV (Co-Founder & CEO)',
 'id': 291,
 'nalin_tech_fit_hook': 'Architecting credit card lifecycle state machines, programmable transaction authorization '
                        'hooks, and core banking ledger connectors.',
 'outreach_status': 'To Contact',
 'website': 'https://hyperface.co',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'apurv@zenskar.com',
 'career_page_url': 'https://www.zenskar.com/careers',
 'company_name': 'Zenskar',
 'domain_sector': 'SaaS Billing & Usage-Based Pricing Calculation Engine',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $3.5M (Bessemer Venture Partners, Shine Capital)',
 'hiring_decision_maker': 'Apurv Bansal (Co-Founder & CEO)',
 'id': 292,
 'nalin_tech_fit_hook': 'Implementing real-time high-throughput meter event ingestion, complex contractual tier rating '
                        'engines, and automated invoice reconciliation.',
 'outreach_status': 'To Contact',
 'website': 'https://www.zenskar.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'siva@everstage.com',
 'career_page_url': 'https://www.everstage.com/careers',
 'company_name': 'Everstage',
 'domain_sector': 'Sales Commission Automation & Incentive Compensation SaaS',
 'employee_count': '70-95',
 'funding_stage_investors': 'Series B $30M (Eight Roads Ventures, 3one4 Capital)',
 'hiring_decision_maker': 'Siva Rajamani (Co-Founder & CEO)',
 'id': 293,
 'nalin_tech_fit_hook': 'Building dynamic sales commission calculation graphs, CRM quota attainment pipelines, and '
                        'interactive earnings gamification dashboards.',
 'outreach_status': 'To Contact',
 'website': 'https://www.everstage.com',
 'work_model_location': 'Fully Remote (India) / Chennai / Delhi-NCR friendly'},
    {'career_email': 'ankur@fibr.ai',
 'career_page_url': 'https://fibr.ai',
 'company_name': 'Fibr.ai',
 'domain_sector': 'Personalized AI Landing Pages & Ad Conversion Engine',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $1.8M (Accel, prominent marketing tech angels)',
 'hiring_decision_maker': 'Ankur Pandey (Co-Founder & CEO)',
 'id': 294,
 'nalin_tech_fit_hook': 'Developing dynamic Next.js edge landing page variants, real-time ad keyword audience '
                        'personalization, and automated A/B conversion optimizers.',
 'outreach_status': 'To Contact',
 'website': 'https://fibr.ai',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Remote'},
    {'career_email': 'ranjan@bureau.id',
 'career_page_url': 'https://www.bureau.id/careers',
 'company_name': 'Bureau.id',
 'domain_sector': 'AI Identity Verification & Fraud Intelligence Platform',
 'employee_count': '50-80',
 'funding_stage_investors': 'Series A $16M (Quona Capital, Commerce Ventures)',
 'hiring_decision_maker': 'Ranjan Reddy (Founder & CEO)',
 'id': 295,
 'nalin_tech_fit_hook': 'Building device fingerprinting fraud models, real-time behavioral bot detection '
                        'microservices, and automated KYC liveness checks.',
 'outreach_status': 'To Contact',
 'website': 'https://www.bureau.id',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'siddharth@syntizen.com',
 'career_page_url': 'https://syntizen.com',
 'company_name': 'Syntizen',
 'domain_sector': 'Aadhaar Biometrics & Digital Identity Verification Infrastructure',
 'employee_count': '30-55',
 'funding_stage_investors': 'Pre-Series A $1.5M (Mastercard, prominent fintech funds)',
 'hiring_decision_maker': 'Siddharth Kukatlapalli (Co-Founder & CEO)',
 'id': 296,
 'nalin_tech_fit_hook': 'Integrating UIDAI Aadhaar e-KYC and e-Sign microservices, facial video match algorithms, and '
                        'tamper-proof digital verification pipelines.',
 'outreach_status': 'To Contact',
 'website': 'https://syntizen.com',
 'work_model_location': 'Remote / Hyderabad / Delhi-NCR friendly'},
    {'career_email': 'manan@fidypay.com',
 'career_page_url': 'https://fidypay.com',
 'company_name': 'FidyPay',
 'domain_sector': 'Financial Inclusion APIs & Real-Time UPI Infrastructure',
 'employee_count': '25-45',
 'funding_stage_investors': 'Seed $1.5M (Prominent fintech angel networks)',
 'hiring_decision_maker': 'Manan Dixit (Founder & CEO)',
 'id': 297,
 'nalin_tech_fit_hook': 'Developing offline soundbox payment notifications, Bharat Bill Payment System (BBPS) '
                        'aggregator switches, and UPI AutoPay microservices.',
 'outreach_status': 'To Contact',
 'website': 'https://fidypay.com',
 'work_model_location': 'Remote / Indore / Delhi-NCR friendly'},
    {'career_email': 'saurabh@monsterapi.ai',
 'career_page_url': 'https://monsterapi.ai',
 'company_name': 'MonsterAPI',
 'domain_sector': 'Decentralized GPU Cloud & LLM Fine-Tuning Infrastructure',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $2M (Prominent AI compute angels)',
 'hiring_decision_maker': 'Saurabh Vij (Founder & CEO)',
 'id': 298,
 'nalin_tech_fit_hook': 'Optimizing LoRA/QLoRA fine-tuning job schedulers across distributed GPU clusters, vLLM '
                        'inference endpoints, and developer API telemetry.',
 'outreach_status': 'To Contact',
 'website': 'https://monsterapi.ai',
 'work_model_location': 'Delhi-NCR (Noida) / Fully Remote'},
    {'career_email': 'raj@avesha.io',
 'career_page_url': 'https://avesha.io',
 'company_name': 'Avesha',
 'domain_sector': 'AI Cloud Networking & GPU Workload Slicing Platform',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $4M (Prominent cloud infrastructure funds)',
 'hiring_decision_maker': 'Raj Nair (Founder & CEO)',
 'id': 299,
 'nalin_tech_fit_hook': 'Developing Kubernetes GPU resource scheduling plugins, multi-cloud model inference mesh '
                        'networking, and edge AI orchestration layers.',
 'outreach_status': 'To Contact',
 'website': 'https://avesha.io',
 'work_model_location': 'Fully Remote (India) / Bangalore'},
    {'career_email': 'gokul@cynlr.com',
 'career_page_url': 'https://www.cynlr.com',
 'company_name': 'Cynlr',
 'domain_sector': 'Visual Robot Intelligence & Object Manipulation Platform',
 'employee_count': '30-55',
 'funding_stage_investors': 'Pre-Series A $4.5M (Special Invest, InfoEdge Ventures)',
 'hiring_decision_maker': 'Gokul N A (Co-Founder & CEO)',
 'id': 300,
 'nalin_tech_fit_hook': 'Developing robotic visual depth perception algorithms, real-time kinematic arm motion '
                        'planning, and factory assembly pick-and-place pipelines.',
 'outreach_status': 'To Contact',
 'website': 'https://www.cynlr.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'kavita@voiro.com',
 'career_page_url': 'https://voiro.com/careers/',
 'company_name': 'Voiro',
 'domain_sector': 'AdTech Intelligence & Media Revenue Automation SaaS',
 'employee_count': '30-55',
 'funding_stage_investors': 'Pre-Series A $2.5M (1Crowd, prominent media angels)',
 'hiring_decision_maker': 'Kavita Shenoy (Founder & CEO)',
 'id': 301,
 'nalin_tech_fit_hook': 'Building OTT live ad inventory yield optimizers, program billing reconciliation pipelines, '
                        'and programmatic ad pacing analytics in FastAPI.',
 'outreach_status': 'To Contact',
 'website': 'https://voiro.com',
 'work_model_location': 'Remote / Bangalore / Delhi-NCR friendly'},
    {'career_email': 'ayush@spacenos.com',
 'career_page_url': 'https://spacenos.com',
 'company_name': 'Spacenos',
 'domain_sector': 'Autonomous AI FinTech & Conversational Banking Interfaces',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $1.5M (Institutional seed & financial angels)',
 'hiring_decision_maker': 'Ayush Singhal (Founder & CEO)',
 'id': 302,
 'nalin_tech_fit_hook': 'Developing conversational banking AI assistants, intent-routing LLM pipelines, and secure '
                        'transaction confirmation flows.',
 'outreach_status': 'To Contact',
 'website': 'https://spacenos.com',
 'work_model_location': 'Delhi-NCR (Noida) / Remote'},
    {'career_email': 'rishabh@credgenics.com',
 'career_page_url': 'https://www.credgenics.com/careers/',
 'company_name': 'Credgenics',
 'domain_sector': 'AI Debt Resolution & Legal Automation Platform',
 'employee_count': '75-100',
 'funding_stage_investors': 'Series B $50M (Westbridge Capital, Accel, Tanglin)',
 'hiring_decision_maker': 'Rishabh Goel (Co-Founder & CEO)',
 'id': 303,
 'nalin_tech_fit_hook': 'Building borrower repayment propensity predictive models, automated legal notice generation '
                        'workflows, and omnichannel communication queues.',
 'outreach_status': 'To Contact',
 'website': 'https://www.credgenics.com',
 'work_model_location': 'Delhi-NCR (Noida) / Hybrid Remote'},
    {'career_email': 'abhishek@blueskyhq.in',
 'career_page_url': 'https://blueskyhq.in',
 'company_name': 'BlueSky Analytics',
 'domain_sector': 'Climate Data Intelligence & Satellite AI Analytics',
 'employee_count': '20-40',
 'funding_stage_investors': 'Seed $2M (Beenext, Rainmatter Capital)',
 'hiring_decision_maker': 'Abhishek Agarwal (Co-Founder & CEO)',
 'id': 304,
 'nalin_tech_fit_hook': 'Processing satellite hyperspectral earth observation imagery for wild-fire and emission '
                        'tracking, geospatial indexing, and climate risk APIs.',
 'outreach_status': 'To Contact',
 'website': 'https://blueskyhq.in',
 'work_model_location': 'Delhi-NCR (Gurgaon) / Remote'},
    {'career_email': 'vimal@kalam.in',
 'career_page_url': 'https://kalam.in',
 'company_name': 'SuperKalam',
 'domain_sector': 'Personalized AI Mentor for Competitive Exams & EdTech',
 'employee_count': '15-30',
 'funding_stage_investors': 'Seed $2M (Y Combinator, prominent education angels)',
 'hiring_decision_maker': 'Vimal Singh Rathore (Co-Founder & CEO)',
 'id': 305,
 'nalin_tech_fit_hook': 'Building adaptive student mastery knowledge graphs, personalized UPSC test question '
                        'generation RAG pipelines, and conversational voice tutoring.',
 'outreach_status': 'To Contact',
 'website': 'https://kalam.in',
 'work_model_location': 'Delhi-NCR (Delhi/Noida) / Remote'},
]
