# Batch 1: Companies 1 to 51 (YC, Peak XV Surge, GenAI Infrastructure, LLMOps, Voice AI & Multi-Agent Platforms)

BATCH_1 = [
    {
        "id": 1,
        "company_name": "Portkey.ai",
        "website": "https://portkey.ai",
        "domain_sector": "AI Infrastructure / LLMOps",
        "employee_count": "15-25",
        "funding_stage_investors": "Seed $3M (Lightspeed, prominent angel investors)",
        "work_model_location": "Fully Remote (India) / Bangalore",
        "career_page_url": "https://portkey.ai/careers",
        "career_email": "rohit@portkey.ai",
        "hiring_decision_maker": "Rohit Agarwal (Co-Founder) & Ayush Garg (Co-Founder)",
        "nalin_tech_fit_hook": "Building low-latency Next.js observability dashboards + FastAPI gateways for LLM routing, evals, and agent fallback.",
        "outreach_status": "To Contact"
    },
    {
        "id": 2,
        "company_name": "Bolna.ai",
        "website": "https://bolna.ai",
        "domain_sector": "Voice AI & Conversational Agents",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2.5M (Y Combinator W24, General Catalyst)",
        "work_model_location": "Fully Remote (India) / Bangalore",
        "career_page_url": "https://bolna.ai/careers",
        "career_email": "abhinav@bolna.ai",
        "hiring_decision_maker": "Abhinav Pathak (Co-Founder) & Prateek Sachan (Co-Founder)",
        "nalin_tech_fit_hook": "Ultra low-latency WebSocket audio pipelines + streaming FastAPI backends for real-time multilingual voice agents.",
        "outreach_status": "To Contact"
    },
    {
        "id": 3,
        "company_name": "Mem0",
        "website": "https://mem0.ai",
        "domain_sector": "Memory Layer for LLMs & AI Agents",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $3.5M (Y Combinator S23, Peak XV Surge)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://mem0.ai/careers",
        "career_email": "taranjeet@mem0.ai",
        "hiring_decision_maker": "Taranjeet Singh (Co-Founder) & Deshraj Yadav (Co-Founder)",
        "nalin_tech_fit_hook": "Hybrid vector/graph retrieval pipelines + custom embedding sync for long-term memory in autonomous agent systems.",
        "outreach_status": "To Contact"
    },
    {
        "id": 4,
        "company_name": "TrueFoundry",
        "website": "https://truefoundry.com",
        "domain_sector": "LLM & ML Deployment Infrastructure",
        "employee_count": "30-50",
        "funding_stage_investors": "Series A $5.3M (Eniac Ventures, Peak XV)",
        "work_model_location": "Remote / Hybrid (Bangalore / Delhi-NCR)",
        "career_page_url": "https://truefoundry.com/careers",
        "career_email": "abhishek@truefoundry.com",
        "hiring_decision_maker": "Abhishek Choudhary (Co-Founder & CTO) & Nikunj Bajaj (CEO)",
        "nalin_tech_fit_hook": "Kubernetes-native model serving pipelines, vLLM acceleration gateways, and full-stack developer monitoring consoles.",
        "outreach_status": "To Contact"
    },
    {
        "id": 5,
        "company_name": "Sarvam AI",
        "website": "https://sarvam.ai",
        "domain_sector": "Indian Sovereign LLMs & Speech Models",
        "employee_count": "30-60",
        "funding_stage_investors": "Series A $41M (Lightspeed, Peak XV, Khosla)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://sarvam.ai/careers",
        "career_email": "vivek@sarvam.ai",
        "hiring_decision_maker": "Vivek Raghavan (Co-Founder) & Pratyush Kumar (Co-Founder)",
        "nalin_tech_fit_hook": "Indic language tokenizers, high-throughput fine-tuning pipelines, and Next.js enterprise evaluation playgrounds.",
        "outreach_status": "To Contact"
    },
    {
        "id": 6,
        "company_name": "Agno (formerly Phidata)",
        "website": "https://www.agno.com",
        "domain_sector": "Multi-Modal AI Agent Framework",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2.8M (Top-tier Silicon Valley & Indian VCs)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.agno.com/careers",
        "career_email": "ashpreet@agno.com",
        "hiring_decision_maker": "Ashpreet Bedi (Founder & CEO)",
        "nalin_tech_fit_hook": "Multi-modal agent orchestration with persistent memory, tool-calling APIs in FastAPI, and interactive agent control UIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 7,
        "company_name": "Respan (formerly Keywords AI)",
        "website": "https://www.respan.ai",
        "domain_sector": "LLM Observability & Evaluation Platform",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2.5M (Y Combinator W24)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.respan.ai/careers",
        "career_email": "frank@respan.ai",
        "hiring_decision_maker": "Frank Liu (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-throughput trace logging, real-time cost tracking dashboards in Next.js, and automated eval benchmarks for LLM outputs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 8,
        "company_name": "Composio",
        "website": "https://composio.dev",
        "domain_sector": "Tool Ecosystem for AI Agents",
        "employee_count": "15-30",
        "funding_stage_investors": "Series A $24M (Lightspeed, Elevation)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://composio.dev/careers",
        "career_email": "karan@composio.dev",
        "hiring_decision_maker": "Karan Vaidya (Co-Founder & CEO) & Soham Ganatra (Co-Founder)",
        "nalin_tech_fit_hook": "Building 100+ authenticated third-party tool integrations in Python/FastAPI and sub-second tool routing for agent frameworks.",
        "outreach_status": "To Contact"
    },
    {
        "id": 9,
        "company_name": "GigaML",
        "website": "https://gigaml.com",
        "domain_sector": "Enterprise On-Prem LLM Fine-Tuning",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $3.6M (Y Combinator S23, Nexus VP)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://gigaml.com/careers",
        "career_email": "varun@gigaml.com",
        "hiring_decision_maker": "Varun Godbole (Co-Founder & CEO) & Esha Manideep (Co-Founder)",
        "nalin_tech_fit_hook": "On-premise LoRA fine-tuning pipelines, quantization optimizations, and private enterprise LLM inference APIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 10,
        "company_name": "Plotline",
        "website": "https://plotline.so",
        "domain_sector": "In-App AI Personalization & Micro-Experiences",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $2.6M (Peak XV Surge)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://plotline.so/careers",
        "career_email": "shubham@plotline.so",
        "hiring_decision_maker": "Shubham Agarwal (Co-Founder) & Adit Kabra (Co-Founder)",
        "nalin_tech_fit_hook": "Lightweight client SDKs, dynamic JSON schema validation, and real-time nudges powered by user behavioral embeddings.",
        "outreach_status": "To Contact"
    },
    {
        "id": 11,
        "company_name": "Questera (Quest Labs)",
        "website": "https://questlabs.ai",
        "domain_sector": "AI Gamification & User Growth SDKs",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W24)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://questlabs.ai/careers",
        "career_email": "subhash@questlabs.ai",
        "hiring_decision_maker": "Subhash Choudhary (Founder & CEO)",
        "nalin_tech_fit_hook": "React/Next.js pre-built gamified UI components + edge-cached personalization rules for fast onboarding funnels.",
        "outreach_status": "To Contact"
    },
    {
        "id": 12,
        "company_name": "Beatoven.ai",
        "website": "https://beatoven.ai",
        "domain_sector": "Generative AI Music & Soundtrack Studio",
        "employee_count": "12-25",
        "funding_stage_investors": "Pre-Series A $1.3M (Capital A, Entrepreneur First)",
        "work_model_location": "Remote / Delhi-NCR / Bangalore",
        "career_page_url": "https://beatoven.ai/careers",
        "career_email": "mansoor@beatoven.ai",
        "hiring_decision_maker": "Mansoor Rahimatkhan (Co-Founder) & Gaurav Doiphode (Co-Founder)",
        "nalin_tech_fit_hook": "Web audio API multi-track timeline editing in React + diffusion-based audio stem generation backends.",
        "outreach_status": "To Contact"
    },
    {
        "id": 13,
        "company_name": "Murf.ai",
        "website": "https://murf.ai",
        "domain_sector": "AI Voice Generation & Audio Studio",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $10M (Matrix Partners, Elevation)",
        "work_model_location": "Fully Remote (India) / Delhi-NCR friendly",
        "career_page_url": "https://murf.ai/careers",
        "career_email": "ankur@murf.ai",
        "hiring_decision_maker": "Ankur Edkie (CEO) & Sneha Roy (Co-Founder)",
        "nalin_tech_fit_hook": "Web-based audio timeline editor in Next.js paired with deep learning voice generation pipelines and low-latency audio streaming.",
        "outreach_status": "To Contact"
    },
    {
        "id": 14,
        "company_name": "Vodex.ai",
        "website": "https://vodex.ai",
        "domain_sector": "GenAI Outbound Voice Agents for Enterprise",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $2M (Unicorn India Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://vodex.ai/careers",
        "career_email": "anshuman@vodex.ai",
        "hiring_decision_maker": "Anshuman Sen (Co-Founder & CEO) & Navneet Gupta (Co-Founder)",
        "nalin_tech_fit_hook": "Sub-500ms conversational turnarounds using streaming STT/TTS models, FastAPI orchestrators, and telephony SIP trunking.",
        "outreach_status": "To Contact"
    },
    {
        "id": 15,
        "company_name": "Floworks",
        "website": "https://floworks.ai",
        "domain_sector": "Autonomous AI Coworkers for Sales & CRM",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W23, SenseAI)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://floworks.ai/careers",
        "career_email": "sarthak@floworks.ai",
        "hiring_decision_maker": "Sarthak Shrivastava (Co-Founder) & Sudipta Biswas (Co-Founder)",
        "nalin_tech_fit_hook": "Al synchronization pipelines across Salesforce/HubSpot, natural language function dispatching, and agent feedback loops.",
        "outreach_status": "To Contact"
    },
    {
        "id": 16,
        "company_name": "Pipeshift",
        "website": "https://pipeshift.com",
        "domain_sector": "Fine-Tuning & Open-Weight LLM Infrastructure",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1.8M (Y Combinator W24, SenseAI)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://pipeshift.com/careers",
        "career_email": "arko@pipeshift.com",
        "hiring_decision_maker": "Arko Chattopadhyay (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Distributed fine-tuning jobs on cloud GPUs, automated loss tracking, and serverless LLM inference endpoints.",
        "outreach_status": "To Contact"
    },
    {
        "id": 17,
        "company_name": "LLUMO AI",
        "website": "https://llumo.ai",
        "domain_sector": "LLM Compression, Cost & Latency Optimization",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1.2M (SenseAI Ventures)",
        "work_model_location": "Remote / Delhi-NCR friendly",
        "career_page_url": "https://llumo.ai/careers",
        "career_email": "akshat@llumo.ai",
        "hiring_decision_maker": "Akshat Anand (CTO) & Shivam Gupta (CEO)",
        "nalin_tech_fit_hook": "Prompt compression algorithms, semantic token caching, and automated LLM quality evaluation benchmarks.",
        "outreach_status": "To Contact"
    },
    {
        "id": 18,
        "company_name": "Two AI (Sutra)",
        "website": "https://two.ai",
        "domain_sector": "Multilingual Frontier AI & GenAI Platform",
        "employee_count": "25-50",
        "funding_stage_investors": "Seed $20M (Jio, Smilegate)",
        "work_model_location": "Remote / Bangalore / Global",
        "career_page_url": "https://two.ai/careers",
        "career_email": "pranav@two.ai",
        "hiring_decision_maker": "Pranav Mistry (Founder & CEO)",
        "nalin_tech_fit_hook": "Multi-dialect LLM training datasets, real-time WebRTC avatar rendering, and high-performance multilingual inferencing.",
        "outreach_status": "To Contact"
    },
    {
        "id": 19,
        "company_name": "Slang Labs",
        "website": "https://slanglabs.in",
        "domain_sector": "In-App Multilingual Voice Assistant SDKs",
        "employee_count": "20-40",
        "funding_stage_investors": "Pre-Series A $1.5M (Google Assistant Fund)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://slanglabs.in/careers",
        "career_email": "kumar@slanglabs.in",
        "hiring_decision_maker": "Kumar Rangarajan (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "In-app voice copilots in React Native/Web, phonetic ASR corrections, and domain-specific intent classification models.",
        "outreach_status": "To Contact"
    },
    {
        "id": 20,
        "company_name": "Gnani.ai",
        "website": "https://gnani.ai",
        "domain_sector": "Conversational Speech AI & Indic Voice Automation",
        "employee_count": "45-75",
        "funding_stage_investors": "Series A $4M (Info Edge Ventures, Samsung)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://gnani.ai/careers",
        "career_email": "ganesh@gnani.ai",
        "hiring_decision_maker": "Ganesh Gopalan (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Building low-latency telephony voice bot gateways, acoustic model pipelines, and omnichannel analytics dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 21,
        "company_name": "CoRover.ai",
        "website": "https://corover.ai",
        "domain_sector": "Sovereign Conversational AI & BharatGPT",
        "employee_count": "45-75",
        "funding_stage_investors": "Series A $4M (Accenture, Indian Angel Network)",
        "work_model_location": "Delhi-NCR (Noida) / Bangalore",
        "career_page_url": "https://corover.ai/careers",
        "career_email": "ankush@corover.mobi",
        "hiring_decision_maker": "Ankush Sabharwal (Founder & CEO)",
        "nalin_tech_fit_hook": "BharatGPT enterprise multi-modal chatbot integrations, Indic speech recognition, and high-concurrency government portal bots.",
        "outreach_status": "To Contact"
    },
    {
        "id": 22,
        "company_name": "SiftHub",
        "website": "https://sifthub.io",
        "domain_sector": "AI-Powered Sales Knowledge & Search Platform",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $5.5M (Matrix Partners India)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://sifthub.io/careers",
        "career_email": "manhal@sifthub.io",
        "hiring_decision_maker": "Manhal Kamalakannan (Founder & CEO)",
        "nalin_tech_fit_hook": "Hybrid semantic search across Slack, Google Drive, and Notion with citation-grounded RAG generation in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 23,
        "company_name": "Segwise",
        "website": "https://segwise.ai",
        "domain_sector": "AI Observability & Anomaly Detection for Apps",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1.6M (Powerhouse Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://segwise.ai/careers",
        "career_email": "brijesh@segwise.ai",
        "hiring_decision_maker": "Brijesh Bharadwaj (Co-Founder) & Shobhit Gupta (Co-Founder)",
        "nalin_tech_fit_hook": "Automated funnel drop-off analysis using time-series anomaly detection, root-cause reasoning agents, and Next.js charts.",
        "outreach_status": "To Contact"
    },
    {
        "id": 24,
        "company_name": "Houseware",
        "website": "https://houseware.io",
        "domain_sector": "Composable Revenue Analytics & AI Workflows",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $2.1M (Tanglin Venture Partners)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://houseware.io/careers",
        "career_email": "divyansh@houseware.io",
        "hiring_decision_maker": "Divyansh Saini (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Warehouse-native semantic layers on Snowflake/BigQuery with natural language text-to-SQL generation and data apps.",
        "outreach_status": "To Contact"
    },
    {
        "id": 25,
        "company_name": "Chaos Genius",
        "website": "https://chaosgenius.io",
        "domain_sector": "Snowflake & Presto Data Warehouse Cost AI",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $3.3M (Elevation Capital, YC)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://chaosgenius.io/careers",
        "career_email": "preetish@chaosgenius.io",
        "hiring_decision_maker": "Preetish Kakkar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated query profiling, cost anomaly alerts, and query optimization recommendations for cloud data warehouses.",
        "outreach_status": "To Contact"
    },
    {
        "id": 26,
        "company_name": "Superalign",
        "website": "https://superalign.ai",
        "domain_sector": "Safety, Evaluation & Alignment for LLMs",
        "employee_count": "8-15",
        "funding_stage_investors": "Seed $1.5M (Peak XV Surge)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://superalign.ai/careers",
        "career_email": "team@superalign.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Automated red-teaming benchmarks, hallucination detection heuristics, and RLHF evaluation harnesses in FastAPI.",
        "outreach_status": "To Contact"
    },
    {
        "id": 27,
        "company_name": "Kroop AI",
        "website": "https://kroop.ai",
        "domain_sector": "Deepfake Detection & Synthetic Voice Forensics",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $500K (Indian Angel Network)",
        "work_model_location": "Remote / Delhi-NCR friendly",
        "career_page_url": "https://kroop.ai/careers",
        "career_email": "jyoti@kroop.ai",
        "hiring_decision_maker": "Dr. Jyoti Joshi (Founder & CEO)",
        "nalin_tech_fit_hook": "Audio-visual spoofing detection models, real-time video stream inspection, and automated forensic report generation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 28,
        "company_name": "Karya",
        "website": "https://karya.in",
        "domain_sector": "Ethical AI Training Data & Indic Speech Datasets",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $5M (Google.org, philanthropies)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://karya.in/careers",
        "career_email": "manu@karya.in",
        "hiring_decision_maker": "Manu Chopra (Founder & CEO)",
        "nalin_tech_fit_hook": "Offline-first mobile data collection apps with automated audio validation and worker micropayment ledgers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 29,
        "company_name": "HyperVerge",
        "website": "https://hyperverge.co",
        "domain_sector": "AI Computer Vision & Identity Verification",
        "employee_count": "60-90",
        "funding_stage_investors": "Series A $5M (NEA, Milliways Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://hyperverge.co/careers",
        "career_email": "kedar@hyperverge.co",
        "hiring_decision_maker": "Kedar Kulkarni (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Sub-second facial liveness detection, optical document parsing, and fraud prevention pipelines on edge devices.",
        "outreach_status": "To Contact"
    },
    {
        "id": 30,
        "company_name": "OnFinance AI",
        "website": "https://onfinance.ai",
        "domain_sector": "Financial LLM Copilot & Wealth Evals",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1M (Silverneedle Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://onfinance.ai/careers",
        "career_email": "kunal@onfinance.ai",
        "hiring_decision_maker": "Kunal Sangwan (Co-Founder) & Anuj Srivastava (Co-Founder)",
        "nalin_tech_fit_hook": "Financial document parsing (10-K, annual reports), domain-specific RAG with tabular reasoning, and compliance audits.",
        "outreach_status": "To Contact"
    },
    {
        "id": 31,
        "company_name": "Rowboat Labs",
        "website": "https://rowboatlabs.com",
        "domain_sector": "Local Knowledge Graph AI Coworker",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $2M (Y Combinator S24)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://rowboatlabs.com/careers",
        "career_email": "founders@rowboatlabs.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Local-first SQLite + vector database embeddings, automated email/meeting summarization, and offline knowledge sync.",
        "outreach_status": "To Contact"
    },
    {
        "id": 32,
        "company_name": "Ressl AI",
        "website": "https://ressl.ai",
        "domain_sector": "Autonomous Agent Benchmarking & Deployment",
        "employee_count": "6-12",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W25)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://ressl.ai/careers",
        "career_email": "founders@ressl.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-agent evaluation sandboxes, deterministic trajectory replay, and agent safety guardrails in Python/FastAPI.",
        "outreach_status": "To Contact"
    },
    {
        "id": 33,
        "company_name": "LimeChat",
        "website": "https://limechat.ai",
        "domain_sector": "Conversational E-Commerce & Level-3 AI Support",
        "employee_count": "35-65",
        "funding_stage_investors": "Seed $5.2M (Stellaris Venture Partners, Pi Ventures)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://limechat.ai/careers",
        "career_email": "nikhil@limechat.ai",
        "hiring_decision_maker": "Nikhil Gupta (Co-Founder & CEO) & Aniket Bajpai (Co-Founder)",
        "nalin_tech_fit_hook": "Autonomous conversational agents on WhatsApp with Shopify/WooCommerce catalog sync and intent routing pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 34,
        "company_name": "Scalenut",
        "website": "https://scalenut.com",
        "domain_sector": "AI SEO & Guided Content Generation Engine",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $3.1M (Saama Capital, Amit Singhal)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://scalenut.com/careers",
        "career_email": "mayank@scalenut.com",
        "hiring_decision_maker": "Mayank Jain (Co-Founder) & Gaurav Goyal (Co-Founder)",
        "nalin_tech_fit_hook": "Semantic NLP document scoring, SERP competitive analysis pipelines, and structured long-form content generation in Next.js.",
        "outreach_status": "To Contact"
    },
    {
        "id": 35,
        "company_name": "Kaagaz",
        "website": "https://kaagaz.app",
        "domain_sector": "AI Document Scanner, OCR & Workflow OS",
        "employee_count": "20-35",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W22, Pravega)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://kaagaz.app/careers",
        "career_email": "gaurav@kaagaz.app",
        "hiring_decision_maker": "Gaurav Shrishrimal (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Edge computer vision for edge distortion correction, multi-language OCR pipelines, and cloud document organization.",
        "outreach_status": "To Contact"
    },
    {
        "id": 36,
        "company_name": "SureBright",
        "website": "https://surebright.com",
        "domain_sector": "AI-Powered Embedded Warranty & Claim Engine",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2.5M (Y Combinator, angel syndicates)",
        "work_model_location": "Delhi-NCR (New Delhi) / Remote",
        "career_page_url": "https://surebright.com/careers",
        "career_email": "founders@surebright.com",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "Automated claims assessment with computer vision receipt parsing and high-throughput merchant checkout plugins.",
        "outreach_status": "To Contact"
    },
    {
        "id": 37,
        "company_name": "Waybill",
        "website": "https://waybill.com",
        "domain_sector": "AI Hardware Procurement & Supply Chain Agent",
        "employee_count": "8-15",
        "funding_stage_investors": "Seed $2M (Y Combinator S24)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Hybrid",
        "career_page_url": "https://waybill.com/careers",
        "career_email": "founders@waybill.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Automated BOM parsing from CAD files, supplier RFQ automation agents, and tariff classification pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 38,
        "company_name": "Tune AI",
        "website": "https://tune.app",
        "domain_sector": "Developer Framework for LLM Fine-Tuning & Orchestration",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1.5M (Accel Atoms)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://tune.app/careers",
        "career_email": "founders@tune.app",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "LLM fine-tuning APIs in Python, dataset formatting pipelines, and evaluation metrics dashboards for open-source weights.",
        "outreach_status": "To Contact"
    },
    {
        "id": 39,
        "company_name": "Arivihan",
        "website": "https://arivihan.com",
        "domain_sector": "AI-Based 1-on-1 Automated Video Tutoring",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Accel Atoms)",
        "work_model_location": "Remote / Delhi-NCR friendly",
        "career_page_url": "https://arivihan.com/careers",
        "career_email": "founders@arivihan.com",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "Interactive video streaming engines, real-time voice-driven doubt resolution, and adaptive curriculum pathways.",
        "outreach_status": "To Contact"
    },
    {
        "id": 40,
        "company_name": "K-Dense",
        "website": "https://kdense.ai",
        "domain_sector": "Autonomous Enterprise AI Agents & Workflow Automation",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2M (Accel Atoms AI Cohort, Google AIFF)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://kdense.ai/careers",
        "career_email": "founders@kdense.ai",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "Autonomous agent execution graphs, multi-step tool planners, and enterprise API authentication wrappers.",
        "outreach_status": "To Contact"
    },
    {
        "id": 41,
        "company_name": "Zaperon",
        "website": "https://zaperon.com",
        "domain_sector": "AI Identity Governance & Zero-Trust Cybersecurity",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1M (Inflection Point Ventures)",
        "work_model_location": "Delhi-NCR (New Delhi) / Hybrid",
        "career_page_url": "https://zaperon.com/careers",
        "career_email": "vineet@zaperon.com",
        "hiring_decision_maker": "Vineet Gupta (Co-Founder) & Sachin Aggarwal (Co-Founder)",
        "nalin_tech_fit_hook": "Passwordless biometric authentication, continuous user behavior anomaly detection, and access governance dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 42,
        "company_name": "Sherlocks.ai",
        "website": "https://sherlocks.ai",
        "domain_sector": "AI Agents for Automated Data Investigation & Root Cause",
        "employee_count": "8-15",
        "funding_stage_investors": "Seed $1.2M (SenseAI Ventures)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://sherlocks.ai/careers",
        "career_email": "founders@sherlocks.ai",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "Automated SQL metric anomaly analysis, hypothesis testing with LLM reasoning, and narrative report generation.",
        "outreach_status": "To Contact"
    },
    {
        "id": 43,
        "company_name": "CureSkin",
        "website": "https://cureskin.com",
        "domain_sector": "Computer Vision AI for Dermatology & Skincare",
        "employee_count": "40-70",
        "funding_stage_investors": "Series A $5M (JSW Ventures, Y Combinator)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://cureskin.com/careers",
        "career_email": "gopinath@cureskin.com",
        "hiring_decision_maker": "Gopinath Jaganmohan (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "High-accuracy skin lesion classification, treatment plan tracking algorithms, and mobile camera normalization pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 44,
        "company_name": "August AI",
        "website": "https://august.ai",
        "domain_sector": "AI Clinical Intelligence & Primary Care Assistance",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $3M (Peak XV Surge 12)",
        "work_model_location": "Remote / Bangalore / Delhi-NCR",
        "career_page_url": "https://august.ai/careers",
        "career_email": "anuruddh@august.ai",
        "hiring_decision_maker": "Anuruddh Mishra (Founder & CEO)",
        "nalin_tech_fit_hook": "Medical conversational reasoning with verified clinical citations, symptom triage workflows, and patient EHR sync.",
        "outreach_status": "To Contact"
    },
    {
        "id": 45,
        "company_name": "HiLoop",
        "website": "https://hiloop.ai",
        "domain_sector": "Infrastructure for Training & Evaluating Open-Weight Models",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge 12)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://hiloop.ai/careers",
        "career_email": "karan@hiloop.ai",
        "hiring_decision_maker": "Karan Brar (Co-Founder)",
        "nalin_tech_fit_hook": "Automated dataset cleaning pipelines, RLHF evaluation harnesses, and multi-model benchmark tracking dashboards.",
        "outreach_status": "To Contact"
    },
    {
        "id": 46,
        "company_name": "Reinforce Labs",
        "website": "https://reinforcelabs.ai",
        "domain_sector": "Automated Red-Teaming & Security Evals for Enterprise AI",
        "employee_count": "8-15",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge 12)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://reinforcelabs.ai/careers",
        "career_email": "anish@reinforcelabs.ai",
        "hiring_decision_maker": "Anish Das Sarma (Founder & CEO)",
        "nalin_tech_fit_hook": "Prompt injection vulnerability testing suites, adversarial attack generators, and enterprise AI firewall proxies.",
        "outreach_status": "To Contact"
    },
    {
        "id": 47,
        "company_name": "Kindling",
        "website": "https://kindling.ai",
        "domain_sector": "AI Storytelling & Strategic Communications Platform",
        "employee_count": "6-12",
        "funding_stage_investors": "Seed $1.8M (Peak XV Surge 12)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://kindling.ai/careers",
        "career_email": "sachin@kindling.ai",
        "hiring_decision_maker": "Sachin Shah (Co-Founder)",
        "nalin_tech_fit_hook": "Interactive narrative generators, tone-adaptive copy editors in Next.js, and multi-format media distribution pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "id": 48,
        "company_name": "Rosella",
        "website": "https://rosella.ai",
        "domain_sector": "AI-Native Commercial Insurance Brokerage Engine",
        "employee_count": "8-15",
        "funding_stage_investors": "Seed $2M (Peak XV Surge 12)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://rosella.ai/careers",
        "career_email": "founders@rosella.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Policy comparison semantic parsers, commercial risk exposure scoring, and carrier quote aggregator APIs.",
        "outreach_status": "To Contact"
    },
    {
        "id": 49,
        "company_name": "Tribe Money",
        "website": "https://tribemoney.ai",
        "domain_sector": "Autonomous AI Copilot for Personal Wealth & Cash Flow",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2M (Peak XV Surge 12)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://tribemoney.ai/careers",
        "career_email": "founders@tribemoney.ai",
        "hiring_decision_maker": "Founding Team",
        "nalin_tech_fit_hook": "Account aggregator bank statement parsing, categorized spend predictions, and conversational finance copilots.",
        "outreach_status": "To Contact"
    },
    {
        "id": 50,
        "company_name": "NeuroPixel.AI",
        "website": "https://neuropixel.ai",
        "domain_sector": "Computer Vision for Automated Apparel Cataloging",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $1.7M (Speciale Invest, Flipkart Leap)",
        "work_model_location": "Remote / Bangalore",
        "career_page_url": "https://neuropixel.ai/careers",
        "career_email": "charlie@neuropixel.ai",
        "hiring_decision_maker": "Charlie K (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-fidelity virtual apparel try-on diffusion models, 3D pose estimation, and automated photo background generators.",
        "outreach_status": "To Contact"
    },
    {
        "id": 51,
        "company_name": "Sketchnote",
        "website": "https://sketchnote.co",
        "domain_sector": "Collaborative AI Whiteboard & Real-Time Sync Canvas",
        "employee_count": "10-25",
        "funding_stage_investors": "Pre-Seed $500K (Accel Atoms)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://sketchnote.co/careers",
        "career_email": "dhruvak@sketchnote.co",
        "hiring_decision_maker": "Dhruvak Aggarwal (Founder & CEO)",
        "nalin_tech_fit_hook": "Infinite canvas rendering with React/Next.js, real-time multi-user WebSocket state sync, and AI diagramming.",
        "outreach_status": "To Contact"
    }
]
