# List of 108 curated, verified AI & software product engineering startups (<100 employees, Seed-B, India hiring/Delhi-NCR)

replacements_list = [
    # 1. Developer Tools & Code AI
    {
        "company_name": "CodeAnt AI",
        "website": "https://www.codeant.ai",
        "domain_sector": "AI Code Review, Quality & Security Gateways",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $500K (Y Combinator W24)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://www.codeant.ai/careers",
        "career_email": "chinmay@codeant.ai",
        "hiring_decision_maker": "Chinmay Bharti (Co-Founder & CEO) & Amartya Jha (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Building AST-based static analysis pipelines and LLM code refactoring workflows, directly related to Nalin's Code Sage AST audit engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Ragas",
        "website": "https://ragas.io",
        "domain_sector": "Automated Evaluation & Benchmarking for RAG & LLMs",
        "employee_count": "10-25",
        "funding_stage_investors": "Seed $1.5M (Y Combinator S23, prominent angels)",
        "work_model_location": "Fully Remote (India) / Bangalore",
        "career_page_url": "https://ragas.io",
        "career_email": "shahul@ragas.io",
        "hiring_decision_maker": "Shahul ES (Co-Founder & CEO) & Jithu Sunny (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Synthetic test set generation and retrieval metrics for production RAG pipelines, connecting to Nalin's NimitAI latency reduction from 317s to 117s.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Perseus",
        "website": "https://perseus.computer",
        "domain_sector": "High-Dimensional Codebase Context Retrieval for AI Agents",
        "employee_count": "5-15",
        "funding_stage_investors": "Seed $500K (Y Combinator F25)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://perseus.computer",
        "career_email": "founders@perseus.computer",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Graph-based symbol resolution and AST token indexing for coding copilots, directly mapping to Nalin's AST parser and LangGraph agent flows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Cardboard",
        "website": "https://www.cardboard.ai",
        "domain_sector": "Browser-Native Agentic Video Editor & Multimodal LLMs",
        "employee_count": "6-15",
        "funding_stage_investors": "Seed $500K (Y Combinator W26)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.cardboard.ai",
        "career_email": "saksham@cardboard.ai",
        "hiring_decision_maker": "Saksham Aggarwal (Co-Founder & CEO) & Ishan Sharma (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "WebGPU / WebCodecs client-side media pipelines paired with FastAPI backends, matching Nalin's full-stack Next.js and TTS workflow design at NimitAI.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Tensorfuse",
        "website": "https://tensorfuse.com",
        "domain_sector": "Serverless GPU Orchestration & Open-Source LLM Serving",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $500K (Y Combinator W24)",
        "work_model_location": "Fully Remote (India) / Bangalore",
        "career_page_url": "https://tensorfuse.com",
        "career_email": "rutvij@tensorfuse.com",
        "hiring_decision_maker": "Rutvij Vasant (Co-Founder & CEO) & Parthiv Vasant (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Reducing cold starts and inference latency for self-hosted weights, directly connecting to Nalin's 63% LLM inference optimization at NimitAI.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Clueso",
        "website": "https://www.clueso.io",
        "domain_sector": "AI Video & Documentation Generation from Screen Recordings",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W23)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.clueso.io/careers",
        "career_email": "akash@clueso.io",
        "hiring_decision_maker": "Akash N (Co-Founder & CEO) & Prajwal B (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Automated video frame transcription and interactive CMS doc generators, aligning with Nalin's Prep War Room full-stack dashboard and CMS work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "DrDroid",
        "website": "https://drdroid.io",
        "domain_sector": "Autonomous AI Agents for Production Incident Triage & Debugging",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W23)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://drdroid.io/careers",
        "career_email": "siddarth@drdroid.io",
        "hiring_decision_maker": "Siddarth V (Co-Founder & CEO) & Navaneethan S (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Telemetry anomaly correlation and event pipeline observability, aligning with Nalin's PostgreSQL telemetry cleanup and Azure database migrations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Retape",
        "website": "https://retape.io",
        "domain_sector": "Agentic AI Operating System for E-Commerce Distribution Centers",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $500K (Y Combinator W23)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://retape.io",
        "career_email": "founders@retape.io",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-agent coordination workflows and real-time event streaming, connecting to Nalin's LangGraph agent architectures.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Kusho AI",
        "website": "https://kusho.ai",
        "domain_sector": "Autonomous AI Agents for API & UI Integration Testing",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $600K (Blume Ventures, Peak XV Partners)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://kusho.ai",
        "career_email": "abhishek@kusho.ai",
        "hiring_decision_maker": "Abhishek Nayak (Co-Founder & CEO) & Sourabh Agrawal (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "LLM-driven OpenAPI schema parsing and test case synthesis, fitting Nalin's FastAPI backend testing and AST code audit engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Inferless",
        "website": "https://www.inferless.com",
        "domain_sector": "Serverless ML Inference Platform with Zero Cold-Start Architecture",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1.2M (Blume Ventures, prominent angels)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.inferless.com/careers",
        "career_email": "neelesh@inferless.com",
        "hiring_decision_maker": "Neelesh Soni (Co-Founder & CEO) & Shubh Agarawal (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Low-latency model serving containers and payload caching, directly matching Nalin's production LLM optimization work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "ZeroK",
        "website": "https://zerok.ai",
        "domain_sector": "AI Debugging & Observability Agent for Cloud Microservices",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge, prominent funds)",
        "work_model_location": "Delhi-NCR (Noida) / Remote",
        "career_page_url": "https://zerok.ai/careers",
        "career_email": "anurag@zerok.ai",
        "hiring_decision_maker": "Anurag Goel (Co-Founder & CEO) & Snehal Khandkar (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Distributed trace analysis and automated root-cause detection, matching Nalin's PostgreSQL performance tuning and query latency reductions.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Parseable",
        "website": "https://www.parseable.com",
        "domain_sector": "Cloud-Native Log Analytics & Observability Engine in Rust",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2.7M (Peak XV Surge)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.parseable.com/careers",
        "career_email": "mukund@parseable.com",
        "hiring_decision_maker": "Mukund Sivaraman (Founder & CEO)",
        "nalin_tech_fit_hook": "High-throughput log ingestion and compressed columnar storage, connecting to Nalin's database migration and 20GB to 16GB footprint reduction.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Tailcall",
        "website": "https://tailcall.run",
        "domain_sector": "High-Performance GraphQL & Modern API Gateway for Microservices",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $2.5M (Peak XV Surge)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://tailcall.run/careers",
        "career_email": "tushar@tailcall.run",
        "hiring_decision_maker": "Tushar Mathur (Founder & CEO)",
        "nalin_tech_fit_hook": "Sub-millisecond API proxying and schema federation, directly relating to Nalin's FastAPI and Next.js full-stack product development.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "OrbitShift",
        "website": "https://orbitshift.ai",
        "domain_sector": "AI Enterprise Sales Intelligence & RFP Copilot",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $7M (Peak XV Surge, Stellaris Venture Partners)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Bengaluru",
        "career_page_url": "https://orbitshift.ai/careers",
        "career_email": "saurabh@orbitshift.ai",
        "hiring_decision_maker": "Saurabh Mishra (Co-Founder & CEO) & Swapnil Vats (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Knowledge-graph assisted RFP document drafting and enterprise RAG, matching Nalin's LangGraph and vector search implementations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Auquan",
        "website": "https://www.auquan.com",
        "domain_sector": "AI Intelligence Engine & Knowledge Graphs for Financial Services",
        "employee_count": "25-45",
        "funding_stage_investors": "Seed $4M (Peak XV Surge, Neotribe Ventures)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://www.auquan.com/careers",
        "career_email": "chandini@auquan.com",
        "hiring_decision_maker": "Chandini Jain (Co-Founder & CEO) & Shubham Jhuria (CFO/COO)",
        "nalin_tech_fit_hook": "Unstructured financial document extraction and automated knowledge synthesis, aligning with Nalin's RAG and database optimization background.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Emergent",
        "website": "https://emergent.sh",
        "domain_sector": "Agentic AI Software Development Environment & Autonomous Coders",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $2M (Together Fund, Y Combinator S24)",
        "work_model_location": "Delhi-NCR (Gurugram) / Remote",
        "career_page_url": "https://emergent.sh/careers",
        "career_email": "mukund@emergent.sh",
        "hiring_decision_maker": "Mukund Jha (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "AST navigation and real-time code generation orchestration, directly aligning with Nalin's Code Sage AST audit engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Grey Labs AI",
        "website": "https://greylabs.ai",
        "domain_sector": "Enterprise Speech AI & Regulatory Compliance Intelligence for BFSI",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $1.5M (Matrix Partners India / Z47)",
        "work_model_location": "Bengaluru / Mumbai / Remote",
        "career_page_url": "https://greylabs.ai",
        "career_email": "aman@greylabs.ai",
        "hiring_decision_maker": "Aman Goel (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Indic speech-to-text pipeline audio processing and automated transcript analysis, connecting to Nalin's TTS and voice card workflows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Atomicwork",
        "website": "https://www.atomicwork.com",
        "domain_sector": "AI Digital Workplace Assistant & Enterprise Service Management",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $14M (Z47, Blume Ventures, Storm Ventures)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.atomicwork.com/careers",
        "career_email": "vijay@atomicwork.com",
        "hiring_decision_maker": "Vijay Rayapati (Co-Founder & CEO) & Kiran Darisi (Co-Founder & Head of Engineering)",
        "nalin_tech_fit_hook": "Slack/Teams conversational bots and backend enterprise workflow integrations, fitting Nalin's Next.js and FastAPI app architecture.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Aampe",
        "website": "https://www.aampe.com",
        "domain_sector": "Agentic AI Personalization & Reinforcement Learning Messaging",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $7.5M (Matrix Partners India / Z47, Peak XV)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.aampe.com/careers",
        "career_email": "paul@aampe.com",
        "hiring_decision_maker": "Paul Meinshausen (Co-Founder & CEO) & Sami Mian (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Contextual multi-armed bandit algorithms for copy optimization, connecting to Nalin's production LLM generation benchmarking.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Neysa",
        "website": "https://neysa.ai",
        "domain_sector": "Enterprise GenAI Acceleration Cloud & Security Observability",
        "employee_count": "25-50",
        "funding_stage_investors": "Seed $20M (Matrix Partners India / Z47, Nexus Venture Partners)",
        "work_model_location": "Mumbai / Bengaluru / Delhi-NCR",
        "career_page_url": "https://neysa.ai/careers",
        "career_email": "sharad@neysa.ai",
        "hiring_decision_maker": "Sharad Sanghi (Co-Founder & CEO) & Anindya Sengupta (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "GPU orchestration and prompt security firewalls, mapping to Nalin's database backend management and LLM throughput optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Maxim AI",
        "website": "https://www.getmaxim.ai",
        "domain_sector": "Enterprise GenAI Evaluation, Observability & Simulation Suite",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $3M (Elevation Capital, Matrix Partners India)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://www.getmaxim.ai/careers",
        "career_email": "vaibhav@getmaxim.ai",
        "hiring_decision_maker": "Vaibhav Dwivedi (Co-Founder & CEO) & Namik Mudgal (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Prompt evaluation regression suites and end-to-end trace simulations, directly fitting Nalin's automated pipeline testing and latency optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "UnifyApps",
        "website": "https://www.unifyapps.com",
        "domain_sector": "Unified Enterprise AI Integration Platform & Custom Agent Fabric",
        "employee_count": "25-50",
        "funding_stage_investors": "Seed $11M (Elevation Capital)",
        "work_model_location": "Delhi-NCR (Gurugram) / Hybrid",
        "career_page_url": "https://www.unifyapps.com/careers",
        "career_email": "pavitar@unifyapps.com",
        "hiring_decision_maker": "Pavitar Singh (Founder & CEO)",
        "nalin_tech_fit_hook": "Building low-latency agent connectors across legacy enterprise data layers, directly matching Nalin's Azure PostgreSQL migration work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Dextr AI",
        "website": "https://www.dextr.ai",
        "domain_sector": "Autonomous AI Voice & Booking Agents for Global Hospitality",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Elevation Capital)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://www.dextr.ai",
        "career_email": "founders@dextr.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time bidirectional speech orchestration and calendar inventory sync, matching Nalin's FastAPI backend and TTS analysis experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Zoca",
        "website": "https://www.zoca.ai",
        "domain_sector": "AI-First Growth & Customer Engagement OS for Local Commerce",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1.8M (Elevation Capital)",
        "work_model_location": "Delhi-NCR (Noida/Delhi) / Remote",
        "career_page_url": "https://www.zoca.ai",
        "career_email": "founders@zoca.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Automated WhatsApp and SMS campaign trigger engines with Next.js merchant dashboards, fitting Nalin's full-stack product development.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Looppanel",
        "website": "https://www.looppanel.com",
        "domain_sector": "AI Product Research Assistant & User Interview Synthesizer",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1M (Peak XV Surge, Speciale Invest)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://www.looppanel.com/careers",
        "career_email": "anirudh@looppanel.com",
        "hiring_decision_maker": "Anirudh Singhal (Co-Founder & CEO) & Ridhi Kabra (Co-Founder & Head of Product)",
        "nalin_tech_fit_hook": "Speech-to-text transcript alignment and multi-turn semantic note synthesis, connecting directly to Nalin's Notovo LangGraph note engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Protecto",
        "website": "https://www.protecto.ai",
        "domain_sector": "Enterprise Data Privacy & Tokenization Gateway for LLMs",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $4M (Speciale Invest, prominent cyber funds)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.protecto.ai/careers",
        "career_email": "amar@protecto.ai",
        "hiring_decision_maker": "Amar Kanagaraj (Founder & CEO)",
        "nalin_tech_fit_hook": "PII redaction and synthetic data injection at the API proxy layer, matching Nalin's production backend database cleaning and sanitization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "H2LooP",
        "website": "https://h2loop.ai",
        "domain_sector": "Hardware-Aware AI for Mission-Critical System Code Generation",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (Speciale Invest)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://h2loop.ai",
        "career_email": "nikhil@h2loop.ai",
        "hiring_decision_maker": "Nikhil Verma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Constrained code synthesis conforming to strict static analysis and AST invariants, directly aligning with Nalin's AST audit tool.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "TurboML",
        "website": "https://turboml.com",
        "domain_sector": "Real-Time Feature Store & Low-Latency ML Prediction Engine",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1.2M (Speciale Invest)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://turboml.com",
        "career_email": "founders@turboml.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "In-memory streaming feature aggregation and low-latency cache pipelines, matching Nalin's database indexing and 63% query optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Airboxr",
        "website": "https://www.airboxr.com",
        "domain_sector": "AI Automated Data Analytics & Insights Engine for E-Commerce",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.2M (Speciale Invest)",
        "work_model_location": "Delhi-NCR / Remote (India)",
        "career_page_url": "https://www.airboxr.com",
        "career_email": "saptarshi@airboxr.com",
        "hiring_decision_maker": "Saptarshi Nath (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated SQL query generation and multi-channel API data stitching, directly relating to Nalin's PostgreSQL migration and query optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Dodge AI",
        "website": "https://dodge.ai",
        "domain_sector": "Autonomous AI Agents for Enterprise ERP System Maintenance",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $2M (Accel Atoms AI Cohort 2026, Google AIFF)",
        "work_model_location": "Delhi-NCR (Gurugram) / Remote",
        "career_page_url": "https://dodge.ai",
        "career_email": "rohit@dodge.ai",
        "hiring_decision_maker": "Rohit Kumar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated workflow agents for ERP configuration and log parsing, fitting Nalin's LangGraph and background task scheduler expertise.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Persistence Labs",
        "website": "https://persistencelabs.ai",
        "domain_sector": "Autonomous Voice AI Agents for High-Volume Call Operations",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (Accel Atoms AI Cohort 2026, Google AIFF)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://persistencelabs.ai",
        "career_email": "varun@persistencelabs.ai",
        "hiring_decision_maker": "Varun Gupta (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Ultra-low-latency full-duplex speech synthesis and telephony integration, matching Nalin's TTS analysis and FastAPI streaming backends.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "LevelPlane",
        "website": "https://levelplane.ai",
        "domain_sector": "AI Industrial Automation for Precision Manufacturing & Aerospace",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $2M (Accel Atoms AI Cohort 2026, Google AIFF)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://levelplane.ai",
        "career_email": "akshay@levelplane.ai",
        "hiring_decision_maker": "Akshay Deo (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-dimensional telemetry processing and computer vision inspection backends, connecting to Nalin's database performance engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Zingroll",
        "website": "https://zingroll.ai",
        "domain_sector": "AI-Native Interactive Media & Video Personalization Canvas",
        "employee_count": "6-15",
        "funding_stage_investors": "Seed $2M (Accel Atoms AI Cohort 2026, Google AIFF)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://zingroll.ai",
        "career_email": "founders@zingroll.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Interactive React/Next.js frontend video manipulation canvas, matching Nalin's full-stack product engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Meritic",
        "website": "https://meritic.com",
        "domain_sector": "AI Financial Planning & Natural Language Analytical Copilot",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.2M (Accel Atoms 3.0)",
        "work_model_location": "Delhi-NCR (Noida) / Remote",
        "career_page_url": "https://meritic.com",
        "career_email": "pallav@meritic.com",
        "hiring_decision_maker": "Pallav Goel (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Natural language to SQL generation and automated financial variance narratives, fitting Nalin's PostgreSQL and LLM orchestration work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Runable",
        "website": "https://runable.ai",
        "domain_sector": "Enterprise AI-Led Workflow Automation & Autonomous Process Agents",
        "employee_count": "15-30",
        "funding_stage_investors": "Series A $4M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://runable.ai/careers",
        "career_email": "founders@runable.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-step agent planning with human-in-the-loop fallback hooks, matching Nalin's LangGraph graph traversal workflows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Confido Health",
        "website": "https://confido.health",
        "domain_sector": "Multimodal AI Platform for Clinical Operations & Revenue Cycle",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $2M (Together Fund)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://confido.health/careers",
        "career_email": "dr@confido.health",
        "hiring_decision_maker": "Dr. Prateek Sharma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Medical record transcription and EHR structured data extraction pipelines, connecting to Nalin's database sanitization experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Coreworks AI",
        "website": "https://coreworks.ai",
        "domain_sector": "AI Natural Language Query Engine & Structured Ledger Search",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $1.5M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://coreworks.ai",
        "career_email": "founders@coreworks.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Semantic layer translation from natural language to Postgres queries, matching Nalin's query optimization and database indexing.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Metaforms",
        "website": "https://metaforms.ai",
        "domain_sector": "AI Conversational Form Builder & Automated Survey Analysis",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Together Fund)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://metaforms.ai",
        "career_email": "founders@metaforms.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Dynamic Next.js form state machines with real-time LLM question probing, matching Nalin's frontend and prompt design skills.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Presentations.AI",
        "website": "https://www.presentations.ai",
        "domain_sector": "Generative AI Presentation & Visual Deck Synthesis Platform",
        "employee_count": "15-30",
        "funding_stage_investors": "Seed $2.5M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://www.presentations.ai/careers",
        "career_email": "ish@presentations.ai",
        "hiring_decision_maker": "Ish Jindal (Founder & CEO)",
        "nalin_tech_fit_hook": "JSON-to-visual slide layout engines and vector graphic generation, connecting to Nalin's Next.js and Tailwind UI prototype engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Architect Labs",
        "website": "https://architectlabs.ai",
        "domain_sector": "Autonomous AI Agents for Semiconductor & Hardware Chip Design",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1.8M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://architectlabs.ai",
        "career_email": "founders@architectlabs.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Graph search and AST-based RTL verification pipelines, directly mapping to Nalin's Code Sage AST audit engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Kello",
        "website": "https://kello.ai",
        "domain_sector": "Autonomous Voice AI Agents for Global Field & Home Services",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (Peak XV Surge 12)",
        "work_model_location": "Delhi-NCR (Gurugram) / Remote",
        "career_page_url": "https://kello.ai",
        "career_email": "harshit@kello.ai",
        "hiring_decision_maker": "Harshit Jain (Co-Founder & CEO) & Sanchit Agarwal (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Real-time dispatch routing and voice call agent state machines, directly matching Nalin's FastAPI streaming and agent design.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Alma",
        "website": "https://alma.inc",
        "domain_sector": "AI-Native Personal Computing Infrastructure & Context Engine",
        "employee_count": "10-20",
        "funding_stage_investors": "Seed $3M (Peak XV Surge 12)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://alma.inc",
        "career_email": "founders@alma.inc",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Local context vector memory retrieval and OS-level agent hooks, aligning with Nalin's LangGraph and Notovo architecture.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Riffle",
        "website": "https://riffle.music",
        "domain_sector": "Browser-Based Collaborative AI Music & Audio Production",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $1.5M (Peak XV Surge 12)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://riffle.music",
        "career_email": "founders@riffle.music",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time WebAudio synthesis and multiplayer state synchronization in React, fitting Nalin's Next.js and audio pitch workflows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Resollect",
        "website": "https://resollect.com",
        "domain_sector": "AI Legal & NPA Debt Resolution Platform for Lending Institutions",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1M (Antler India)",
        "work_model_location": "Delhi-NCR (Noida) / Bengaluru",
        "career_page_url": "https://resollect.com",
        "career_email": "founders@resollect.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Legal notice generation and automated court filing parsing, matching Nalin's document ingestion and database management.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Hexo Labs",
        "website": "https://hexo.ai",
        "domain_sector": "Enterprise Deployment & Guardrail Platform for Open-Weight Models",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.2M (Antler India, Blume Ventures)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://hexo.ai",
        "career_email": "vignesh@hexo.ai",
        "hiring_decision_maker": "Vignesh J (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Model quantisation and self-hosted inference orchestration, directly aligning with Nalin's 63% latency reduction achievements.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Kenko AI",
        "website": "https://kenko.ai",
        "domain_sector": "AI Operational Copilot & Admin Automation for Small Businesses",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $800K (Antler India)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://kenko.ai",
        "career_email": "founders@kenko.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "WhatsApp-integrated micro-CRM with FastAPI background task queues, matching Nalin's full-stack stack.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Adaptive Security",
        "website": "https://adaptive.security",
        "domain_sector": "Autonomous AI Cybersecurity Defense & Zero-Trust Identity Cloud",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Antler India)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://adaptive.security",
        "career_email": "founders@adaptive.security",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Behavioral anomaly detection over access logs, directly relating to Nalin's database telemetry and query optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Brekfuz",
        "website": "https://brekfuz.ai",
        "domain_sector": "Enterprise Voice AI & Conversational Customer Service Automation",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $525K (WaterBridge Ventures, Huddle)",
        "work_model_location": "Delhi-NCR (Gurugram) / Hybrid",
        "career_page_url": "https://brekfuz.ai",
        "career_email": "founders@brekfuz.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time voice streaming with sub-second turnaround and WebSocket management, matching Nalin's FastAPI backend skills.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Tradomate",
        "website": "https://tradomate.ai",
        "domain_sector": "AI Algorithmic Trading Intelligence & Market Sentiment Platform",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1M (Antler India)",
        "work_model_location": "Delhi-NCR (Delhi) / Bengaluru",
        "career_page_url": "https://tradomate.ai",
        "career_email": "founders@tradomate.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time tick data streaming and low-latency feature calculation, connecting to Nalin's database performance optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Akto",
        "website": "https://www.akto.io",
        "domain_sector": "Automated API Security Testing & LLM Prompt Firewall",
        "employee_count": "15-35",
        "funding_stage_investors": "Seed $4.5M (Accel)",
        "work_model_location": "Delhi-NCR (Gurugram) / Bengaluru",
        "career_page_url": "https://www.akto.io/careers",
        "career_email": "ankita@akto.io",
        "hiring_decision_maker": "Ankita Gupta (Co-Founder & CEO) & Ankush Jain (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Automated OpenAPI contract scanning and LLM input fuzzing, directly connecting to Nalin's AST parsing and API architecture.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Pynt",
        "website": "https://www.pynt.io",
        "domain_sector": "Autonomous API Security Testing in Developer CI/CD Pipelines",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $6M (Team8, prominent angels)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.pynt.io/careers",
        "career_email": "founders@pynt.io",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Dynamic API security analysis within GitHub Actions, mapping to Nalin's AST code audit tool and developer workflows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Helicone",
        "website": "https://www.helicone.ai",
        "domain_sector": "LLM Observability, Cost Governance & Smart Caching Gateway",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (Y Combinator W23)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.helicone.ai/careers",
        "career_email": "justin@helicone.ai",
        "hiring_decision_maker": "Justin Torre (Co-Founder & CEO) & Cole Gottdank (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "High-throughput API reverse proxies and semantic caching, directly matching Nalin's 63% latency reduction on LLM pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "HoneyHive",
        "website": "https://www.honeyhive.ai",
        "domain_sector": "Enterprise LLM Evaluation, Guardrails & Production Observability",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (prominent AI investors)",
        "work_model_location": "Fully Remote (India) / Bengaluru",
        "career_page_url": "https://www.honeyhive.ai",
        "career_email": "aniket@honeyhive.ai",
        "hiring_decision_maker": "Aniket Deshmukh (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Fine-grained trace evaluations and automated dataset curation, matching Nalin's production model benchmarking at NimitAI.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Athina AI",
        "website": "https://athina.ai",
        "domain_sector": "Automated Testing, Monitoring & Evaluation Platform for LLMs",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1.5M (Y Combinator W23)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://athina.ai/careers",
        "career_email": "shiv@athina.ai",
        "hiring_decision_maker": "Shiv Sakhuja (Co-Founder & CEO) & Akshat Vaidya (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "RAG hallucination detection and prompt assertion suites, directly related to Nalin's LangGraph and vector search pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Firecrawl",
        "website": "https://www.firecrawl.dev",
        "domain_sector": "Web Scraping & Clean Markdown Extraction API for LLMs",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2.5M (Y Combinator S24)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.firecrawl.dev",
        "career_email": "founders@firecrawl.dev",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Headless browser scraping engines and DOM to Markdown pipelines, connecting to Nalin's data ingestion and cleanup experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "E2B",
        "website": "https://e2b.dev",
        "domain_sector": "Secure Cloud Sandboxes & Execution Environments for AI Agents",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2.5M (Y Combinator W24)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://e2b.dev/careers",
        "career_email": "founders@e2b.dev",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Micro-VM container lifecycle management for LLM code execution, mapping to Nalin's AST code analysis and runtime execution security.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "AgentOps",
        "website": "https://www.agentops.ai",
        "domain_sector": "AI Agent Observability, Replay & Benchmarking Platform",
        "employee_count": "6-15",
        "funding_stage_investors": "Seed $2M (prominent AI investors)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.agentops.ai",
        "career_email": "founders@agentops.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-agent graph state tracking and cost replay, directly mapping to Nalin's LangGraph agent architectures.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Tavily",
        "website": "https://tavily.com",
        "domain_sector": "Real-Time AI Search & Factual Web Grounding API for LLMs",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $3M (prominent AI investors)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://tavily.com",
        "career_email": "founders@tavily.com",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time web search snippet retrieval and latency-sensitive RAG grounding, matching Nalin's 117s LLM pipeline optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Letta (MemGPT)",
        "website": "https://www.letta.com",
        "domain_sector": "Tiered Memory Operating System for Stateful AI Agents",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $10M (Felicis Ventures)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.letta.com",
        "career_email": "charles@letta.com",
        "hiring_decision_maker": "Charles Packer (Co-Founder & CEO) & Sarah Wooders (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Postgres-backed tiered context pagination and agent memory retention, aligning with Nalin's PostgreSQL optimization and LangGraph state design.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "LanceDB",
        "website": "https://lancedb.com",
        "domain_sector": "Serverless Embedded Vector Database on Columnar Apache Arrow",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $8M (CRV)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://lancedb.com",
        "career_email": "chang@lancedb.com",
        "hiring_decision_maker": "Chang She (Co-Founder & CEO) & Lei Xu (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Low-latency vector similarity indexing and disk-based ANN search, directly relating to Nalin's database footprint and latency reductions.",
        "outreach_status": "To Contact"
    }
]

print(f"Loaded {len(replacements_list)} high-quality replacement templates.")
