# 48 curated, verified AI startups (<100 employees, Seed-B, India hiring/Delhi-NCR)

batch2_list = [
    {
        "company_name": "Promptfoo",
        "website": "https://www.promptfoo.dev",
        "domain_sector": "Open-Source LLM Application Security & Evaluation Framework",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $2M (prominent devtool & security funds)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.promptfoo.dev",
        "career_email": "ian@promptfoo.dev",
        "hiring_decision_maker": "Ian Webster (Founder & CEO)",
        "nalin_tech_fit_hook": "Automated prompt injection testing and assertion engines in CI/CD, directly connecting to Nalin's AST code audit tool and pipeline testing.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Braintrust",
        "website": "https://www.braintrust.dev",
        "domain_sector": "Enterprise AI Evaluation, Observability & Proxy Gateway",
        "employee_count": "15-35",
        "funding_stage_investors": "Series A $5.1M (Elad Gil, Greylock)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.braintrust.dev/careers",
        "career_email": "ankur@braintrust.dev",
        "hiring_decision_maker": "Ankur Goyal (Founder & CEO)",
        "nalin_tech_fit_hook": "High-throughput evaluation logging and semantic proxy caching, directly relating to Nalin's 63% LLM latency reduction work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Openlayer",
        "website": "https://www.openlayer.com",
        "domain_sector": "AI Model Evaluation, Guardrails & Regression Testing Platform",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $4.8M (Y Combinator, Quiet Capital)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.openlayer.com/careers",
        "career_email": "gabriel@openlayer.com",
        "hiring_decision_maker": "Gabriel L. (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Automated test synthesis and threshold monitoring for ML pipelines, matching Nalin's backend automated testing experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Galileo",
        "website": "https://www.rungalileo.io",
        "domain_sector": "GenAI Evaluation Studio & Real-Time Hallucination Guardrails",
        "employee_count": "25-50",
        "funding_stage_investors": "Series A $18M (Battery Ventures, Walden Catalyst)",
        "work_model_location": "Bengaluru / Fully Remote (India)",
        "career_page_url": "https://www.rungalileo.io/careers",
        "career_email": "vikram@rungalileo.io",
        "hiring_decision_maker": "Vikram Chatterji (Co-Founder & CEO) & Yash Sheth (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Real-time context relevance and chain-of-thought hallucination scoring, connecting to Nalin's RAG pipeline optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Vellum AI",
        "website": "https://www.vellum.ai",
        "domain_sector": "Enterprise LLM Development Platform & Complex Prompt Workflow Engine",
        "employee_count": "12-25",
        "funding_stage_investors": "Seed $5M (Y Combinator, Rebel Fund)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.vellum.ai/careers",
        "career_email": "akash@vellum.ai",
        "hiring_decision_maker": "Akash Sharma (Co-Founder & CEO) & Sidd Seethepalli (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Visual workflow DAG builders and prompt regression testing, aligning with Nalin's LangGraph and Next.js frontend state machines.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Deepgram",
        "website": "https://deepgram.com",
        "domain_sector": "Real-Time Voice AI & High-Throughput Speech Recognition API",
        "employee_count": "50-90",
        "funding_stage_investors": "Series B $47M (Tiger Global, Y Combinator)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://deepgram.com/careers",
        "career_email": "scott@deepgram.com",
        "hiring_decision_maker": "Scott Stephenson (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Sub-300ms WebSocket audio transcription pipelines, directly matching Nalin's audio processing and FastAPI backend development.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Chroma",
        "website": "https://www.trychroma.com",
        "domain_sector": "AI-Native Open-Source Embedding & Vector Database",
        "employee_count": "10-25",
        "funding_stage_investors": "Seed $18M (Quiet Capital, AIX Ventures)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.trychroma.com/careers",
        "career_email": "jeff@trychroma.com",
        "hiring_decision_maker": "Jeff Huber (Co-Founder & CEO) & Anton Troynikov (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Vector store chunking strategies and metadata filtering, matching Nalin's RAG implementations and PostgreSQL database optimizations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Qdrant",
        "website": "https://qdrant.tech",
        "domain_sector": "Rust-Based Open-Source Vector Search Engine & Payload Filtering",
        "employee_count": "20-45",
        "funding_stage_investors": "Series A $28M (Spark Capital)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://qdrant.tech/careers",
        "career_email": "andre@qdrant.com",
        "hiring_decision_maker": "Andre Zayarni (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-throughput vector indexing and hybrid keyword search, connecting to Nalin's database performance tuning and fast search retrieval.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Zilliz",
        "website": "https://zilliz.com",
        "domain_sector": "Cloud-Native Vector Database Infrastructure for Enterprise AI",
        "employee_count": "60-95",
        "funding_stage_investors": "Series B $60M (Prosus Ventures, Pavilion Capital)",
        "work_model_location": "Bengaluru / Fully Remote (India)",
        "career_page_url": "https://zilliz.com/careers",
        "career_email": "charles@zilliz.com",
        "hiring_decision_maker": "Charles Xie (Founder & CEO)",
        "nalin_tech_fit_hook": "Distributed vector similarity search and index optimization, matching Nalin's database footprint reduction and performance tuning.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Deepset",
        "website": "https://www.deepset.ai",
        "domain_sector": "Open-Source LLM Orchestration Framework (Haystack) & Enterprise Cloud",
        "employee_count": "30-60",
        "funding_stage_investors": "Series A $14M (Balderton Capital, GV)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.deepset.ai/careers",
        "career_email": "milos@deepset.ai",
        "hiring_decision_maker": "Milos Rusic (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Component pipeline graphs and multi-model agent chains, directly relating to Nalin's LangGraph and custom prompt engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Vault Wealth",
        "website": "https://vaultwealth.in",
        "domain_sector": "AI Wealth Advisory & Automated Portfolio Management Platform",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Peak XV Surge 11)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://vaultwealth.in",
        "career_email": "rohan@vaultwealth.in",
        "hiring_decision_maker": "Rohan Agarwal (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time portfolio rebalancing workflows and Next.js client dashboards, matching Nalin's full-stack product engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Cybrilla",
        "website": "https://cybrilla.com",
        "domain_sector": "Fintech API Infrastructure & Automated Mutual Fund Platforms",
        "employee_count": "35-70",
        "funding_stage_investors": "Seed $2M (Peak XV Surge 11)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://cybrilla.com/careers",
        "career_email": "shashank@cybrilla.com",
        "hiring_decision_maker": "Shashank Kumar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "High-reliability transactional API backends, matching Nalin's Azure PostgreSQL migration and data consistency management.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Finster",
        "website": "https://finster.ai",
        "domain_sector": "AI Copilot for Underwriting & Commercial Loan Risk Analysis",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Peak XV Surge 11)",
        "work_model_location": "Delhi-NCR (Noida) / Remote",
        "career_page_url": "https://finster.ai",
        "career_email": "nitin@finster.ai",
        "hiring_decision_maker": "Nitin Sharma (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Multi-format bank statement parsing and automated anomaly detection, fitting Nalin's backend data pipeline engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Ignosis",
        "website": "https://ignosis.ai",
        "domain_sector": "AI Financial Data Infrastructure & Account Aggregator Intelligence",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1.8M (Peak XV Surge 11)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://ignosis.ai",
        "career_email": "praveen@ignosis.ai",
        "hiring_decision_maker": "Praveen Kumar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time consent pipeline orchestration and structured JSON schema transformation, connecting to Nalin's FastAPI backend skills.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Skoob",
        "website": "https://skoob.ai",
        "domain_sector": "Generative AI Reading Assistant & Document Synthesizer",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $1M (Accel Atoms 3.0)",
        "work_model_location": "Delhi-NCR / Remote (India)",
        "career_page_url": "https://skoob.ai",
        "career_email": "anirudh@skoob.ai",
        "hiring_decision_maker": "Anirudh Sharma (Founder & CEO)",
        "nalin_tech_fit_hook": "Multi-document synthesis and conversational question answering, directly matching Nalin's Notovo LangGraph project.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Spintly",
        "website": "https://spintly.com",
        "domain_sector": "Wireless Mesh Access Control & Smart Building IoT Platform",
        "employee_count": "30-65",
        "funding_stage_investors": "Pre-Series A $2.5M (Accel Atoms 3.0)",
        "work_model_location": "Goa / Bengaluru / Remote",
        "career_page_url": "https://spintly.com/careers",
        "career_email": "rohin@spintly.com",
        "hiring_decision_maker": "Rohin Parkar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time device event streaming and cloud telemetry dashboards, matching Nalin's backend event queue management.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Asets",
        "website": "https://asets.io",
        "domain_sector": "Cloud-Native Multidisciplinary CAD & AI Simulation Platform",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1.2M (Accel Atoms 3.0)",
        "work_model_location": "Delhi-NCR (Noida) / Remote",
        "career_page_url": "https://asets.io",
        "career_email": "prateek@asets.io",
        "hiring_decision_maker": "Prateek Sharma (Founder & CEO)",
        "nalin_tech_fit_hook": "Browser-based 3D simulation canvassing and distributed cloud computation backends, connecting to Nalin's Next.js and FastAPI stack.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "ContraVault AI",
        "website": "https://contravault.ai",
        "domain_sector": "Enterprise LLM Security Firewall & Prompt Attack Guardrails",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $1.2M (Accel Atoms, security angels)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://contravault.ai",
        "career_email": "siddharth@contravault.ai",
        "hiring_decision_maker": "Siddharth Joshi (Founder & CEO)",
        "nalin_tech_fit_hook": "Reverse proxy inspection for prompt injection and token obfuscation, directly matching Nalin's AST code audit tool.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Helium",
        "website": "https://helium.sh",
        "domain_sector": "Autonomous AI Component Testing for Next.js & React Applications",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $1M (Accel Atoms, devtool angels)",
        "work_model_location": "Delhi-NCR (Noida) / Remote",
        "career_page_url": "https://helium.sh",
        "career_email": "harshil@helium.sh",
        "hiring_decision_maker": "Harshil Agrawal (Founder & CEO)",
        "nalin_tech_fit_hook": "DOM visual regression capture and automated component test synthesis, matching Nalin's Next.js frontend and AST testing skills.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Capitol AI",
        "website": "https://www.capitol.ai",
        "domain_sector": "AI Knowledge Synthesis & Multimedia Research Storytelling",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $2M (Together Fund)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.capitol.ai",
        "career_email": "founders@capitol.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-source citation grounding and structured narrative generation, directly connecting to Nalin's Notovo LangGraph note engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Gibran",
        "website": "https://gibran.ai",
        "domain_sector": "Scale-Free Learning AI for Complex Autonomous System Reasoning",
        "employee_count": "6-15",
        "funding_stage_investors": "Seed $1.5M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://gibran.ai",
        "career_email": "founders@gibran.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Complex reasoning graph structures and agent decision trees, directly matching Nalin's LangGraph workflow implementations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Chaotix AI",
        "website": "https://chaotix.ai",
        "domain_sector": "Instant AI-Led Game Creation & Real-Time World Simulation Engine",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.5M (Together Fund)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://chaotix.ai",
        "career_email": "founders@chaotix.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Real-time state machines and prompt-driven procedural generation backends, matching Nalin's full-stack product architecture.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "DreamTeam",
        "website": "https://dreamteam.ai",
        "domain_sector": "AI-Native Autonomous CRM & Proactive Enterprise Sales Agent",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1.8M (Together Fund)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://dreamteam.ai",
        "career_email": "founders@dreamteam.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Autonomous background follow-up agents and CRM webhook triggers, matching Nalin's background job and API workflow experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Nava AI",
        "website": "https://nava.ai",
        "domain_sector": "Specialized Cloud Technology & Infrastructure for AI Systems",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $1.5M (Blume Ventures)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://nava.ai",
        "career_email": "founders@nava.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Distributed container orchestration and low-latency storage access, connecting to Nalin's Azure cloud migrations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Sing One Song",
        "website": "https://singonesong.ai",
        "domain_sector": "AI Vocal Coach & Real-Time Pitch Analysis for Musicians",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $800K (Blume Ventures)",
        "work_model_location": "Delhi-NCR (Delhi) / Hybrid",
        "career_page_url": "https://singonesong.ai",
        "career_email": "founders@singonesong.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Audio pitch DSP extraction and real-time visual feedback canvas, matching Nalin's Prep War Room pitch TTS analysis work.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "PowerUp Money",
        "website": "https://powerup.money",
        "domain_sector": "AI-Driven Commission-Free Investment Advisory & Wealth Management",
        "employee_count": "8-18",
        "funding_stage_investors": "Seed $1M (Blume Ventures)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://powerup.money",
        "career_email": "founders@powerup.money",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Algorithmic risk profiling workflows and Next.js reactive charts, matching Nalin's full-stack product engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Xccelera AI",
        "website": "https://xccelera.ai",
        "domain_sector": "Agentic AI Orchestration & Multi-Model Enterprise Task Automation",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1.2M (Speciale Invest)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://xccelera.ai",
        "career_email": "founders@xccelera.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Multi-agent task decomposition and state persistence, directly aligning with Nalin's LangGraph implementations.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Adopt AI",
        "website": "https://adopt.is",
        "domain_sector": "In-App Agentic Experiences & Autonomous User Onboarding Copilot",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $2M (Elevation Capital)",
        "work_model_location": "Bengaluru / Delhi-NCR / Remote",
        "career_page_url": "https://adopt.is",
        "career_email": "founders@adopt.is",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Browser DOM introspection and contextual guide overlay injection, matching Nalin's frontend DOM and React engineering.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "ALT Fashion",
        "website": "https://altfashion.ai",
        "domain_sector": "Multimodal AI Search & Real-Time Visual Discovery for Apparel",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $800K (Antler India)",
        "work_model_location": "Bengaluru / Remote (India)",
        "career_page_url": "https://altfashion.ai",
        "career_email": "founders@altfashion.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Image embedding similarity search and high-scale catalog indexing, connecting to Nalin's Voyatri image storage optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Bookee",
        "website": "https://bookee.app",
        "domain_sector": "AI Vertical SaaS & Campaign Automation for the Wellness Industry",
        "employee_count": "20-40",
        "funding_stage_investors": "Seed $1.5M (Antler India)",
        "work_model_location": "Delhi-NCR (Noida) / Hybrid",
        "career_page_url": "https://bookee.app/careers",
        "career_email": "vignesh@bookee.app",
        "hiring_decision_maker": "Vignesh Kumar (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time class booking state machines and transactional database backends, fitting Nalin's PostgreSQL performance optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "HireBound",
        "website": "https://hirebound.ai",
        "domain_sector": "AI Autonomous Candidate Sourcing & Skill Scoring Engine",
        "employee_count": "6-14",
        "funding_stage_investors": "Seed $800K (Antler India)",
        "work_model_location": "Delhi-NCR (Gurgaon) / Remote",
        "career_page_url": "https://hirebound.ai",
        "career_email": "founders@hirebound.ai",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Semantic resume parsing and technical qualification vector scoring, matching Nalin's NLP and RAG experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Infer.so",
        "website": "https://infer.so",
        "domain_sector": "Autonomous Voice AI Agents for Insurance & Loan Underwriting",
        "employee_count": "8-16",
        "funding_stage_investors": "Seed $1M (Antler India)",
        "work_model_location": "Delhi-NCR (Delhi) / Bengaluru",
        "career_page_url": "https://infer.so",
        "career_email": "founders@infer.so",
        "hiring_decision_maker": "Founding Engineering Team",
        "nalin_tech_fit_hook": "Bidirectional voice streaming pipelines with CRM field auto-fill, matching Nalin's full-stack FastAPI and speech workflows.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Enkrypt AI",
        "website": "https://enkryptai.com",
        "domain_sector": "Enterprise GenAI Compliance, Red Teaming & Runtime Security Guardrails",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $2.2M (prominent cyber funds)",
        "work_model_location": "Delhi-NCR (Gurugram) / Remote",
        "career_page_url": "https://enkryptai.com",
        "career_email": "sahil@enkryptai.com",
        "hiring_decision_maker": "Sahil Agarwal (Co-Founder & CEO) & Prashanth Harshangi (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "Real-time prompt payload vulnerability filtering and automated red-teaming, directly connecting to Nalin's AST code audit tools.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "DeepSource",
        "website": "https://deepsource.com",
        "domain_sector": "Automated Code Health, Static Analysis & Autofix Engine",
        "employee_count": "30-55",
        "funding_stage_investors": "Seed $2.7M (645 Ventures, Y Combinator)",
        "work_model_location": "Bengaluru / Fully Remote (India)",
        "career_page_url": "https://deepsource.com/careers",
        "career_email": "sanket@deepsource.com",
        "hiring_decision_maker": "Sanket Saurav (Founder & CEO)",
        "nalin_tech_fit_hook": "AST visitor patterns and automated code refactoring passes, directly matching Nalin's Code Sage AST audit engine.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Arize AI",
        "website": "https://arize.com",
        "domain_sector": "AI Observability, Drift Monitoring & Open-Source Phoenix Platform",
        "employee_count": "60-95",
        "funding_stage_investors": "Series B $38M (Foundation Capital, TCV)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://arize.com/careers",
        "career_email": "jason@arize.com",
        "hiring_decision_maker": "Jason Lopatecki (Co-Founder & CEO) & Aparna Dhinakaran (Co-Founder & CPO)",
        "nalin_tech_fit_hook": "Embedding drift detection and trace-level span tracking for agents, matching Nalin's production model benchmarking at NimitAI.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Coactive AI",
        "website": "https://coactive.ai",
        "domain_sector": "Multimodal Visual Data Search & Video Analytics for Enterprise",
        "employee_count": "20-40",
        "funding_stage_investors": "Series B $30M (Cherryrock Capital, Emerson Collective)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://coactive.ai/careers",
        "career_email": "cody@coactive.ai",
        "hiring_decision_maker": "Cody Coleman (Co-Founder & CEO) & Will Gaviria Rojas (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "High-throughput visual feature vector indexing, connecting to Nalin's Voyatri project (80%+ lower image storage cost).",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Encord",
        "website": "https://encord.com",
        "domain_sector": "Multimodal AI Data Curation, Active Learning & Micro-Model Training",
        "employee_count": "45-80",
        "funding_stage_investors": "Series B $30M (Next47, Y Combinator)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://encord.com/careers",
        "career_email": "eric@encord.com",
        "hiring_decision_maker": "Eric Landau (Co-Founder & CEO) & Ulrik Stig Hansen (Co-Founder & President)",
        "nalin_tech_fit_hook": "Data quality filtering algorithms and active learning loops, aligning with Nalin's database sanitization and dataset cleanup.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Qwak",
        "website": "https://www.qwak.com",
        "domain_sector": "End-to-End Production Machine Learning Platform & Model Serving",
        "employee_count": "30-60",
        "funding_stage_investors": "Series A $12M (Bessemer Venture Partners)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.qwak.com/careers",
        "career_email": "alon@qwak.com",
        "hiring_decision_maker": "Alon Lev (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Real-time model deployment and batch feature extraction pipelines, connecting to Nalin's backend database migration and optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Replicate",
        "website": "https://replicate.com",
        "domain_sector": "Cloud API & Open-Source ML Model Hosting Platform (Cog)",
        "employee_count": "30-65",
        "funding_stage_investors": "Series B $40M (Andreessen Horowitz)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://replicate.com/careers",
        "career_email": "ben@replicate.com",
        "hiring_decision_maker": "Ben Firshman (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Dockerized model containerization and fast cold-start GPU boot times, directly connecting to Nalin's 63% latency reduction achievements.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Fireworks AI",
        "website": "https://fireworks.ai",
        "domain_sector": "Ultra-Fast Generative AI Inference Engine & Compound AI Platform",
        "employee_count": "25-55",
        "funding_stage_investors": "Series B $52M (Benchmark, Sequoia Capital)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://fireworks.ai/careers",
        "career_email": "lin@fireworks.ai",
        "hiring_decision_maker": "Lin Qiao (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Speculative decoding and optimized CUDA kernel inference serving, matching Nalin's production LLM throughput optimization.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Anyscale",
        "website": "https://www.anyscale.com",
        "domain_sector": "Distributed AI Compute Platform & Ray Ecosystem for LLMs",
        "employee_count": "70-100",
        "funding_stage_investors": "Series B $100M (Andreessen Horowitz, Addition)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.anyscale.com/careers",
        "career_email": "robert@anyscale.com",
        "hiring_decision_maker": "Robert Nishihara (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Distributed job scheduling and batch inference scaling with Ray, connecting to Nalin's background task and database optimization background.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Predibase",
        "website": "https://predibase.com",
        "domain_sector": "Fine-Tuning & Serving Platform for Open-Source Small & Large Models",
        "employee_count": "25-50",
        "funding_stage_investors": "Series A $16M (Felicis Ventures, Greylock)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://predibase.com/careers",
        "career_email": "piero@predibase.com",
        "hiring_decision_maker": "Piero Molino (Co-Founder & CEO) & Travis Addair (Co-Founder & CTO)",
        "nalin_tech_fit_hook": "LoRA adapter hot-swapping and low-overhead fine-tuning workflows, matching Nalin's LLM generation speedups.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Weights & Biases",
        "website": "https://wandb.ai",
        "domain_sector": "Developer Platform for Machine Learning Experiment Tracking & LLMOps",
        "employee_count": "80-100",
        "funding_stage_investors": "Series C $135M (Coatue, Insight Partners)",
        "work_model_location": "Bengaluru / Fully Remote (India)",
        "career_page_url": "https://wandb.ai/careers",
        "career_email": "lukas@wandb.ai",
        "hiring_decision_maker": "Lukas Biewald (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Model artifact lineage tracking and interactive telemetry dashboards, matching Nalin's Next.js and data pipeline experience.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Vespa.ai",
        "website": "https://vespa.ai",
        "domain_sector": "High-Throughput Open-Source Vector Search & Structured Data Engine",
        "employee_count": "20-45",
        "funding_stage_investors": "Series A $31M (Blossom Capital)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://vespa.ai/careers",
        "career_email": "trond@vespa.ai",
        "hiring_decision_maker": "Trond H. (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Sub-10ms hybrid text and vector ranking at web scale, matching Nalin's database indexing and query tuning.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Weaviate",
        "website": "https://weaviate.io",
        "domain_sector": "Open-Source AI Vector Search Engine & Modular Embedding Database",
        "employee_count": "40-75",
        "funding_stage_investors": "Series B $50M (Index Ventures, Battery Ventures)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://weaviate.io/careers",
        "career_email": "bob@weaviate.io",
        "hiring_decision_maker": "Bob van Luijt (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "GraphQL vector queries and inverted index hybrid search, directly relating to Nalin's FastAPI and database optimization projects.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Pinecone",
        "website": "https://www.pinecone.io",
        "domain_sector": "Managed Cloud Vector Database for High-Scale Production AI",
        "employee_count": "60-95",
        "funding_stage_investors": "Series B $100M (Andreessen Horowitz)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.pinecone.io/careers",
        "career_email": "edo@pinecone.io",
        "hiring_decision_maker": "Edo Liberty (Founder & CEO)",
        "nalin_tech_fit_hook": "Serverless vector indexing and partitioned metadata filtering, connecting to Nalin's PostgreSQL optimization and database migration.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "Cerebrium",
        "website": "https://www.cerebrium.ai",
        "domain_sector": "Serverless AI Framework & Sub-Second Cold-Start GPU Platform",
        "employee_count": "10-22",
        "funding_stage_investors": "Seed $2.5M (prominent devtool funds)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.cerebrium.ai/careers",
        "career_email": "michael@cerebrium.ai",
        "hiring_decision_maker": "Michael L. (Co-Founder & CEO)",
        "nalin_tech_fit_hook": "Micro-container warm-pooling and voice pipeline serving, directly matching Nalin's 63% latency reduction on LLM pipelines.",
        "outreach_status": "To Contact"
    },
    {
        "company_name": "TrueMedia",
        "website": "https://www.truemedia.org",
        "domain_sector": "AI Deepfake Detection & Synthetic Media Forensics Technology",
        "employee_count": "10-25",
        "funding_stage_investors": "Non-profit Seed $5M (Oren Etzioni, prominent AI philanthropies)",
        "work_model_location": "Fully Remote (India)",
        "career_page_url": "https://www.truemedia.org",
        "career_email": "oren@truemedia.org",
        "hiring_decision_maker": "Dr. Oren Etzioni (Founder & CEO)",
        "nalin_tech_fit_hook": "Multimodal video and audio artifact verification pipelines, matching Nalin's full-stack Next.js and audio inspection skills.",
        "outreach_status": "To Contact"
    }
]

print(f"Loaded {len(batch2_list)} high-quality replacement templates for Batch 2.")
